const esc=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
export function colourVisual(id,lang){
 const pt=lang==='pt';
 const table=(heading,headers,rows)=>`<section class="colour-study"><h2>${heading}</h2><table><thead><tr>${headers.map(h=>`<th scope="col">${h}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map((v,i)=>i===0?`<th scope="row">${v}</th>`:`<td>${v}</td>`).join('')}</tr>`).join('')}</tbody></table></section>`;
 if(id===1)return table(pt?'As quatro cores-imagem':'The four image colours',pt?['Cor','Relação na classificação de Steiner']:['Colour','Relation in Steiner’s classification'],pt?[['Verde','Imagem sem vida do vivo'],['Flor de pessegueiro','Imagem viva da alma'],['Branco / luz','Imagem anímica do espírito'],['Preto','Imagem espiritual do que não tem vida']]:[['Green','Lifeless image of the living'],['Peach-blossom','Living image of the soul'],['White / light','Soul’s image of spirit'],['Black','Spiritual image of the lifeless']]);
 if(id===8)return `<aside class="source-note"><h2>${pt?'Contexto científico complementar':'Supplementary scientific context'}</h2><p><a href="https://spaceplace.nasa.gov/blue-sky/en/">NASA: ${pt?'por que o céu é azul':'why the sky is blue'}</a> · <a href="https://www.nei.nih.gov/eye-health-information/healthy-vision/how-eyes-work">National Eye Institute: ${pt?'como os olhos funcionam':'how the eyes work'}</a></p></aside>`;
 if(id===12)return table(pt?'Sequência da palestra':'The lecture’s sequence',pt?['Hierarquia','Manifestação e etapa']:['Hierarchy','Manifestation and stage'],pt?[['Primeira: Serafins, Querubins, Tronos','Calor · antigo Saturno'],['Segunda: Kyriotetes, Dynamis, Exusiai','Luz e ar · antigo Sol'],['Terceira: Archai, Arcanjos, Anjos','Cor e água · antiga Lua'],['Quarta: humanidade original','Vida e contornos sólidos · Terra']]:[['First: Seraphim, Cherubim, Thrones','Warmth · Old Saturn'],['Second: Kyriotetes, Dynamis, Exusiai','Light and air · Old Sun'],['Third: Archai, Archangels, Angels','Colour and water · Old Moon'],['Fourth: original humanity','Life and solid contours · Earth']]);
 let studies=[];
 if(id===2)studies=pt?[['yellow','Amarelo: centro forte → borda clara'],['blue','Azul: borda forte → centro claro'],['red','Vermelho: distribuição uniforme']]:[['yellow','Yellow: strong centre → pale edge'],['blue','Blue: strong edge → pale centre'],['red','Red: even distribution']];
 if(id===4||id===9)studies=pt?[['pair-a','A: vermelho à esquerda, azul à direita'],['pair-b','B: azul à esquerda, vermelho à direita']]:[['pair-a','A: red on the left, blue on the right'],['pair-b','B: blue on the left, red on the right']];
 if(id===11)studies=pt?[['weight-a','A: pequena área escura junto à borda'],['weight-b','B: a mesma área escura junto ao centro']]:[['weight-a','A: small dark area near the edge'],['weight-b','B: the same dark area near the centre']];
 if(!studies.length)return '';
 return `<section class="colour-study"><h2>${pt?'Compare as disposições':'Compare the arrangements'}</h2><div class="colour-studies">${studies.map(([cls,caption])=>`<figure><div class="colour-swatch ${cls}" role="img" aria-label="${esc(caption)}"><i aria-hidden="true"></i><b aria-hidden="true"></b></div><figcaption>${esc(caption)}</figcaption></figure>`).join('')}</div><p>${pt?'Estudos digitais originais, não reproduções dos desenhos do livro. As legendas descrevem a disposição; você pode realizar a atividade pela descrição. Telas, materiais e percepção individual alteram a aparência. Registre também diferenças em relação à experiência proposta.':'Original digital studies, not reproductions of the book’s drawings. Captions describe each arrangement; you can use the descriptions for the activity. Screens, materials and individual perception affect appearance. Record differences from the proposed experience too.'}</p></section>`;
}
