const esc=s=>String(s).replaceAll('&','&amp;').replaceAll('"','&quot;').replaceAll('<','&lt;');
export function guidedLab(course,id,lang){
 const pt=lang==='pt',t=(a,b)=>pt?b:a;
 const box=(type,title,body)=>`<section class="study-lab" data-lab="${type}"><h2>${title}</h2>${body}</section>`;
 const output='<p data-lab-output role="status" aria-live="polite"></p>';
 if((course==='philosophy-of-freedom'&&id===4)||(course==='theosophy'&&id===18))return box('arithmetic',t('Reconstruct the steps','Reconstrua os passos'),`<p>${t('Calculate ((3 × 3) + 1) ÷ 2. Write the connections in your first attempt above, then check the result.','Calcule ((3 × 3) + 1) ÷ 2. Escreva as ligações na primeira tentativa acima e confira o resultado.')}</p><div class="js-only"><label for="lab-result">${t('Your result','Seu resultado')}</label> <input id="lab-result" type="number" step="any"> <button class="study-button" type="button">${t('Check my steps','Conferir meus passos')}</button></div>${output}`);
 if(course==='colour'&&id===2)return box('colour',t('Change one thing, look again','Mude uma coisa, observe de novo'),`<p>${t('Compare two distributions of the same hue. Describe where your attention goes before reading Steiner’s account. These are original digital studies; screen appearance varies. Use the captions if you prefer a verbal comparison.','Compare duas distribuições da mesma cor. Descreva para onde sua atenção vai antes de ler Steiner. Estes são estudos digitais originais; a aparência varia conforme a tela. Use as legendas se preferir uma comparação verbal.')}</p><div class="lab-pair"><figure><div class="lab-patch" aria-hidden="true"></div><figcaption>A: ${t('dense centre, pale edge','centro intenso, borda clara')}</figcaption></figure><figure><div class="lab-patch edge" aria-hidden="true"></div><figcaption>B: ${t('pale centre, dense edge','centro claro, borda intensa')}</figcaption></figure></div><div class="study-actions js-only"><label for="lab-hue">${t('Hue','Cor')}</label><select id="lab-hue"><option value="yellow">${t('Yellow','Amarelo')}</option><option value="blue">${t('Blue','Azul')}</option></select><button data-swap class="study-button" type="button">${t('Swap the arrangements','Trocar as composições')}</button></div>${output}<p>${t('Keep the hue fixed first. Swap only the distribution. Then try blue. A different response—or no clear difference—is useful evidence about your experience.','Primeiro mantenha a cor. Troque apenas a distribuição. Depois experimente azul. Uma resposta diferente — ou nenhuma diferença clara — é um dado útil sobre sua experiência.')}</p>`);
 if(course==='encountering-the-self'&&id===3){
  const replies=pt?[
   ['Perguntar o que aconteceu','Uma continuação possível: “Achei que a caixa era de todos.” Agora sabemos que o rótulo estava pouco claro. Reconheça isso e combine a devolução ou reposição do material. A nova informação muda a interpretação, sem eliminar a reparação.'],
   ['Dizer “Você é egoísta”','Esse rótulo atribui um traço antes de ouvir a criança. Pode encerrar a conversa sem esclarecer o ocorrido. Reescreva a fala descrevendo o material usado e fazendo uma pergunta.'],
   ['Repor tudo sem conversar','Resolver sozinho pode reparar a perda, mas deixa a regra pouco clara e exclui a participação da criança. Acrescente uma pergunta e uma tarefa de reparação adequada à situação.']
  ]:[
   ['Ask what happened','One possible continuation: “I thought the box was shared.” We now learn that the label was unclear. Acknowledge that and agree how to return or replace the materials. New information changes the interpretation without removing responsibility for repair.'],
   ['Say “You are selfish”','This assigns a trait before hearing the child. It may end the conversation without clarifying what happened. Rewrite the response to describe the materials used and ask a question.'],
   ['Replace everything without talking','Solving it alone may repair the loss but leaves the rule unclear and excludes the child’s participation. Add a question and an appropriate part in making things right.']];
  return box('dialogue',t('Let the next answer change your view','Deixe a próxima resposta mudar sua interpretação'),`<p>${t('A child used materials from someone else’s box. Choose an opening response, read the feedback, then try another. This is an authored scenario, not a prediction of how any child will respond.','Uma criança usou materiais da caixa de outra pessoa. Escolha uma resposta inicial, leia o comentário e experimente outra. Esta é uma situação didática original, não uma previsão da reação de uma criança.')}</p><div class="study-actions js-only">${replies.map(([label,reply])=>`<button type="button" class="study-button" data-reply="${esc(reply)}">${label}</button>`).join('')}</div>${output}<details class="guided-hint"><summary>${t('Read all possible responses','Ler todas as respostas possíveis')}</summary>${replies.map(([label,reply])=>`<h3>${label}</h3><p>${reply}</p>`).join('')}</details>`);
 }
 if(course==='theosophy'&&id===6)return box('map',t('How can nine become seven?','Como nove se tornam sete?'),`<p>${t('Sketch nine labelled spaces: A physical body; B life body; C soul body; D sentient soul; E intellectual soul; F consciousness soul; G spirit self; H life spirit; I spirit man. Predict which neighbouring pairs the passage brings together. This represents Steiner’s classification.','Desenhe nove espaços: A corpo físico; B corpo vital; C corpo anímico; D alma da sensação; E alma do intelecto; F alma da consciência; G personalidade espiritual; H espírito vital; I homem-espírito. Preveja quais pares vizinhos o trecho reúne. O esquema representa a classificação de Steiner.')}</p><details class="guided-hint"><summary>${t('First grouping','Primeiro agrupamento')}</summary><p>${t('Bring C and D together: soul body and sentient soul form one connection. Keep both names inside one bracket. Nine spaces become eight groups.','Reúna C e D: corpo anímico e alma da sensação formam uma ligação. Mantenha os dois nomes no mesmo colchete. Nove espaços tornam-se oito grupos.')}</p></details><details class="guided-hint"><summary>${t('Second grouping and check','Segundo agrupamento e conferência')}</summary><p>${t('Bring F and G together: consciousness soul and spirit self. The seven groups are A, B, [C+D], E, [F+G], H, I. Nothing has been erased. Explain the relationship rather than saying two members disappeared.','Reúna F e G: alma da consciência e personalidade espiritual. Os sete grupos são A, B, [C+D], E, [F+G], H, I. Nada foi apagado. Explique a relação, em vez de dizer que dois membros desapareceram.')}</p></details>`);
 if(course==='encountering-the-self'&&id===15)return box('reflection',t('Predict the reflection','Preveja a reflexão'),`<p>${t('On paper, predict the partners of the three dots across the dashed vertical axis. Then reveal the reflected curve. This original geometry exercise illustrates reflection, not a claim about bodily development.','No papel, preveja os correspondentes dos três pontos do outro lado do eixo vertical tracejado. Depois revele a curva refletida. Este exercício geométrico original ilustra reflexão, não uma afirmação sobre desenvolvimento corporal.')}</p><svg viewBox="0 0 420 240" role="img" aria-labelledby="lab-reflection-title lab-reflection-desc"><title id="lab-reflection-title">${t('A curve beside a reflection axis','Uma curva ao lado de um eixo de reflexão')}</title><desc id="lab-reflection-desc">${t('The vertical axis is x=210. Three points are (80,40), (140,120), (90,200). Find their equal distances on the opposite side.','O eixo vertical é x=210. Três pontos são (80,40), (140,120), (90,200). Encontre as distâncias iguais no lado oposto.')}</desc><path d="M210 10V230" stroke="#776b7c" stroke-width="2" stroke-dasharray="6 5"/><g fill="#456d59" stroke="#456d59" stroke-width="3"><path d="M80 40 Q195 70 140 120 Q20 170 90 200" fill="none"/><circle cx="80" cy="40" r="5"/><circle cx="140" cy="120" r="5"/><circle cx="90" cy="200" r="5"/></g><g class="reflection-answer" transform="translate(420 0) scale(-1 1)" fill="#9b572e" stroke="#9b572e" stroke-width="3"><path d="M80 40 Q195 70 140 120 Q20 170 90 200" fill="none"/><circle cx="80" cy="40" r="5"/><circle cx="140" cy="120" r="5"/><circle cx="90" cy="200" r="5"/></g></svg><button class="study-button js-only" type="button" aria-pressed="false">${t('Show / hide the reflection','Mostrar / ocultar a reflexão')}</button>${output}<details class="guided-hint"><summary>${t('Check the coordinates','Conferir as coordenadas')}</summary><p>(340, 40), (280, 120), (330, 200). ${t('The height is unchanged. Horizontal distances from x=210 are 130, 70 and 120 on each side.','A altura não muda. As distâncias horizontais de x=210 são 130, 70 e 120 em cada lado.')}</p></details>`);
 if(course==='according-to-luke'&&[4,5,7].includes(id)){
  const stages=pt?[
   ['1 · Duas linhagens','Na interpretação de Steiner, a linhagem de Salomão é associada ao relato de Mateus e à individualidade de Zaratustra; a linhagem de Natã, ao relato de Lucas e a uma corrente adâmica preservada. Não trate essa leitura como uma afirmação explícita dos Evangelhos.'],
   ['2 · Aos doze anos','Steiner descreve a passagem do eu de Zaratustra do menino de Salomão para o menino de Natã. A contribuição de Buda é uma relação distinta. Dê nomes às relações; não reúna todas as figuras em uma só identidade.'],
   ['3 · O batismo','Na sequência apresentada por Steiner, o batismo aos trinta anos marca a entrada do Cristo. Distinga esse acontecimento do episódio aos doze anos. Localize no texto o que ele afirma sobre a individualidade que parte.']
  ]:[
   ['1 · Two lineages','In Steiner’s interpretation, the Solomon lineage is associated with Matthew’s account and the individuality of Zarathustra; the Nathan lineage with Luke’s account and a preserved Adamic stream. Do not treat this reading as an explicit statement in the Gospels.'],
   ['2 · At twelve','Steiner describes the Zarathustra I passing from the Solomon child to the Nathan child. Buddha’s contribution is a distinct relationship. Name the relationships; do not merge all the figures into one identity.'],
   ['3 · The baptism','In Steiner’s sequence, the baptism at thirty marks the entry of the Christ. Distinguish this from the event at twelve. Locate what the passage says about the departing individuality.']];
  return box('map',t('Build an attributed map','Construa um mapa com atribuição'),`<p>${t('First sketch the names and relationships you remember. Reveal one stage at a time and correct the arrows. This map summarizes Steiner’s spiritual interpretation, not established biography. Later stages preview the following readings.','Primeiro desenhe os nomes e relações de que se lembra. Revele uma etapa por vez e corrija as setas. O mapa resume a interpretação espiritual de Steiner, não uma biografia estabelecida. As etapas posteriores antecipam as próximas leituras.')}</p>${stages.map(([a,b])=>`<details class="guided-hint"><summary>${a}</summary><p>${b}</p></details>`).join('')}<p>${t('Return to the assigned lecture. Support each arrow with a passage, and distinguish the Gospel account from Steiner’s additional interpretation. An unlocated arrow remains a question.','Volte à palestra indicada. Apoie cada seta em um trecho e distinga o relato evangélico da interpretação adicional de Steiner. Uma seta sem apoio permanece uma pergunta.')}</p>`);
 }
 return '';
}
