// One original opening question per lesson, with a matching Brazilian Portuguese prompt.
// The existing reading, examples, activities and annotated answers remain the substantive source teaching.
const rows={
theosophy:[
'What do you notice, feel and consider before deciding how to help?|O que você percebe, sente e considera antes de decidir como ajudar?',
'Two people see the same stars. What can differ, and what can they understand together?|Duas pessoas veem as mesmas estrelas. O que pode diferir e o que podem compreender juntas?',
'Is the heard tone the same thing as the annoyance it awakens?|O som ouvido é a mesma coisa que o incômodo que desperta?',
'What difference between a stone and a growing plant needs explanation?|Que diferença entre uma pedra e uma planta em crescimento precisa de explicação?',
'What changes between feeling hurt by a correction and examining whether it is right?|O que muda entre sentir-se magoado com uma correção e examinar se ela está certa?',
'When two people say “I,” do they refer to the same person?|Quando duas pessoas dizem “eu”, referem-se à mesma pessoa?',
'How could nine distinctions become seven groups without losing a label?|Como nove distinções podem formar sete grupos sem perder um nome?',
'Can you keep a skill while forgetting the occasions on which you learned it?|É possível conservar uma habilidade e esquecer as ocasiões em que a aprendeu?',
'What does quick learning show, and what does it leave unexplained?|O que a aprendizagem rápida mostra e o que deixa sem explicação?',
'Does a break in awareness erase a responsibility? Where does this analogy stop?|Uma interrupção da consciência apaga uma responsabilidade? Onde termina essa analogia?',
'How would you draw connection and separation without treating them as places?|Como desenharia ligação e separação sem tratá-las como lugares?',
'What persists when the mug is no longer in its usual place?|O que permanece quando a caneca já não está no lugar habitual?',
'What does a building plan explain, and what is missing from that comparison?|O que uma planta de edifício explica e o que falta nessa comparação?',
'Must a more capable carpenter repeat the first object exactly?|Uma pessoa mais hábil em carpintaria precisa repetir exatamente o primeiro objeto?',
'Can a person develop a capacity without gaining income or status?|Alguém pode desenvolver uma capacidade sem aumentar renda ou posição social?',
'Which relationship does the ice-and-water comparison help you think about?|Que relação a comparação entre gelo e água ajuda a pensar?',
'Does observing a shared festival identify what spiritually underlies it?|Observar uma festa compartilhada identifica o que a fundamentaria espiritualmente?',
'When someone calls a voice warm, what does the word carry across?|Quando alguém chama uma voz de calorosa, o que a palavra transporta entre experiências?',
'Can you explain an argument accurately and still question it?|Você pode explicar um argumento com precisão e ainda questioná-lo?',
'Does feeling irritated decide whether a corrected date is accurate?|Sentir irritação decide se uma data corrigida está certa?',
'Which starting information determines the departure time? What could change it?|Que informação inicial determina o horário de saída? O que poderia mudá-lo?',
'What else must you ask besides which option a person chose?|O que mais precisa perguntar além da opção escolhida?',
'What makes an explanation of relationships stronger than a list of terms?|O que torna explicar relações mais completo que listar termos?'],
'higher-worlds':[
'What can improved listening show, and what further claim would need support?|O que uma escuta melhor pode mostrar e que afirmação adicional precisaria de apoio?',
'How can you take an unfamiliar idea seriously while keeping your judgment?|Como levar uma ideia desconhecida a sério e preservar seu julgamento?',
'What is the difference between describing an interruption and judging the whole person?|Qual a diferença entre descrever uma interrupção e julgar a pessoa inteira?',
'What did you hear, what did you feel, and what did you infer about the dog?|O que ouviu, o que sentiu e o que inferiu sobre o cachorro?',
'Why might a seed and a model that look alike develop differently?|Por que uma semente e uma imitação parecidas poderiam se desenvolver de modo diferente?',
'What could you ask the quiet classmate instead of explaining their hidden condition?|O que perguntaria à pessoa quieta em vez de explicar sua condição oculta?',
'What distinguishes presence of mind from simply acting quickly?|O que distingue presença de espírito de simplesmente agir depressa?',
'What information would Sam need before writing a firm response?|De que informação Sam precisaria antes de escrever uma resposta firme?',
'How could the group investigate responsibility without assuming equal blame?|Como o grupo investigaria responsabilidade sem presumir culpa igual?',
'If the supplies are no longer needed, what would keeping the promise mean?|Se os materiais já não são necessários, o que significaria cumprir a promessa?',
'What is added when a coloured drawing becomes a claim about someone’s spiritual organs?|O que se acrescenta quando um desenho colorido vira afirmação sobre órgãos espirituais de alguém?',
'How might an expectation change the way an ordinary message is interpreted?|Como uma expectativa pode mudar a interpretação de uma mensagem comum?',
'Could one clock sound enter more than one dream scene?|Um som de relógio poderia entrar em mais de uma cena de sonho?',
'Which link between the fragments was given, and which did you supply?|Que ligação entre os fragmentos foi dada e qual você acrescentou?',
'How could understanding, concern and action work together in the same response?|Como compreensão, cuidado e ação poderiam trabalhar juntos na mesma resposta?',
'What does the ledger help explain about responsibility, and what does it leave out?|O que o registro ajuda a explicar sobre responsabilidade e o que deixa de fora?',
'What changes when a capacity serves others as well as its possessor?|O que muda quando uma capacidade serve aos outros e também a quem a possui?',
'How does knowing your position change the use of a map?|Como conhecer sua posição muda o uso de um mapa?',
'Which idea connects the two books, and where do their claims differ?|Que ideia liga os dois livros e onde suas afirmações diferem?'],
'philosophy-of-freedom':[
'What would settle the meeting time, and what would explain your reason for attending?|O que esclareceria o horário da reunião e o que explicaria sua razão para participar?',
'Does knowing which day was chosen tell you why it was chosen?|Saber qual dia foi escolhido revela por que foi escolhido?',
'What is the difference between noticing movement and explaining it?|Qual a diferença entre perceber um movimento e explicá-lo?',
'What is given in the event, and what connection do you add to explain it?|O que é dado no acontecimento e que ligação você acrescenta para explicá-lo?',
'Calculate ((3 × 3) + 1) ÷ 2, then describe how you arrived at the result.|Calcule ((3 × 3) + 1) ÷ 2 e descreva como chegou ao resultado.',
'When the card is tilted, what changes in appearance and what do you judge remains?|Quando o cartão é inclinado, o que muda na aparência e o que você julga permanecer?',
'Does dependence on a perceiver establish that only representations are known?|Depender de alguém que percebe estabelece que só representações são conhecidas?',
'What connects the three flower records beyond their shared name?|O que liga os três registros da flor além do nome compartilhado?',
'How can two different drawings express the same triangular relationship?|Como dois desenhos diferentes expressam a mesma relação triangular?',
'What would distinguish another bicycle from the same bicycle encountered again?|O que distinguiria outra bicicleta da mesma bicicleta encontrada de novo?',
'Is missing information the same as an unclear question or an impossible answer?|Informação ausente equivale a pergunta pouco clara ou resposta impossível?',
'Why would moving a chair answer the concern, rather than merely express goodwill?|Por que mover uma cadeira responderia à necessidade, em vez de apenas expressar boa vontade?',
'Which is the aim, what may make it attractive, and what makes it feasible?|Qual é a finalidade, o que pode torná-la atraente e o que a torna viável?',
'Could the same helpful act arise from different grounds of action?|O mesmo ato útil poderia nascer de fundamentos de ação diferentes?',
'Can two people understand the same aim and propose different deeds?|Duas pessoas podem compreender a mesma finalidade e propor atos diferentes?',
'What exists now that lets a future meeting guide present action?|O que existe agora e permite que uma reunião futura oriente a ação presente?',
'Can you explain the reason for inclusion without repeating the slogan?|Consegue explicar a razão da inclusão sem repetir o lema?',
'What differs between imagining a useful response and knowing how to deliver it?|Qual a diferença entre imaginar uma resposta útil e saber realizá-la?',
'Can enjoyment during practice coexist with disappointment about the result?|O prazer durante a prática pode coexistir com decepção pelo resultado?',
'Would an equally pleasant activity satisfy the particular wish to repair the book?|Uma atividade igualmente agradável satisfaria o desejo específico de reparar o livro?',
'What could you ask before assigning a quiet person a role?|O que perguntaria antes de atribuir um papel a uma pessoa quieta?'],
'according-to-luke':[
'Who is speaking in each claim: the narrative, its interpreter or the reader?|Quem fala em cada afirmação: a narrativa, seu intérprete ou o leitor?',
'What did you observe about your friend, and what did you merely imagine?|O que observou na amiga e o que apenas imaginou?',
'What does the second volunteer learn that the first has not asked?|O que a segunda voluntária aprende e a primeira não perguntou?',
'What fact would change the response to the accusation?|Que fato mudaria a resposta à acusação?',
'What belongs in each narrative before you add a theory connecting them?|O que pertence a cada narrativa antes de acrescentar uma teoria que as ligue?',
'Does contributing to a result mean being the same person?|Contribuir para um resultado significa ser a mesma pessoa?',
'Which information about a person is relevant to the responsibility being assigned?|Que informação sobre alguém é pertinente à responsabilidade atribuída?',
'What disappears when different figures in an account receive one generic name?|O que desaparece quando figuras diferentes recebem um único nome genérico?',
'What question would locate a difficulty better than a demand for stronger belief?|Que pergunta localizaria uma dificuldade melhor que exigir crença mais forte?',
'What remains unknown when you see someone sharing notes?|O que permanece desconhecido ao ver alguém compartilhando anotações?',
'Can hope for improvement coexist with a boundary and a request for repair?|Esperança de melhora pode coexistir com limite e pedido de reparação?',
'What would make the welcome proposal concrete and open to review?|O que tornaria a proposta de acolhimento concreta e revisável?'],
colour:[
'Which part of your description concerns the arrangement and which your response?|Que parte da descrição trata da composição e qual trata da sua resposta?',
'What changes when the centre changes but the green ground stays the same?|O que muda ao trocar o centro e manter o fundo verde?',
'Where does your attention go when the strongest colour moves from centre to edge?|Para onde vai sua atenção quando a cor mais intensa passa do centro à borda?',
'Which decision was planned, and which appeared during the colour process?|Que decisão foi planejada e qual surgiu durante o processo de cor?',
'Does exchanging the colours change your attention although the shapes stay still?|Trocar as cores muda sua atenção mesmo com as formas imóveis?',
'How might a neighbouring colour change the feeling of the same blue?|Como uma cor vizinha poderia mudar a sensação do mesmo azul?',
'What is already formed in the sketch, and what is only an intended next step?|O que já está formado no esboço e o que é apenas intenção do próximo passo?',
'How do a physical description and a reason for painting answer different questions?|Como descrição física e razão para pintar respondem a perguntas diferentes?',
'What conditions must you describe before explaining what you see?|Que condições precisa descrever antes de explicar o que vê?',
'What would help separate a depth impression from a physical change of position?|O que ajudaria a separar impressão de profundidade de mudança física de posição?',
'What could the middle region do to connect the upper and lower regions?|O que a região central poderia fazer para ligar as regiões superior e inferior?',
'Why might a small dark area draw attention away from a large pale one?|Por que uma área escura pequena pode atrair mais atenção que uma área clara grande?',
'How does a sequence of spiritual relations differ from a material recipe?|Como uma sequência de relações espirituais difere de uma receita material?',
'Which revision can you describe precisely, and what did it change in your response?|Que revisão consegue descrever com precisão e o que mudou na sua resposta?'],
temperaments:[
'What do the two situations reveal that a single label would miss?|O que as duas situações revelam e um rótulo único perderia?',
'What does the sibling contrast make you ask before choosing an explanation?|O que o contraste entre irmãos leva a perguntar antes de escolher uma explicação?',
'Does predominance mean that the other members are absent?|Predominância significa ausência dos outros membros?',
'How could the bridge problem direct effort without becoming a power struggle?|Como o problema da ponte pode orientar esforço sem virar disputa de poder?',
'Where is interest already present, and what would be a reachable ending?|Onde o interesse já existe e qual seria uma conclusão alcançável?',
'What would make the seed-planting invitation a real choice?|O que tornaria o convite para plantar uma escolha real?',
'How can an act of care acknowledge rather than cancel disappointment?|Como um gesto de cuidado pode reconhecer a decepção em vez de apagá-la?',
'Which new detail would make you revise your first label?|Que detalhe novo faria revisar o primeiro rótulo?',
'Which support fits the stated need, and how would you check the response?|Que apoio corresponde à necessidade relatada e como verificaria a resposta?',
'What could you change in the task instead of repeating an order to yourself?|O que poderia mudar na tarefa em vez de repetir uma ordem a si mesmo?',
'What has become more precise in your description of the fictional person?|O que ficou mais preciso na descrição da pessoa fictícia?'],
'understand-temperament':[
'What can you ask about a pattern without turning it into a rule about everyone?|O que pode perguntar sobre um padrão sem torná-lo regra para todos?',
'What differs between the two uses of quickness?|O que difere entre os dois usos da rapidez?',
'Does quietness tell you how someone generates or evaluates ideas?|Ser quieto revela como alguém gera ou avalia ideias?',
'How can you appreciate useful work and still identify a defect?|Como apreciar trabalho útil e ainda identificar um defeito?',
'What would turn enthusiasm into a clear, revisable commitment?|O que transformaria entusiasmo num compromisso claro e revisável?',
'What changes when preparation time and written responses become possible?|O que muda quando preparação e resposta escrita se tornam possíveis?',
'Which question would help you understand the concern without dismissing it?|Que pergunta ajudaria a compreender a preocupação sem descartá-la?',
'What information do you need to match a person and a task responsibly?|De que informação precisa para relacionar pessoa e tarefa de modo responsável?',
'What agreement could address the actual difference without predicting incompatibility?|Que acordo trataria da diferença real sem prever incompatibilidade?',
'Which claim does an attentive act illustrate, and which does it not establish?|Que afirmação um ato atento ilustra e qual não estabelece?',
'Which alternative explanations fit the same outward observation?|Que explicações alternativas correspondem à mesma observação exterior?',
'Why must two different classifications have the same number of categories?|Por que duas classificações diferentes precisariam ter o mesmo número de categorias?',
'How would a clearer agreement change the disagreement you began with?|Como um acordo mais claro mudaria o desacordo inicial?'],
'encountering-the-self':[
'What could the request for privacy mean besides rejection?|O que o pedido de privacidade poderia significar além de rejeição?',
'What could the adult acknowledge before proposing a shared project?|O que o adulto poderia reconhecer antes de propor um projeto conjunto?',
'Can wanting privacy and wanting company belong to the same child?|Desejar privacidade e companhia pode fazer parte da mesma criança?',
'What would you say first after a child uses someone else’s materials?|O que diria primeiro quando uma criança usa materiais de outra pessoa?',
'Which childhood possibilities does the neat biography leave out?|Que possibilidades da infância a biografia bem organizada deixa de fora?',
'What do you need to learn about this child beyond their school year?|O que precisa saber sobre esta criança além do ano escolar?',
'What differs between finding a form by doing and working from a plan?|O que distingue descobrir a forma fazendo de trabalhar com um plano?',
'What does the house metaphor illuminate without becoming a bodily measurement?|O que a metáfora da casa esclarece sem virar medida corporal?',
'How could a practical building task open a question about belonging?|Como construir algo pode abrir uma pergunta sobre pertencimento?',
'Which part of the difficulty can the learning arrangement help you investigate?|Que parte da dificuldade a organização da aprendizagem ajuda a investigar?',
'What would you ask to understand why the child raised the question?|O que perguntaria para compreender por que a criança fez a pergunta?',
'What does the chapter report, and what cannot be decided by its narrative?|O que o capítulo relata e o que sua narrativa não permite decidir?',
'Which supports could a fictional character identify or ask for?|Que apoios uma personagem fictícia poderia identificar ou pedir?',
'Does a matching interval establish a causal connection?|Um intervalo coincidente estabelece ligação causal?',
'What can the prose explain, and what still depends on the damaged figure?|O que a prosa explica e o que ainda depende da figura danificada?',
'Where would three reflected points lie before you draw the whole curve?|Onde ficariam três pontos refletidos antes de desenhar a curva inteira?',
'What does the child’s next request change in your first interpretation?|O que o próximo pedido da criança muda na interpretação inicial?']
};
export function guidedPrompt(course,id,lang){const row=rows[course]?.[id];if(!row)throw Error(`Missing guided prompt ${course}/${id}`);return row.split('|')[lang==='pt'?1:0];}
export const guidedCounts=Object.fromEntries(Object.entries(rows).map(([k,v])=>[k,v.length]));
