// One original opening question per lesson, with a matching Brazilian Portuguese prompt.
// The existing reading, examples, activities and annotated answers remain the substantive source teaching.
const rows={
theosophy:[
'What do you notice, feel and consider before deciding how to help?|O que você percebe, sente e considera antes de decidir como ajudar?',
'Two people see the same stars. What can differ, and what can they understand together?|Duas pessoas veem as mesmas estrelas. O que pode diferir e o que podem compreender juntas?',
'Is the heard tone the same thing as the annoyance it awakens?|O som ouvido é a mesma coisa que o incômodo que desperta?',
'What difference between a stone and a growing plant needs explanation?|Que diferença entre uma pedra e uma planta em crescimento precisa de explicação?',
'What changes between feeling hurt by a correction and examining whether it is right?|O que muda entre sentir-se magoado com uma correção e examinar se ela está certa?',
'When two people say “I,” do they refer to the same person?|Quando duas pessoas dizem “eu”, referem-se à mesma pessoa?',
'How could nine distinctions become seven groups without losing a label?|Como nove distinções podem formar sete grupos sem perder um nome?',
'Can you keep a skill while forgetting the occasions on which you learned it?|É possível conservar uma habilidade e esquecer as ocasiões em que a aprendeu?',
'What does quick learning show, and what does it leave unexplained?|O que a aprendizagem rápida mostra e o que deixa sem explicação?',
'Does a break in awareness erase a responsibility? Where does this analogy stop?|Uma interrupção da consciência apaga uma responsabilidade? Onde termina essa analogia?',
'How would you draw connection and separation without treating them as places?|Como desenharia ligação e separação sem tratá-las como lugares?',
'What persists when the mug is no longer in its usual place?|O que permanece quando a caneca já não está no lugar habitual?',
'What does a building plan explain, and what is missing from that comparison?|O que uma planta de edifício explica e o que falta nessa comparação?',
'Must a more capable carpenter repeat the first object exactly?|Uma pessoa mais hábil em carpintaria precisa repetir exatamente o primeiro objeto?',
'Can a person develop a capacity without gaining income or status?|Alguém pode desenvolver uma capacidade sem aumentar renda ou posição social?',
'Which relationship does the ice-and-water comparison help you think about?|Que relação a comparação entre gelo e água ajuda a pensar?',
'Does observing a shared festival identify what spiritually underlies it?|Observar uma festa compartilhada identifica o que a fundamentaria espiritualmente?',
'When someone calls a voice warm, what does the word carry across?|Quando alguém chama uma voz de calorosa, o que a palavra transporta entre experiências?',
'Can you explain an argument accurately and still question it?|Você pode explicar um argumento com precisão e ainda questioná-lo?',
'Does feeling irritated decide whether a corrected date is accurate?|Sentir irritação decide se uma data corrigida está certa?',
'Which starting information determines the departure time? What could change it?|Que informação inicial determina o horário de saída? O que poderia mudá-lo?',
'What else must you ask besides which option a person chose?|O que mais precisa perguntar além da opção escolhida?',
'What makes an explanation of relationships stronger than a list of terms?|O que torna explicar relações mais completo que listar termos?'],
'higher-worlds':[
'How does Steiner connect a capacity for knowledge with preparation and character?|Como Steiner relaciona a capacidade de conhecer com preparação e caráter?',
'Why does Steiner ask us to turn impressions into inner understanding and useful action?|Por que Steiner pede que transformemos impressões em compreensão interior e ação útil?',
'What distinguishes calm review of past events from meditation beyond personal circumstances?|O que distingue a revisão tranquila de acontecimentos passados da meditação além das circunstâncias pessoais?',
'Why does Steiner join keen observation with feeling, selfless listening and study?|Por que Steiner relaciona observação atenta, sentimento, escuta desinteressada e estudo?',
'How do the seed and grown-plant contemplations approach what is not presently visible?|Como as contemplações da semente e da planta desenvolvida abordam o que ainda não está visível?',
'Why does Steiner put moral development before spiritual insight into another person?|Por que Steiner coloca o desenvolvimento moral antes do conhecimento espiritual de outra pessoa?',
'How do the three trials differ in their guidance and the capacities they develop?|Em que diferem as três provas quanto à orientação e às capacidades que desenvolvem?',
'How does Steiner join patient inner development with active work and considerate replies?|Como Steiner relaciona o desenvolvimento interior paciente com trabalho ativo e respostas ponderadas?',
'What responsibility does each of the first three conditions ask the learner to assume?|Que responsabilidade cada uma das três primeiras condições pede ao aprendiz que assuma?',
'How can a resolution remain steadfast while being corrected when an error is found?|Como uma resolução pode manter sua firmeza e ser corrigida quando se descobre um erro?',
'How do the eight functions and six attributes relate to different spiritual organs in this account?|Como as oito funções e os seis atributos se relacionam com diferentes órgãos espirituais nesta concepção?',
'Why does Steiner connect regulating spiritual organs with moral habits and self-knowledge?|Por que Steiner relaciona a regulação dos órgãos espirituais com hábitos morais e autoconhecimento?',
'How does the chapter connect transformed dreams with waking perception and a spiritual point of reference?|Como o capítulo relaciona sonhos transformados com percepção na vigília e um ponto de referência espiritual?',
'What must change before isolated sleep experiences count as knowledge in this account?|O que precisa mudar para que experiências isoladas durante o sono sejam consideradas conhecimento nesta concepção?',
'Why does the claimed separation of thinking, feeling and willing require conscious coordination?|Por que a separação proposta entre pensar, sentir e querer exige coordenação consciente?',
'In this account, how does the lesser Guardian turn karmic history into a task of personal responsibility?|Nesta concepção, como o Guardião menor transforma a história cármica em uma tarefa de responsabilidade pessoal?',
'Why does the greater Guardian direct powers gained in earthly life toward collaboration with others?|Por que o Guardião maior orienta as capacidades adquiridas na vida terrena para a colaboração com os outros?',
'Why does the appendix distinguish pure thinking from perceiving other supersensible beings?|Por que o apêndice distingue o pensar puro da percepção de outros seres suprassensíveis?',
'What connections between preparation, self-direction and service can you support with passages from both books?|Que relações entre preparação, direção consciente de si e serviço você pode fundamentar com trechos dos dois livros?'],
'philosophy-of-freedom':[
"How does asking what you know differ from asking what leads you to act?|Em que perguntar o que você conhece difere de perguntar o que leva você a agir?",
"Does knowing that you want an action explain what determines your wanting?|Saber que você quer agir explica o que determina esse querer?",
"What connects the search for an explanation with the experienced separation between self and world?|O que relaciona a busca de uma explicação com a separação vivenciada entre eu e mundo?",
"What is observed in an event, and what connection does thinking contribute?|O que é observado em um acontecimento e que ligação o pensar acrescenta?",
"Calculate ((3 × 3) + 1) ÷ 2, then distinguish the result from the activity that produced it.|Calcule ((3 × 3) + 1) ÷ 2 e distinga o resultado da atividade que o produziu.",
"How do percept, concept and mental picture differ in one encounter?|Como percepto, conceito e representação diferem em um mesmo encontro?",
"Why does dependence on sense organs not by itself prove that only mental pictures can be known?|Por que depender dos órgãos dos sentidos, por si só, não demonstra que apenas representações podem ser conhecidas?",
"What does the fitting concept contribute beyond a perceived appearance?|O que o conceito adequado acrescenta à aparência percebida?",
"How can two people understand the same conceptual relation while having different experiences?|Como duas pessoas podem compreender a mesma relação conceitual e ter experiências diferentes?",
"How does a mental picture retain a relation to a particular encounter?|Como uma representação conserva a relação com um encontro particular?",
"How does an unanswered question differ from an alleged limit to knowledge in principle?|Em que uma pergunta ainda sem resposta difere de um suposto limite do conhecimento por princípio?",
"What different roles do thinking, feeling and willing play within one experience?|Que papéis diferentes pensar, sentir e querer desempenham em uma mesma experiência?",
"How would you separate an action’s motive, its driving forces and its practical conditions?|Como distinguiria o motivo de uma ação, suas forças motrizes e suas condições práticas?",
"How can understanding another person’s aim inform your own response without requiring immediate agreement?|Como compreender a finalidade de outra pessoa pode orientar sua resposta sem exigir concordância imediata?",
"What changes when a person understands a rule and makes its ethical content their own?|O que muda quando alguém compreende uma regra e torna próprio seu conteúdo ético?",
"How can an idea of a future result guide an action occurring now?|Como a ideia de um resultado futuro pode orientar uma ação que ocorre agora?",
"What ethical reason, concrete response and practical means would make participation possible?|Que razão ética, resposta concreta e meios práticos possibilitariam a participação?",
"How does imagining a suitable deed differ from knowing how to realize it?|Em que imaginar uma ação adequada difere de saber realizá-la?",
"Why might fulfilling a particular aim matter beyond choosing the most pleasant alternative?|Por que realizar uma finalidade particular pode importar além de escolher a alternativa mais agradável?",
"How does valuing a particular aim differ from adding pleasant and unpleasant feelings?|Em que avaliar uma finalidade particular difere de somar sentimentos agradáveis e desagradáveis?",
"What must you learn about a person beyond the groups to which they belong?|O que precisa conhecer de uma pessoa além dos grupos aos quais ela pertence?",
"How does the argument about knowing support the account of free action, and what remains unproved by a good outcome?|Como o argumento sobre o conhecer sustenta a descrição da ação livre e o que um bom resultado deixa sem demonstrar?"],
'according-to-luke':[
'How does McDermott combine an open judgment with his positive case for spiritual knowledge?|Como McDermott combina o julgamento aberto com sua defesa do conhecimento espiritual?',
'How do the three levels of cognition explain Steiner’s distinction between a clairvoyant and an initiate?|Como os três níveis de conhecimento explicam a distinção de Steiner entre clarividente e iniciado?',
'What does the passage say about the earlier teacher, and how does teaching differ from exercising a capacity?|O que o trecho afirma sobre o mestre anterior e como ensinar difere de exercer uma capacidade?',
'What fact would change the response to the accusation?|Que fato mudaria a resposta à acusação?',
'What belongs in each narrative before you add a theory connecting them?|O que pertence a cada narrativa antes de acrescentar uma teoria que as ligue?',
'Does contributing to a result mean being the same person?|Contribuir para um resultado significa ser a mesma pessoa?',
'Which information about a person is relevant to the responsibility being assigned?|Que informação sobre alguém é pertinente à responsabilidade atribuída?',
'What disappears when different figures in an account receive one generic name?|O que desaparece quando figuras diferentes recebem um único nome genérico?',
'What question would locate a difficulty better than a demand for stronger belief?|Que pergunta localizaria uma dificuldade melhor que exigir crença mais forte?',
'What remains unknown when you see someone sharing notes?|O que permanece desconhecido ao ver alguém compartilhando anotações?',
'Can hope for improvement coexist with a boundary and a request for repair?|Esperança de melhora pode coexistir com limite e pedido de reparação?',
'Which source references show how the argument connects, and which pages remain unread?|Quais referências mostram as ligações do argumento e quais páginas ainda não foram lidas?'],
colour:[
'Why should this collection not be read as twelve successive lectures from one original course?|Por que a coletânea não deve ser lida como doze palestras sucessivas de um único curso original?',
'Why does Steiner call green an image of life rather than life itself?|Por que Steiner chama o verde de imagem da vida, em vez de vida em si?',
'How are the imagined origins of green and peach-blossom different?|Como diferem as origens imaginadas do verde e da cor de flor de pessegueiro?',
'What is Steiner’s proposed difference between plant green and mineral colour becoming fixed?|Qual é a diferença proposta por Steiner entre a fixação do verde vegetal e da cor mineral?',
'Why does Steiner contrast Carstens with Raphael and Dante?|Por que Steiner contrapõe Carstens a Rafael e Dante?',
'What distinguishes red from orange in Steiner’s sequence?|O que distingue vermelho e laranja na sequência de Steiner?',
'What does Steiner qualify when he says thought becomes luminous?|Que ressalva Steiner faz ao dizer que o pensamento se torna luminoso?',
'How do gratitude and responsibility follow from the proposed bridge?|Como gratidão e responsabilidade decorrem da ponte proposta?',
'Which two arrangements does Steiner call the fundamental laws of colour?|Quais são as duas disposições chamadas por Steiner de leis fundamentais da cor?',
'Why does Steiner distinguish painting from architecture, dress and sculpture?|Por que Steiner distingue a pintura da arquitetura, do vestuário e da escultura?',
'What makes an ugly subject capable of artistic beauty in this lecture?|O que permite que um motivo feio tenha beleza artística nesta palestra?',
'How do qualitative measure and number differ from their earthly counterparts?|Como a medida e o número qualitativos diferem de seus correspondentes terrestres?',
'What is the order of hierarchies, manifestations and cosmic stages?|Qual é a ordem das hierarquias, manifestações e etapas cósmicas?',
'What separates image and lustre, and which colours belong to each?|O que distingue imagem e brilho, e quais cores pertencem a cada grupo?'
],
temperaments:[
"How does the lecture connect a general temperament with understanding a particular person?|Como a palestra relaciona um temperamento geral à compreensão de uma pessoa particular?",
"Why does Steiner need temperament to mediate the two streams?|Por que Steiner precisa que o temperamento medeie as duas correntes?",
"What is lost if the four temperament pairings become four separate kinds of human being?|O que se perde quando as quatro relações de temperamento se tornam quatro espécies separadas de ser humano?",
"Why does the choleric educational proposal need both a competent educator and resistance in the task?|Por que a proposta educativa colérica precisa tanto de um educador competente quanto de resistência na tarefa?",
"How do the personal relationship and the interesting objects serve Steiner’s indirect route to attention?|Como a relação pessoal e os objetos interessantes servem ao caminho indireto de Steiner para a atenção?",
"Why can companions’ interests work differently from simply placing an interesting object before the phlegmatic child?|Por que os interesses dos companheiros podem atuar de modo diferente de simplesmente colocar um objeto interessante diante da criança fleumática?",
"What connects the educator’s life experience with the proposed redirection of the child’s pain?|O que liga a experiência de vida de quem educa ao redirecionamento proposto para a dor da criança?",
"Does the mixed-type qualification mean that Steiner abandons his outward and spiritual explanations?|A ressalva sobre combinações significa que Steiner abandona suas explicações exteriores e espirituais?",
"What stays the same across the four routes, and what changes?|O que permanece igual nas quatro vias e o que muda?",
"How does the indirect role of reason differ from a command to change one’s temperament?|Como o papel indireto da razão difere de uma ordem para mudar o próprio temperamento?",
"Why does the full closing passage change how the fourfold map should be used?|Por que a passagem final completa modifica o uso do quadro quádruplo?"
],
'understand-temperament':[
"How can a companion preserve Childs’s argument while keeping its own practical exercises clear?|Como um guia pode preservar o argumento de Childs e manter claros seus próprios exercícios práticos?",
"What distinguishes the resources of temperament from the person’s use of them in Childs’s first chapter?|O que distingue os recursos do temperamento do uso que a pessoa faz deles no primeiro capítulo de Childs?",
"Why can a sanguine pattern be stable in Childs’s classification while showing little persistence?|Por que um padrão sanguíneo pode ser estável na classificação de Childs e mostrar pouca persistência?",
"How does the course’s feedback agreement relate to Childs’s handling prescription?|Como o acordo de revisão do curso se relaciona à prescrição de trato de Childs?",
"Why does the chapter connect interrupted projects and social influence, yet recommend firm kindness rather than domination?|Por que o capítulo relaciona projetos interrompidos e influência social, mas recomenda gentileza firme em vez de dominação?",
"How does the need for preparation explain both the chapter’s valued carefulness and its warning against pressure?|Como a necessidade de preparação explica tanto o cuidado valorizado no capítulo quanto sua advertência contra a pressão?",
"How can the chapter’s proposed turn toward compassion be understood without accepting its judgments about illness or using its tactic?|Como compreender o movimento para a compaixão proposto no capítulo sem aceitar seus juízos sobre doença nem usar sua tática?",
"How can Childs claim temperament is lasting while also recommending development and practical trials?|Como Childs pode afirmar que o temperamento é duradouro e também recomendar desenvolvimento e experiências práticas?",
"What does it mean to read the ten source pairings under the caricature qualification rather than replace them with the course questions?|O que significa ler os dez pares da fonte sob a ressalva de caricatura, em vez de substituí-los pelas perguntas do curso?",
"What premises and intermediate steps lead Childs to practical love in this chapter?|Que premissas e passos intermediários conduzem Childs ao amor prático neste capítulo?",
"What constructive practice does Appendix I propose, and which unresolved tension accompanies it?|Que prática construtiva propõe o apêndice I e qual tensão não resolvida a acompanha?",
"How does Childs reach four types, and what remains an explanatory hypothesis?|Como Childs chega a quatro tipos e o que permanece como hipótese explicativa?",
"What should the final case demonstrate about understanding this book?|O que o caso final deve demonstrar sobre a compreensão deste livro?"
],
'encountering-the-self':[
 "Which opening detail makes a developmental interpretation more accountable?|Que detalhe da abertura torna a interpretação do desenvolvimento mais responsável?",
 "What makes the house-building ending more than a simple remedy for criticism?|Por que a construção da casa ultrapassa uma solução simples para a crítica?",
 "Which part of the mother's final response depends on the dialogue's Christian interpretation?|Que parte da resposta final da mãe depende da interpretação cristã do diálogo?",
 "How can the course preserve the repair process without attributing its adapted family arrangement to Koepke?|Como o curso pode preservar o processo de reparação sem atribuir a Koepke sua configuração familiar adaptada?",
 "Why do Walter’s age and Steiner’s later formulation matter when reading the seven biographies?|Por que a idade de Walter e a formulação posterior de Steiner importam na leitura das sete biografias?",
 "Why must an explanation of Diagram 1 include both its shading and its arrows?|Por que uma explicação do Diagrama 1 deve incluir o sombreado e as setas?",
 "How can the color sequence clarify the difference between observation and an explanation?|Como a sequência de cor esclarece a diferença entre observar e explicar?",
 "Why must an explanation of the crossed diagram include both its spiritual limit and its bodily claims?|Por que explicar o diagrama cruzado exige incluir tanto seu limite espiritual quanto suas afirmações corporais?",
 "How could one curriculum example be revisited without replacing Koepke’s account with a generic activity?|Como retomar um exemplo curricular sem substituir a explicação de Koepke por uma atividade genérica?",
 "What would be lost if the Snow White comparison were taught only as a reminder to reduce stress?|O que se perderia se a comparação com Branca de Neve fosse ensinada apenas como lembrete para reduzir o estresse?",
 "What changes in the reading when the Christophorus ending is included?|O que muda na leitura quando o final de Christophorus é incluído?",
 "Why is neither “only external stress” nor “only uncertainty” an adequate account of Holtzapfel’s contribution?|Por que nem “apenas pressão externa” nem “apenas incerteza” resume adequadamente a contribuição de Holtzapfel?",
 "What does the rooted tree’s new understanding add beyond its physical stability?|O que a nova compreensão da árvore acrescenta à sua estabilidade física?",
 "Which part of the appendix goes beyond the orbital diagram?|Que parte do apêndice vai além do diagrama orbital?",
 "Why is the third-grade figure essential to the appendix’s progression?|Por que a figura do terceiro ano é essencial à progressão do apêndice?",
 "How can one lesson study the drawings faithfully without claiming to verify every effect assigned to them?|Como estudar fielmente os desenhos sem afirmar que todos os efeitos atribuídos foram verificados?",
 "What changes when the final plan treats a source scene as constructed rather than as a verified case?|O que muda quando o plano final trata a cena como construída, e não como caso verificado?"
]
};
export function guidedPrompt(course,id,lang){const row=rows[course]?.[id];if(!row)throw Error(`Missing guided prompt ${course}/${id}`);return row.split('|')[lang==='pt'?1:0];}
export const guidedCounts=Object.fromEntries(Object.entries(rows).map(([k,v])=>[k,v.length]));
