// Original bilingual orientation. Source markers refer to the supplied 2002
// Bamford/Spiegler transcription, not the printed pagination of GA 9.
export const introduction = {
 id: 0, chapter: 0, pages: '15–16, 22–24, 30–32, 46–49, 151–152, 160–162', notes: '',
 en: ['Why study anthroposophy?', 'Understand the purpose of this study and see how the course fits together.', [
  'Anthroposophy is Rudolf Steiner’s path of spiritual knowledge, beginning with the question of what it means to be human. He proposes that capacities within us can develop toward knowledge of a spiritual reality. His aim connects understanding ourselves with understanding the world and acting within it. This course helps you follow that proposal, examine it, and form your own questions.',
  'Self-knowledge here means more than describing your personality. It involves attending to how you perceive, feel, think, remember, and act. These familiar activities provide starting questions: How does an experience become part of me? What guides a choice? Can I understand something beyond my immediate likes and dislikes? Steiner takes these questions toward an account of soul and spirit.',
  'Bamford presents a comparison from Steiner that helps explain this starting point. Imagine exploring a landscape at ground level, seeing it from a hilltop, and looking from the hillside where details and the wider view can meet. The comparison places anthroposophy on the hillside: it begins with observable human life and seeks indications of its spiritual foundation. “Anthropology” and “theosophy” name the other perspectives in this particular comparison, not a ranking of people or a complete description of those fields today. The image explains an intended approach; it does not prove the spiritual foundation.',
  'In his later lectures collected as What Is Anthroposophy?, Steiner connects spiritual life with freedom, memory, and love. Freedom concerns conscious activity rather than simply following an impulse. Memory connects past experience with present inner life. Love opens us toward another being and the world. These are themes to explore throughout the course; you do not need to master their spiritual explanation before beginning.',
  'Our main book is Theosophy (GA 9). It gives us an organized sequence: the human being; individuality and destiny; the soul and spiritual worlds; and a path of knowledge. We will work through it in short readings. The later lectures help us revisit the meaning of those ideas, while Theosophy supplies the foundation.',
  'Keep three uses of the name distinct. Theosophy is the title of Steiner’s book in this course. Theosophy can also mean divine wisdom more broadly. The Theosophical Society is the historical organization in which Steiner worked before the separate Anthroposophical movement. Studying this particular book is not the same as studying every teaching associated with that organization.',
  'Steiner calls his approach spiritual science because he intends a disciplined way of knowing, not simply accepting a belief. That is how he presents his method; the name does not by itself establish the truth of its results. We will distinguish an ordinary observation, an argument, and a report of spiritual perception as we meet them. Understanding a proposal and agreeing with it are different steps.',
  'Allow about 20–30 minutes for this opening, including reflection. Begin with an experience you can describe, then follow the author’s explanation before evaluating it. Keep one question in your notebook and return to it as the course develops. You can begin without prior spiritual experience or specialist vocabulary.'
 ], 'Return to the example of helping someone at the beginning. Write what you notice, what you feel, and what reasons might guide your response. Then choose one question about human life you want this course to help you explore. Use the course map to identify where you might revisit it.', 'In your own words: What does anthroposophy seek? Why does this course begin with Theosophy? Does noticing a thoughtful choice establish the whole spiritual account?', 'Steiner’s anthroposophy seeks a path from human self-knowledge toward knowledge of spiritual reality. Theosophy supplies an organized foundation for studying that account. A thoughtful choice gives us an everyday starting point for questions about freedom and action; it does not establish all of Steiner’s explanations. If you can explain these distinctions and name one question of your own, continue to Lesson 1. Otherwise reread the opening and the course map.'],
 pt: ['Por que estudar antroposofia?', 'Compreender o propósito deste estudo e como as partes do curso se relacionam.', [
  'Antroposofia é o caminho de conhecimento espiritual de Rudolf Steiner, que começa pela pergunta sobre o que significa ser humano. Ele propõe que capacidades presentes em nós podem se desenvolver em direção ao conhecimento de uma realidade espiritual. Seu propósito liga a compreensão de nós mesmos à compreensão do mundo e à nossa atuação nele. Este curso ajuda você a acompanhar essa proposta, examiná-la e formular suas próprias perguntas.',
  'Autoconhecimento, aqui, significa mais do que descrever a própria personalidade. Envolve prestar atenção a como percebemos, sentimos, pensamos, lembramos e agimos. Essas atividades familiares oferecem perguntas iniciais: Como uma experiência passa a fazer parte de mim? O que orienta uma escolha? Posso compreender algo além daquilo de que gosto ou não gosto imediatamente? Steiner conduz essas perguntas a uma concepção de alma e espírito.',
  'Bamford apresenta uma comparação de Steiner que ajuda a explicar esse ponto de partida. Imagine explorar uma paisagem ao nível do chão, vê-la do alto de uma colina e observá-la da encosta, onde os detalhes e a visão mais ampla podem se encontrar. A comparação situa a antroposofia na encosta: ela começa pela vida humana observável e busca indícios de seu fundamento espiritual. “Antropologia” e “teosofia” nomeiam as outras perspectivas nessa comparação específica, não uma classificação de pessoas nem uma descrição completa dessas áreas hoje. A imagem explica uma abordagem pretendida; não comprova o fundamento espiritual.',
  'Nas palestras posteriores reunidas em What Is Anthroposophy?, Steiner relaciona a vida espiritual à liberdade, à memória e ao amor. Liberdade envolve atividade consciente, além de simplesmente seguir um impulso. A memória liga a experiência passada à vida interior presente. O amor nos abre para outro ser e para o mundo. São temas para explorar ao longo do curso; você não precisa dominar sua explicação espiritual antes de começar.',
  'Nosso livro principal é Teosofia (GA 9). Ele oferece uma sequência organizada: o ser humano; individualidade e destino; os mundos anímico e espiritual; e um caminho de conhecimento. Vamos percorrê-lo em leituras curtas. As palestras posteriores ajudam a retomar o significado dessas ideias, enquanto Teosofia fornece a base.',
  'Distinga três usos do nome. Teosofia é o título do livro de Steiner estudado neste curso. Teosofia também pode significar sabedoria divina num sentido mais amplo. A Sociedade Teosófica é a organização histórica na qual Steiner atuou antes do movimento antroposófico separado. Estudar este livro específico não equivale a estudar todos os ensinamentos associados àquela organização.',
  'Steiner chama sua abordagem de ciência espiritual porque pretende apresentar um modo disciplinado de conhecer, além da simples aceitação de uma crença. É assim que ele apresenta seu método; o nome, sozinho, não estabelece a verdade dos resultados. Vamos distinguir uma observação comum, um argumento e um relato de percepção espiritual à medida que aparecerem. Compreender uma proposta e concordar com ela são passos diferentes.',
  'Reserve cerca de 20–30 minutos para esta abertura, incluindo a reflexão. Comece por uma experiência que possa descrever e acompanhe a explicação do autor antes de avaliá-la. Guarde uma pergunta no caderno e retome-a ao longo do curso. Você pode começar sem experiência espiritual prévia ou vocabulário especializado.'
 ], 'Use o exemplo de ajudar alguém apresentado nesta lição. Escreva o que você percebe, o que sente e quais razões poderiam orientar sua resposta. Depois escolha uma pergunta sobre a vida humana que deseja explorar com o curso. Use o mapa do curso para identificar onde poderia retomá-la.', 'Com suas palavras: O que a antroposofia busca? Por que este curso começa com Teosofia? Perceber uma escolha ponderada estabelece toda a concepção espiritual?', 'A antroposofia de Steiner busca um caminho do autoconhecimento humano ao conhecimento da realidade espiritual. Teosofia fornece uma base organizada para estudar essa concepção. Uma escolha ponderada oferece um ponto de partida cotidiano para perguntas sobre liberdade e ação; não estabelece todas as explicações de Steiner. Se consegue explicar essas distinções e formular uma pergunta própria, avance para a Lição 1. Caso contrário, releia a abertura e o mapa do curso.']
};

export const introductionExample = {
 en: ['A friend asks for help while you are busy. You hear the request, notice impatience, remember how someone once helped you, and consider what you can reasonably offer.', 'One ordinary moment brings together perception, feeling, memory, thought, and action. Steiner asks how these activities relate and what they reveal about the human being. This gives us a question to investigate before learning his terminology.', 'Start with a human question. Learn the concepts as ways of exploring it.'],
 pt: ['Uma amiga pede ajuda enquanto você está ocupado. Você ouve o pedido, percebe impaciência, lembra de quando alguém o ajudou e considera o que pode oferecer de maneira razoável.', 'Um momento comum reúne percepção, sentimento, memória, pensamento e ação. Steiner pergunta como essas atividades se relacionam e o que revelam sobre o ser humano. Isso nos oferece uma pergunta para investigar antes de aprender sua terminologia.', 'Comece com uma pergunta humana. Aprenda os conceitos como formas de explorá-la.']
};

export const courseMap = {
 en: [
  ['What is the human being?', 'Begin with body, soul, and spirit, then learn how Steiner organizes their relationships.', 1, 'Lessons 1–6'],
  ['What carries through a life?', 'Explore memory, individuality, actions, and the proposed relationship between repeated lives and destiny.', 7, 'Lessons 7–9'],
  ['How do human life and the spiritual worlds relate?', 'Study the worlds Steiner describes and the development he proposes between death and rebirth.', 10, 'Lessons 10–17'],
  ['How is spiritual knowledge approached?', 'Examine the roles of thinking, feeling, conduct, and freedom in the path of knowledge.', 18, 'Lessons 18–21'],
  ['How do the ideas fit together?', 'Return to your first question and explain what you now understand, including what remains unresolved.', 22, 'Final synthesis']
 ],
 pt: [
  ['O que é o ser humano?', 'Comece por corpo, alma e espírito; depois aprenda como Steiner organiza suas relações.', 1, 'Lições 1–6'],
  ['O que permanece ao longo de uma vida?', 'Explore memória, individualidade, ações e a relação proposta entre vidas sucessivas e destino.', 7, 'Lições 7–9'],
  ['Como a vida humana e os mundos espirituais se relacionam?', 'Estude os mundos descritos por Steiner e o desenvolvimento que ele propõe entre morte e renascimento.', 10, 'Lições 10–17'],
  ['Como se aproxima do conhecimento espiritual?', 'Examine os papéis do pensamento, do sentimento, da conduta e da liberdade no caminho do conhecimento.', 18, 'Lições 18–21'],
  ['Como as ideias se relacionam?', 'Retome sua primeira pergunta e explique o que compreende agora, incluindo o que permanece em aberto.', 22, 'Síntese final']
 ]
};
