// Original teaching material. Page ranges refer to the visually reviewed 1971 English edition of GA 9.
export const lessons = [];
const add = (id, chapter, pages, notes, en, pt) => lessons.push({id, chapter, pages, notes, en, pt});
// Each language: title, learning goal, explanation paragraphs, exercise, question, suggested answer.
add(1,
1,
"1–5",
"",
[
  "Encountering the world",
  "Explain the flower example through sensory encounter, personal response, and knowledge of enduring relationships.",
  [
    "Steiner begins with Goethe’s distinction between asking how an object affects us and investigating the object in its own relationships. Both concern the same world. Pleasure, usefulness, attraction, and aversion make the world personally significant; inquiry asks what belongs to the thing itself. Begin with this change of standpoint before learning the later names for the human constitution.",
    "The meadow on printed page 3 gives the first teaching example. The eyes disclose colors; the person enjoys their splendor. A year later the original flowers are gone, different flowers produce new joy, and the earlier joy remains as memory. Knowledge of the species and its laws can be recognized again in the new flowers. Separate the passing object, the personally retained experience, and the enduring relationship understood.",
    "On page 4 Steiner names these three relationships body, soul, and spirit. Body makes the environment accessible. Soul joins what is encountered to one’s own being through pleasure and pain, desire and aversion, joy and sorrow. Spirit allows the nature of things to disclose itself beyond personal liking. These are introductory meanings, which the rest of the chapter develops; they describe three aspects of one person’s encounter.",
    "The stars example on page 5 repeats the distinction: delight belongs to the observer’s inner life, while a correctly understood law concerns the stars themselves. A thought is not true simply because it occurs to someone. The intended contrast is between a private response and knowledge with a significance others can examine. Steiner understands such knowing as participation in spirit.",
    "The body is available to bodily observation; another person’s inward joy is not seen in the same way as a flower or a hand. Later Steiner will describe a claimed spiritual perception of soul life. At this opening stage, stay with the difference between encountering, inwardly experiencing, and understanding. The next lesson asks how bodily organization, feeling, willing, and thinking work together."
  ],
  "Reconstruct both visits to the meadow in three columns: what the senses encounter, what belongs to the person’s soul, and what is sought or recognized through knowledge. Include the vanished first flowers, remembered joy, new joy, and a law of growth. Then use a familiar object to give your own example, marking an unanswered question as a question rather than an established law.",
  "Why can the earlier joy remain when the original flowers are gone, while knowledge of the species can apply to the new flowers?",
  "The earlier joy is retained as a personal memory, so it belongs to this person’s soul life. A correctly understood relationship concerns the kind of flower rather than only that individual encounter and can be recognized in later flowers. Sensory encounter, personal memory, and knowledge therefore have different relationships to time and to the observer. Steiner uses this to introduce body, soul, and spirit."
],
[
  "Nosso encontro com o mundo",
  "Explicar o exemplo das flores por meio do encontro sensorial, da resposta pessoal e do conhecimento de relações duradouras.",
  [
    "Steiner começa com a distinção de Goethe entre perguntar como um objeto nos afeta e investigar o objeto em suas próprias relações. As duas atitudes se referem ao mesmo mundo. Prazer, utilidade, atração e aversão dão ao mundo um significado pessoal; a investigação pergunta o que pertence à própria coisa. Comece por essa mudança de perspectiva antes de aprender os nomes posteriores da constituição humana.",
    "O campo florido da página impressa 3 oferece o primeiro exemplo didático. Os olhos revelam as cores; a pessoa se alegra com seu esplendor. Um ano depois, as primeiras flores desapareceram, outras flores produzem nova alegria e a alegria anterior permanece como lembrança. O conhecimento da espécie e de suas leis pode ser reconhecido nas novas flores. Separe o objeto passageiro, a experiência pessoal conservada e a relação duradoura compreendida.",
    "Na página 4, Steiner chama essas três relações de corpo, alma e espírito. O corpo torna o ambiente acessível. A alma liga o que encontramos ao nosso próprio ser por meio de prazer e dor, desejo e aversão, alegria e tristeza. O espírito permite que a natureza das coisas se revele além do gosto pessoal. São significados introdutórios, desenvolvidos no restante do capítulo; descrevem três aspectos do encontro de uma mesma pessoa.",
    "O exemplo das estrelas, na página 5, retoma a distinção: o encantamento pertence à vida interior de quem observa, enquanto uma lei corretamente compreendida diz respeito às próprias estrelas. Um pensamento não é verdadeiro apenas porque ocorre a alguém. O contraste proposto é entre uma resposta privada e um conhecimento cujo significado outras pessoas podem examinar. Steiner entende esse conhecer como participação no espírito.",
    "O corpo está disponível à observação corporal; a alegria interior de outra pessoa não é vista do mesmo modo que uma flor ou uma mão. Mais adiante, Steiner descreverá a percepção espiritual da vida anímica que afirma ser possível. Nesta abertura, acompanhe a diferença entre encontrar, vivenciar interiormente e compreender. A próxima lição pergunta como organização corporal, sentir, querer e pensar atuam juntos."
  ],
  "Reconstrua as duas visitas ao campo em três colunas: o que os sentidos encontram, o que pertence à alma da pessoa e o que se busca ou reconhece pelo conhecimento. Inclua as primeiras flores desaparecidas, a alegria lembrada, a nova alegria e uma lei de crescimento. Depois dê um exemplo com um objeto familiar, identificando uma pergunta sem resposta como pergunta, e não como uma lei já estabelecida.",
  "Por que a alegria anterior pode permanecer depois que as primeiras flores desapareceram, enquanto o conhecimento da espécie pode se aplicar às novas flores?",
  "A alegria anterior permanece como lembrança pessoal e pertence à vida anímica dessa pessoa. Uma relação corretamente compreendida diz respeito ao tipo de flor, e não apenas àquele encontro, e pode ser reconhecida em flores posteriores. Encontro sensorial, lembrança pessoal e conhecimento têm, portanto, relações diferentes com o tempo e com quem observa. Steiner usa isso para introduzir corpo, alma e espírito."
]);
add(2,
1,
"6–11",
"",
[
  "Embodiment and inner experience",
  "Trace the relationships among bodily organization, sensation, feeling, willing, and thinking in Steiner’s account.",
  [
    "The first three subsections develop the opening distinction. Steiner places human embodiment alongside mineral, plant, and animal existence: material composition, growth and reproduction, and perception with inner experience. He then describes specifically human organization in relation to thinking. This prepares the question of how one human being belongs to several orders of existence.",
    "The soul subsection begins with sensation itself. Two people can look at the same red table, yet one does not directly perceive the other’s experience of red. Feeling adds pleasure or displeasure to sensation. Willing brings inner life back into the outer world through action: a person approaches, avoids, builds, or changes something. Soul therefore includes sensing, feeling, and willing; reducing it to emotion loses two movements of the text.",
    "Thinking can examine both perceptions and actions. In knowing, it seeks the relationships of things; in acting, it brings reasonable coherence to life. On page 10 Steiner distinguishes the natural necessity of bodily processes from the laws of thought that the person voluntarily acknowledges. His point is that a desire does not by itself decide what is true or what action is justified.",
    "The body remains the basis through which this occurs. At the next subsection’s opening on page 11, Steiner explicitly calls the brain the bodily instrument of thinking. The course follows this account of embodiment without adopting the chapter’s historical anatomical comparisons or the demeaning disability language in its Carus quotation as standards for human worth or present-day biology.",
    "Use the bell as an original application of the text. Vibration and the hearing organ concern embodiment; hearing the sound, feeling irritated, and wanting to silence it belong to inner experience; examining the pattern or a considerate response introduces reflection. All can occur in one encounter. Steiner’s next step is to distinguish the physical, living, and sentient organizations that he believes make such an encounter possible."
  ],
  "Describe a fictional listener hearing a bell. Label the physical event and organ, the sensation, the feeling, the impulse, and one considered action. Explain how reflection could change the action without pretending the irritation never occurred. Revisit pages 9–10 and state the difference between being subject to a bodily process and acknowledging a reason in thought.",
  "Why does Steiner include willing in soul life and thinking in both knowing and acting?",
  "Willing expresses inner life in an outward deed, so soul life both receives impressions and responds to the world. Thinking examines perceptions to gain knowledge and examines actions to bring coherence and direction. The person can acknowledge reasons instead of simply following each impulse. This connects body, soul, and spirit while preserving their distinct roles."
],
[
  "Corpo e experiência interior",
  "Acompanhar as relações entre organização corporal, sensação, sentir, querer e pensar na concepção de Steiner.",
  [
    "As três primeiras subseções desenvolvem a distinção inicial. Steiner aproxima a existência corporal humana das existências mineral, vegetal e animal: composição material, crescimento e reprodução, percepção e experiência interior. Em seguida, descreve a organização especificamente humana em relação ao pensar. Isso prepara a pergunta sobre como um mesmo ser humano pertence a diferentes ordens de existência.",
    "A subseção sobre a alma começa com a própria sensação. Duas pessoas podem olhar a mesma mesa vermelha, mas uma não percebe diretamente a experiência de vermelho da outra. O sentir acrescenta prazer ou desprazer à sensação. O querer leva a vida interior de volta ao mundo exterior pela ação: uma pessoa se aproxima, evita, constrói ou modifica algo. A alma inclui, portanto, sensação, sentir e querer; reduzi-la à emoção elimina dois movimentos do texto.",
    "O pensar pode examinar percepções e ações. Ao conhecer, procura as relações das coisas; ao agir, introduz uma coerência racional na vida. Na página 10, Steiner distingue a necessidade natural dos processos corporais das leis do pensamento que a pessoa reconhece voluntariamente. Seu argumento é que um desejo, sozinho, não determina o que é verdadeiro ou qual ação se justifica.",
    "O corpo continua sendo a base pela qual isso acontece. Na abertura da subseção seguinte, na página 11, Steiner chama explicitamente o cérebro de instrumento corporal do pensar. O curso acompanha essa concepção de corporeidade sem adotar as comparações anatômicas históricas do capítulo ou a linguagem depreciativa sobre deficiência na citação de Carus como critérios do valor humano ou de biologia atual.",
    "Use o sino como aplicação original do texto. Vibração e órgão auditivo dizem respeito à corporeidade; ouvir o som, sentir irritação e querer silenciá-lo pertencem à experiência interior; examinar o padrão sonoro ou uma resposta cuidadosa introduz a reflexão. Tudo pode ocorrer num mesmo encontro. O próximo passo de Steiner distingue as organizações física, viva e senciente que, segundo ele, tornam esse encontro possível."
  ],
  "Descreva uma pessoa fictícia ouvindo um sino. Identifique acontecimento e órgão físicos, sensação, sentimento, impulso e uma ação refletida. Explique como a reflexão poderia mudar a ação sem fingir que a irritação não ocorreu. Retome as páginas 9–10 e formule a diferença entre estar sujeito a um processo corporal e reconhecer uma razão no pensamento.",
  "Por que Steiner inclui o querer na vida anímica e o pensar tanto no conhecer quanto no agir?",
  "O querer expressa a vida interior num ato externo; por isso, a vida anímica recebe impressões e responde ao mundo. O pensar examina percepções para obter conhecimento e ações para dar coerência e direção. A pessoa pode reconhecer razões em vez de simplesmente seguir cada impulso. Isso relaciona corpo, alma e espírito, preservando suas funções distintas."
]);
add(3,
1,
"11–20",
"1–2",
[
  "Life, sensation, and formative organization",
  "Distinguish physical body, ether or life body, soul body, and sentient soul, explaining how the chapter connects them.",
  [
    "Steiner first defends thinking as a path that can deepen feeling: persevering thought about spiritual questions can awaken warmth, beauty, and enthusiasm. He then names the material organization the physical body. Its substances also occur in the mineral world, while a living being maintains and develops a form through growth and successive generations. The oak and the quartz crystal introduce this difference in organization.",
    "The ether or life body names the supersensible formative organization Steiner attributes to living beings. It gives living form and sustains the physical organization during life. On pages 14–16 he presents it as a real object of spiritual perception, approached through an organ or faculty that must develop. The comparison with sight explains the kind of access he claims; observing growth supplies the starting phenomenon rather than a demonstration of that faculty.",
    "Read the long footnote on pages 14–15 before treating life-force as an extra chemical force. Steiner says inorganic laws act the same way inside an organism as outside it. The formative-force body concerns the living organization in which those processes occur. Ether here is also different from the hypothetical ether of physics. Addendum 1 reinforces his proposed change of mode of knowledge; Addendum 2 qualifies touch as a general awareness of an impression in this context.",
    "Life and sensation are then distinguished. Physical and living processes in an eye and brain do not describe the inward experience of blue in the same terms. The sentient soul is the activity through which such impressions become inner experiences. It also embraces desire, aversion, impulse, instinct, and passion. In Steiner’s scheme plants participate in formative life, while animals and humans also have a world of sensation.",
    "The soul body or sentient body, introduced on page 20, mediates bodily organization and sentient soul. Steiner describes a finer part of the etheric organization as united with the sentient soul and a coarser part as united with the physical body. Distinguish the bodily organization supporting sensation from the soul’s experience; later he will unite soul body and sentient soul under the name astral body.",
    "The sentient soul depends on the living body and the functioning of the senses. Experiencing one’s own sensation is different from perceiving its expression in another being: the seer described on pages 18–19 does not simply feel the other’s feeling from the other’s standpoint. These qualifications explain relationships among the members before the next lesson differentiates soul life itself."
  ],
  "Draw a concept map for Steiner’s stone, plant, animal, and human examples. Label material organization, formative life, and inner sensation. For a person seeing blue, add physical body, ether body, soul body, and sentient soul, with one sentence explaining each connection. Annotate the map with the footnote’s statement that inorganic laws remain unchanged and mark which added organizations are claims of spiritual perception.",
  "How do ether body, soul body, and sentient soul differ in the chapter’s explanation of seeing blue?",
  "The ether body provides formative life in the bodily organization. The soul body is the sentient organization joining that bodily basis to soul life. The sentient soul inwardly experiences the blue and responds through feelings or desires. Life-process, support for sensation, and experienced sensation are distinguishable but connected. Steiner later groups soul body and sentient soul as astral body; this does not make either identical with the ether body."
],
[
  "Vida, sensação e organização formativa",
  "Distinguir corpo físico, corpo etérico ou vital, corpo anímico e alma senciente, explicando como o capítulo os relaciona.",
  [
    "Steiner primeiro defende o pensar como caminho capaz de aprofundar o sentir: o pensamento perseverante sobre questões espirituais pode despertar calor, beleza e entusiasmo. Em seguida, chama a organização material de corpo físico. Suas substâncias também existem no mundo mineral, enquanto um ser vivo conserva e desenvolve uma forma pelo crescimento e pela sucessão das gerações. O carvalho e o cristal de quartzo introduzem essa diferença de organização.",
    "O corpo etérico ou vital designa a organização formativa suprassensível que Steiner atribui aos seres vivos. Ela dá forma viva e sustenta a organização física durante a vida. Nas páginas 14–16, ele a apresenta como objeto real de percepção espiritual, acessível por um órgão ou uma faculdade que precisa se desenvolver. A comparação com a visão explica o acesso que ele afirma existir; observar o crescimento fornece o fenômeno inicial, e não uma demonstração dessa faculdade.",
    "Leia a longa nota das páginas 14–15 antes de tratar a força vital como força química adicional. Steiner afirma que as leis inorgânicas atuam do mesmo modo dentro e fora de um organismo. O corpo de forças formativas diz respeito à organização viva na qual esses processos ocorrem. Éter aqui também difere do éter hipotético da física. O Adendo 1 reforça a mudança de modalidade de conhecimento proposta pelo autor; o Adendo 2 qualifica o tato, neste contexto, como consciência geral de uma impressão.",
    "Em seguida, distinguem-se vida e sensação. Os processos físicos e vitais no olho e no cérebro não descrevem, nos mesmos termos, a experiência interior de azul. A alma senciente é a atividade pela qual essas impressões se tornam experiências interiores. Ela também abrange desejo, aversão, impulso, instinto e paixão. No esquema de Steiner, plantas participam da vida formativa, enquanto animais e seres humanos também têm um mundo de sensações.",
    "O corpo anímico ou senciente, introduzido na página 20, faz a mediação entre organização corporal e alma senciente. Steiner descreve uma parte mais sutil da organização etérica como unida à alma senciente e uma parte mais densa como unida ao corpo físico. Distinga a organização corporal que sustenta a sensação da experiência da alma; mais adiante, ele reunirá corpo anímico e alma senciente sob o nome de corpo astral.",
    "A alma senciente depende do corpo vivo e do funcionamento dos sentidos. Vivenciar a própria sensação difere de perceber sua expressão em outro ser: o vidente descrito nas páginas 18–19 não sente simplesmente o sentimento alheio do ponto de vista daquela pessoa. Essas qualificações explicam as relações entre os membros antes que a próxima lição diferencie a própria vida anímica."
  ],
  "Desenhe um mapa conceitual para os exemplos de pedra, planta, animal e ser humano de Steiner. Identifique organização material, vida formativa e sensação interior. Para uma pessoa vendo azul, acrescente corpo físico, corpo etérico, corpo anímico e alma senciente, com uma frase explicando cada ligação. Anote a afirmação da nota de que as leis inorgânicas permanecem iguais e identifique as organizações adicionais como afirmações de percepção espiritual.",
  "Como corpo etérico, corpo anímico e alma senciente diferem na explicação do capítulo sobre ver azul?",
  "O corpo etérico fornece a vida formativa à organização corporal. O corpo anímico é a organização senciente que liga essa base corporal à vida da alma. A alma senciente vivencia interiormente o azul e responde com sentimentos ou desejos. Processo vital, suporte da sensação e sensação vivenciada são distinguíveis, mas relacionados. Steiner posteriormente reúne corpo anímico e alma senciente como corpo astral; isso não torna nenhum deles idêntico ao corpo etérico."
]);
add(4,
1,
"20–26",
"4",
[
  "Three aspects of soul",
  "Explain how thinking serves desire and how orientation toward truth and goodness differentiates the three soul members.",
  [
    "The sentient soul encounters sensation and the desires, aversions, and impulses connected with it. Thinking first enters this life as a practical helper. The child learns that fire burns; people devise tools, transport, and communication to meet needs. Steiner names the soul served by thought the intellectual or mind soul. Thinking in this role can organize a desire very effectively while the desire still supplies its purpose.",
    "The argument then changes direction. In the starry-heavens example on page 22, delight belongs to the individual, while knowledge of the paths of heavenly bodies has a significance others can share. On page 23 Steiner distinguishes truth from our changing conceptions of it: discovering an error changes what we believe, not truth into something that depended on our enjoyment. He takes this independence as a connection between soul and an enduring spiritual reality.",
    "Moral goodness supplies the parallel on page 24. Inclinations can be educated so that they freely accord with what is recognized as good; goodness does not acquire its value because a desire approves it. Steiner’s ideal is the refinement of inclination rather than its permanent suppression. An ordinary example is recognizing that one should correct a misleading statement even when keeping it would bring an advantage.",
    "The consciousness soul names the part of soul life in which the enduring true and good become alive. This is more specific than being awake or having any sensation: Steiner expressly acknowledges ordinary consciousness in animals. The three members are therefore sentient soul, intellectual soul, and consciousness soul, connected and interpenetrating rather than three sealed mental rooms.",
    "For an original application, compare hearing criticism, planning a reply that wins approval, and examining whether the criticism is justified. The second can be clever yet remain in the service of a wish; the third asks for a valid judgment even if it is unwelcome. These are movements within one person’s experience, not categories for ranking whole people.",
    "The closing pages describe these organizations as the aura perceived by the seer, introducing the later discussion of spiritual perception. Addendum 4 also qualifies the animal contrast on page 21: Steiner does not deny thought in animal life but attributes it to a group-ego rather than an independently thinking human I. Learn that distinction as his account before proceeding to the I itself."
  ],
  "Use a fictional person who receives justified criticism of a written report. Describe the first sensation and reaction, a plan to protect approval, and an examination of what is true and what correction would be good. Explain which role thinking plays in the last two. Then write one sentence distinguishing an error in a person’s conception from the chapter’s claim about the independence of truth.",
  "Why does skillful reasoning in the service of a desire not by itself illustrate the consciousness soul?",
  "The intellectual soul can bring thinking into the service of a personal purpose. The consciousness soul concerns the true and good with a significance independent of that purpose. In the example, devising a persuasive defense differs from examining whether the report needs correction. Steiner distinguishes the orientation of thinking, not merely how clever the reasoning is; all three members remain related in the same person."
],
[
  "Três aspectos da alma",
  "Explicar como o pensar serve ao desejo e como a orientação para a verdade e o bem diferencia os três membros da alma.",
  [
    "A alma senciente acolhe sensações e os desejos, aversões e impulsos ligados a elas. O pensar entra inicialmente nessa vida como auxílio prático. A criança aprende que o fogo queima; as pessoas criam ferramentas, transporte e comunicação para atender às necessidades. Steiner chama a alma servida pelo pensamento de alma do intelecto ou alma intelectual. Nesse papel, o pensar pode organizar um desejo com muita eficácia, enquanto o desejo continua fornecendo sua finalidade.",
    "O argumento muda então de direção. No exemplo do céu estrelado da página 22, o encantamento pertence ao indivíduo, enquanto o conhecimento das trajetórias dos astros tem um significado compartilhável. Na página 23, Steiner distingue a verdade das concepções mutáveis que temos dela: descobrir um erro muda aquilo em que acreditamos, sem tornar a verdade dependente de nosso prazer. Ele entende essa independência como ligação entre a alma e uma realidade espiritual duradoura.",
    "O bem moral oferece o paralelo na página 24. As inclinações podem ser educadas para concordar livremente com o que se reconhece como bom; o bem não recebe seu valor da aprovação de um desejo. O ideal de Steiner é refinar a inclinação, em vez de reprimi-la permanentemente. Um exemplo cotidiano é reconhecer que se deve corrigir uma afirmação enganosa mesmo quando mantê-la traria uma vantagem.",
    "A alma da consciência designa o aspecto da vida anímica no qual o verdadeiro e o bom duradouros se tornam vivos. Isso é mais específico do que estar acordado ou ter qualquer sensação: Steiner reconhece expressamente a consciência comum nos animais. Os três membros são, portanto, alma senciente, alma do intelecto e alma da consciência, relacionadas e interpenetradas, em vez de três compartimentos mentais fechados.",
    "Como aplicação original, compare ouvir uma crítica, planejar uma resposta que conquiste aprovação e examinar se a crítica é justificada. O segundo movimento pode ser inteligente e ainda servir a um desejo; o terceiro procura um julgamento válido mesmo quando ele desagrada. São movimentos na experiência da mesma pessoa, e não categorias para classificar pessoas inteiras.",
    "As páginas finais descrevem essas organizações como aura percebida pelo vidente, introduzindo a discussão posterior da percepção espiritual. O Adendo 4 também qualifica o contraste com os animais da página 21: Steiner não nega pensamento na vida animal, mas o atribui a um Eu de grupo, em vez de a um Eu humano que pensa de modo independente. Aprenda essa distinção como concepção do autor antes de avançar ao próprio Eu."
  ],
  "Use uma pessoa fictícia que recebe uma crítica justificada a um relatório. Descreva a primeira sensação e reação, um plano para preservar a aprovação e um exame do que é verdadeiro e de qual correção seria boa. Explique a função do pensar nos dois últimos casos. Depois escreva uma frase distinguindo um erro na concepção de alguém da afirmação do capítulo sobre a independência da verdade.",
  "Por que raciocinar com habilidade a serviço de um desejo não ilustra, por si só, a alma da consciência?",
  "A alma do intelecto pode colocar o pensar a serviço de uma finalidade pessoal. A alma da consciência se refere ao verdadeiro e ao bom cujo significado independe dessa finalidade. No exemplo, elaborar uma defesa convincente difere de examinar se o relatório precisa de correção. Steiner distingue a orientação do pensar, e não apenas a habilidade do raciocínio; os três membros continuam relacionados na mesma pessoa."
]);
add(5,
1,
"26–35",
"5–6",
[
  "The I and spiritual individuality",
  "Explain the I as the mediator of body, soul, and spirit, and distinguish spirit self, life spirit, and spirit man.",
  [
    "Jean Paul’s childhood recollection introduces awareness of oneself as an independent being. Steiner then uses the word I: any person can name a table, but when each says I about themselves, the reference comes from their own inward standpoint. Addendum 5 qualifies this illustration: repeating the word is different from connecting it with the idea, which develops gradually. The lesson concerns self-awareness rather than a test of how early a child speaks.",
    "The I gathers the experiences of body and soul and acts through them. At the same time, it opens toward spirit. The text’s two directions matter: sensations bring the physical world into experience; intuition brings spiritual content. For Steiner, the I becomes more individual as it makes truth and goodness its own. This is spiritual individuality, not merely the assertion of a private preference.",
    "On page 30 the consciousness soul is in contact with truth independent of liking, while spirit self is that same spiritual truth taken into and individualized by the I. Receiving it does not make truth privately true; it makes it part of this person’s being. The distinction connects the preceding lesson’s orientation toward truth with the spiritual individuality developed here.",
    "Intuition names revelation of the spiritual in contrast with sensation as revelation of the bodily world. Even simple thought is called an elementary manifestation in this discussion. Addendum 6 distinguishes this manifestation from the fuller intuition of supersensible perception developed in other works. A sudden hunch or intensity of conviction therefore does not explain the term’s role in the chapter.",
    "Pages 32–34 add spirit man and life spirit. Spirit man names the independent spiritual being; life spirit names the formative spiritual life that builds and sustains it; spirit self names spirit individualized in the I. The analogies of nourishment and sheath describe how the spiritual being receives from its world and develops its individuality. Steiner explicitly says that spatial enlargement is a picture of a spiritual reality, so do not imagine a second material skin expanding around the body.",
    "The chapter now has three spiritual members as well as three bodily and three soul members. They are connected within one human being. The next lesson brings the names together and explains why the book can regroup them as nine, seven, or four without changing the subject."
  ],
  "Draw the I at the meeting of two arrows: sensation from the physical world and intuition from the spiritual world. Explain the role of consciousness soul and spirit self at that meeting. Add brief entries for life spirit and spirit man using the chapter’s nourishment or sheath analogy, then mark which expressions are pictures rather than physical anatomy. Conclude with Addendum 5’s distinction between using the word I and understanding its idea.",
  "How can a truth be independent of personal preference and still become individualized in spirit self?",
  "Its validity is not changed by being received. The consciousness soul is in contact with that truth; spirit self names the spiritual content made part of the individual I’s own being. Steiner joins a shared or self-existent truth with individual appropriation of it. The I can therefore develop through spiritual content without turning that content into an arbitrary personal opinion."
],
[
  "O Eu e a individualidade espiritual",
  "Explicar o Eu como mediador de corpo, alma e espírito e distinguir si-mesmo espiritual, espírito vital e homem-espírito.",
  [
    "A lembrança de infância de Jean Paul introduz a consciência de si como ser independente. Steiner utiliza então a palavra Eu: qualquer pessoa pode nomear uma mesa, mas, quando cada uma diz Eu a seu próprio respeito, a referência vem de sua perspectiva interior. O Adendo 5 qualifica a ilustração: repetir a palavra difere de ligá-la à ideia, que se desenvolve gradualmente. A lição trata da autoconsciência, e não de um teste sobre a idade em que uma criança começa a falar.",
    "O Eu reúne as experiências do corpo e da alma e atua por meio deles. Ao mesmo tempo, abre-se ao espírito. As duas direções do texto importam: as sensações trazem o mundo físico à experiência; a intuição traz conteúdo espiritual. Para Steiner, o Eu se torna mais individual ao fazer seus a verdade e o bem. Trata-se de individualidade espiritual, e não apenas da afirmação de uma preferência privada.",
    "Na página 30, a alma da consciência está em contato com a verdade independente do gosto, enquanto o si-mesmo espiritual é essa mesma verdade espiritual acolhida e individualizada pelo Eu. Recebê-la não a torna uma verdade privada; torna-a parte do ser desta pessoa. A distinção relaciona a orientação para a verdade da lição anterior à individualidade espiritual desenvolvida aqui.",
    "Intuição designa a revelação do espiritual, em contraste com a sensação como revelação do mundo corporal. Até o pensamento simples é chamado de manifestação elementar nessa discussão. O Adendo 6 distingue essa manifestação da intuição mais plena da percepção suprassensível desenvolvida em outras obras. Um palpite repentino ou a intensidade da convicção, portanto, não explica a função do termo no capítulo.",
    "As páginas 32–34 acrescentam homem-espírito e espírito vital. Homem-espírito designa o ser espiritual independente; espírito vital, a vida espiritual formativa que o constrói e sustenta; si-mesmo espiritual, o espírito individualizado no Eu. As analogias de nutrição e envoltório descrevem como o ser espiritual recebe de seu mundo e desenvolve sua individualidade. Steiner diz explicitamente que o aumento espacial é uma imagem de uma realidade espiritual; por isso, não imagine uma segunda pele material se expandindo ao redor do corpo.",
    "O capítulo agora apresenta três membros espirituais, além de três corporais e três anímicos. Todos se relacionam no mesmo ser humano. A próxima lição reúne os nomes e explica por que o livro pode agrupá-los como nove, sete ou quatro sem mudar de assunto."
  ],
  "Desenhe o Eu no encontro de duas setas: sensação a partir do mundo físico e intuição a partir do mundo espiritual. Explique a função da alma da consciência e do si-mesmo espiritual nesse encontro. Acrescente definições breves de espírito vital e homem-espírito usando a analogia de nutrição ou envoltório do capítulo e identifique quais expressões são imagens, em vez de anatomia física. Conclua com a distinção do Adendo 5 entre usar a palavra Eu e compreender sua ideia.",
  "Como uma verdade pode independer da preferência pessoal e ainda assim se individualizar no si-mesmo espiritual?",
  "Sua validade não muda quando ela é acolhida. A alma da consciência está em contato com essa verdade; o si-mesmo espiritual designa o conteúdo espiritual tornado parte do próprio ser do Eu individual. Steiner relaciona uma verdade compartilhada ou que existe por si à apropriação individual dela. O Eu pode, assim, se desenvolver pelo conteúdo espiritual sem convertê-lo numa opinião pessoal arbitrária."
]);
add(6,
1,
"35–39",
"3",
[
  "One human being, several classifications",
  "Reconstruct the ninefold, grouped sevenfold, fourfold, and transformation-based sevenfold accounts, explaining their connections.",
  [
    "The ending first retraces the chapter’s movement: physical organization supports life, sensation, thinking, and openness to spiritual content. The soul mediates body and spirit. Steiner’s plant image on page 37 gives the relationship a shape: bodily members are the roots in the physical world, spiritual members the flowering in the spirit world, and soul the connecting stalk. Read this as an explanatory image of the account.",
    "The ninefold list on page 36 names A physical body; B ether or life body; C soul body; D sentient soul; E intellectual soul; F consciousness soul; G spirit self; H life spirit; I spirit man. These distinguish bodily, soul, and spiritual aspects of one human being. The letter I in the list is simply the ninth label; it must not be confused with the self called the I.",
    "The first sevenfold account joins C with D and F with G because the text describes them as unities in earthly life. Its full list across pages 36–37 is physical body; etheric or life body; sentient soul body; intellectual soul; spirit-filled consciousness soul; life spirit; spirit man. Two pairs are joined; the distinctions have not been discarded.",
    "The fourfold account on page 37 groups soul body and sentient soul as astral body, and takes intellectual soul and consciousness soul as the related sheaths of the I. It therefore names physical body, life body, astral body, and I. This makes the I’s central role visible while retaining the distinctions developed earlier.",
    "Pages 38–39 then describe transformation through the I’s reception of spirit. Spirit self illuminates and transforms the astral organization of impulses and desires; life spirit transforms the life body; spirit man transforms the physical body. Steiner says that the spiritualized aspect of the physical body requires spiritual perception even though it appears physical to bodily senses. The transformation is his spiritual account, rather than a visible replacement of an organ.",
    "The concluding sevenfold list adds these transformed aspects to the fourfold foundation: physical body; life body; astral body; I as soul kernel; spirit self as transmuted astral body; life spirit as transmuted life body; spirit man as transmuted physical body. Its organizing principle differs from the earlier grouping of nine into seven. Addendum 3’s rainbow and water comparisons explain why Steiner regards the members as real differentiations within a unity, not merely convenient labels; the comparisons illustrate that claim."
  ],
  "Write the nine terms as labeled cards A–I. Join C/D and F/G to reproduce the first sevenfold grouping. On a second sheet draw the fourfold account, then add three arrows: astral body → spirit self, life body → life spirit, physical body → spirit man. Explain the role of the I and the reason the two sevenfold lists have different entries. Finish by applying the original body–soul–spirit distinction to a new encounter and identifying which later concepts the encounter illustrates rather than establishes.",
  "Why do the two sevenfold lists differ, and how does the fourfold account connect them?",
  "The first sevenfold list combines two pairs in the ninefold description of an earthly human being. The fourfold account brings related soul members together around the I as physical body, life body, astral body, and I. The final sevenfold list adds spirit self, life spirit, and spirit man as the transformed astral, life, and physical organizations. The counts arise from different ways of expressing the relationships and development of the same being."
],
[
  "Um ser humano, diferentes classificações",
  "Reconstruir os esquemas de nove, sete por agrupamento, quatro e sete por transformação, explicando suas relações.",
  [
    "O encerramento retoma primeiro o movimento do capítulo: a organização física sustenta vida, sensação, pensar e abertura ao conteúdo espiritual. A alma faz a mediação entre corpo e espírito. A imagem vegetal de Steiner na página 37 dá forma à relação: os membros corporais são as raízes no mundo físico, os espirituais são o florescimento no mundo espiritual e a alma é o caule que os liga. Leia isso como imagem explicativa dessa concepção.",
    "A lista de nove membros da página 36 nomeia A corpo físico; B corpo etérico ou vital; C corpo anímico; D alma senciente; E alma do intelecto; F alma da consciência; G si-mesmo espiritual; H espírito vital; I homem-espírito. Ela distingue aspectos corporais, anímicos e espirituais de um mesmo ser humano. A letra I na lista é apenas o nono rótulo e não deve ser confundida com o Eu, denominado I em inglês.",
    "O primeiro esquema de sete membros reúne C com D e F com G porque o texto os descreve como unidades na vida terrestre. A lista completa nas páginas 36–37 é corpo físico; corpo etérico ou vital; corpo anímico senciente; alma do intelecto; alma da consciência preenchida pelo espírito; espírito vital; homem-espírito. Dois pares são reunidos; as distinções não foram descartadas.",
    "O esquema de quatro membros da página 37 reúne corpo anímico e alma senciente como corpo astral e considera alma do intelecto e alma da consciência como envoltórios relacionados do Eu. Assim, nomeia corpo físico, corpo vital, corpo astral e Eu. Isso torna visível a função central do Eu, preservando as distinções desenvolvidas antes.",
    "As páginas 38–39 descrevem então a transformação pela recepção do espírito no Eu. O si-mesmo espiritual ilumina e transforma a organização astral de impulsos e desejos; o espírito vital transforma o corpo vital; o homem-espírito transforma o corpo físico. Steiner afirma que o aspecto espiritualizado do corpo físico exige percepção espiritual, embora apareça como físico aos sentidos corporais. A transformação pertence à concepção espiritual do autor, em vez de ser uma substituição visível de um órgão.",
    "A lista final de sete membros acrescenta esses aspectos transformados à base de quatro: corpo físico; corpo vital; corpo astral; Eu como núcleo da alma; si-mesmo espiritual como corpo astral transformado; espírito vital como corpo vital transformado; homem-espírito como corpo físico transformado. Seu critério difere do agrupamento anterior de nove em sete. As comparações do Adendo 3 com o arco-íris e a água explicam por que Steiner considera os membros diferenciações reais numa unidade, e não apenas nomes convenientes; as comparações ilustram essa afirmação."
  ],
  "Escreva os nove termos em cartões A–I. Reúna C/D e F/G para reproduzir o primeiro agrupamento de sete. Em outra folha, desenhe o esquema de quatro membros e acrescente três setas: corpo astral → si-mesmo espiritual, corpo vital → espírito vital, corpo físico → homem-espírito. Explique a função do Eu e por que as duas listas de sete têm termos diferentes. Termine aplicando a distinção inicial de corpo, alma e espírito a um novo encontro e identificando quais conceitos posteriores o encontro ilustra, em vez de comprovar.",
  "Por que as duas listas de sete membros diferem e como o esquema de quatro as relaciona?",
  "A primeira lista de sete reúne dois pares na descrição de nove membros do ser humano terrestre. O esquema de quatro reúne membros anímicos relacionados em torno do Eu: corpo físico, corpo vital, corpo astral e Eu. A lista final de sete acrescenta si-mesmo espiritual, espírito vital e homem-espírito como organizações astral, vital e física transformadas. As contagens resultam de maneiras diferentes de expressar as relações e o desenvolvimento do mesmo ser."
]);
