import {temperamentsLessons as steiner} from './temperaments.mjs';
import {understandLessons as childs} from './understand-temperament.mjs';
import {mysteryLessons as mystery} from './mystery-temperaments.mjs';
const n=i=>String(i).padStart(2,'0');
const books={steiner:{lessons:steiner,route:'temperaments',label:'Rudolf Steiner · The Four Temperaments · GA 57'},childs:{lessons:childs,route:'understand-temperament',label:'Gilbert Childs · Understand Your Temperament!'},mystery:{lessons:mystery,route:'mystery-temperaments',label:'Rudolf Steiner · The Mystery of Temperaments'}};
// Twelve learning events, not three books pasted into twelve oversized pages.
const map=[['steiner',0,[['mystery',1],['childs',0]]],['steiner',2,[['mystery',4],['childs',2]]],['steiner',3,[['mystery',9],['childs',3]]],['steiner',4,[['mystery',8],['childs',4]]],['steiner',5,[['mystery',11],['childs',5]]],['steiner',6,[['mystery',10],['childs',6]]],['steiner',7,[['mystery',6],['childs',10]]],['steiner',8,[['mystery',7],['childs',6]]],['childs',7,[['mystery',13]]],['childs',8,[['mystery',13]]],['steiner',9,[['mystery',12]]],['steiner',10,[['mystery',14],['childs',12]]]];
// Rows: title, opening scene, first question, sustained activity, new information.
const events=[
 [
 ['Meet the person before the type','Lea proposes three ideas for a community garden, leaves a planning meeting early, then patiently repairs a broken planter. A teammate calls her unreliable.','What can you describe before explaining Lea’s character?','Begin one continuing case with Lea, or a fictional person of your own. On three occasions, describe an action, your interpretation and another possible explanation. Preserve the first entry for Lesson 12.','Lea left because she had agreed to collect supplies. Revise the judgment without replacing it with an equally absolute positive label.'],
 ['Conheça a pessoa antes do tipo','Lea propõe três ideias para uma horta, sai cedo da reunião e depois conserta um canteiro com paciência. Um colega a chama de pouco confiável.','O que é possível descrever antes de explicar o caráter de Lea?','Comece um caso contínuo com Lea ou alguém fictício. Em três ocasiões, descreva uma ação, sua interpretação e outra explicação possível. Preserve a primeira anotação para a Lição 12.','Lea saiu porque havia combinado buscar materiais. Revise o julgamento sem substituí-lo por um rótulo positivo igualmente absoluto.']
 ],
 [
 ['The four tendencies and their background','One teammate assumes that Lea’s changing interests mean she possesses only the astral member in Steiner’s account.','How would you correct that interpretation of the fourfold map?','On three short visits, reconstruct the four pairings from memory and check the explanation. Add one sentence distinguishing Steiner’s account from an observed behaviour. In the last entry explain the map without assigning Lea a fixed inner constitution.','Lea also shows steadiness in repairs. Explain why this does not require inventing a second person or removing a member from the framework.'],
 ['As quatro tendências e seu fundamento','Um colega supõe que os interesses variáveis de Lea significam que ela possui apenas o membro astral na descrição de Steiner.','Como corrigir essa interpretação do quadro quádruplo?','Em três sessões curtas, reconstrua os quatro pares de memória e confira a explicação. Distinga a descrição de Steiner de um comportamento observado. Ao final, explique o quadro sem atribuir a Lea uma constituição interior fixa.','Lea também mostra constância nos consertos. Explique por que isso não exige inventar outra pessoa nem retirar um membro do quadro.']
 ],
 [
 ['Choleric: purpose and correction','Lea insists that the planter must be finished today. Another volunteer points out that one joint is unstable.','What response could respect initiative and still address the defect?','Write a reply naming a real contribution and a specific problem. Try the structure in three fictional variations: a missed deadline, faulty joint and unclear instruction. Record what changes when the other person supplies more information.','The wood was cut to an incorrect measurement supplied by the organizer. Revise who should check and repair the problem.'],
 ['Colérico: propósito e correção','Lea insiste em terminar o canteiro hoje. Outro voluntário aponta uma união instável.','Que resposta respeita a iniciativa e ainda enfrenta o defeito?','Escreva uma resposta nomeando contribuição real e problema específico. Experimente em três variações fictícias: prazo perdido, união defeituosa e instrução confusa. Registre o que muda quando surgem novas informações.','A madeira foi cortada segundo uma medida incorreta fornecida pela organização. Revise quem deve verificar e reparar o problema.']
 ],
 [
 ['Sanguine: interest and follow-through','Lea starts a bird-sign project enthusiastically, then leaves it for a new idea.','How could an existing interest support one completed step?','Choose one small task of your own. Connect it to an existing interest and define what finished means. Return for three brief sessions, recording the invitation, what you actually completed and what helped you return.','The task was much larger than Lea expected. Reduce its scope and renegotiate the agreement before interpreting the unfinished work.'],
 ['Sanguíneo: interesse e continuidade','Lea começa placas sobre pássaros com entusiasmo, mas deixa o projeto por uma ideia nova.','Como um interesse existente pode apoiar uma etapa concluída?','Escolha uma tarefa pequena sua. Ligue-a a um interesse e defina o que conta como concluído. Retorne em três sessões breves, registrando convite, realização e o que ajudou a voltar.','A tarefa era maior do que Lea esperava. Reduza o escopo e renegocie o acordo antes de interpretar o trabalho inacabado.']
 ],
 [
 ['Phlegmatic: steadiness and participation','A volunteer listens quietly while others plan. Once shown the seed trays, they carefully organize them.','What could invite participation without assuming that quietness means indifference?','Prepare three invitations for the same fictional task: advance notice, a choice of roles and a shared demonstration. Predict a response to each, then explain what you would ask to check the fit. Try one invitation in an ordinary agreed activity if useful.','The volunteer says that instructions were difficult to hear. Revise the arrangement before attributing the response to temperament.'],
 ['Fleumático: constância e participação','Uma pessoa ouve o planejamento em silêncio. Quando vê as bandejas de sementes, organiza tudo com cuidado.','O que pode convidar à participação sem supor que silêncio seja indiferença?','Prepare três convites para a mesma tarefa fictícia: aviso antecipado, escolha de funções e demonstração compartilhada. Preveja respostas e explique como perguntaria sobre a adequação. Se útil, experimente um convite numa atividade combinada.','A pessoa diz que não conseguia ouvir bem as instruções. Revise o ambiente antes de atribuir a resposta ao temperamento.']
 ],
 [
 ['Melancholic: sensitivity and care','A volunteer worries that the seedlings will fail and returns repeatedly to last year’s losses.','How can you acknowledge the concern and offer a manageable next step?','Write three responses to the fictional concern: one that dismisses it, one that assumes you know its cause and one that asks before offering help. Compare their likely effects. Revise the third into a practical invitation the person may decline.','The person points to an actual drainage problem. Add a practical repair to your response rather than treating every concern as a mood.'],
 ['Melancólico: sensibilidade e cuidado','Uma pessoa teme perder as mudas e volta repetidamente às perdas do ano anterior.','Como reconhecer a preocupação e oferecer um próximo passo possível?','Escreva três respostas fictícias: uma que descarta a preocupação, outra que presume sua causa e outra que pergunta antes de ajudar. Compare efeitos possíveis. Transforme a terceira num convite prático que a pessoa possa recusar.','A pessoa aponta um problema real de drenagem. Acrescente uma reparação prática, em vez de tratar toda preocupação como estado de ânimo.']
 ],
 [
 ['Mixtures, context and change','Your notes describe Lea as forceful in planning, easily distracted by new ideas, and patient with repairs.','Does one of these observations have to be discarded to keep a temperament label?','Revisit three entries from your continuing case. For each, add a counterexample or changed circumstance. Compare the sources’ discussion of mixtures and appearance; identify a claim you cannot establish from your observations.','Lea explains that repairing gives her uninterrupted time. Revise your account to include the conditions that support her attention.'],
 ['Combinações, contexto e mudança','Suas notas descrevem Lea como firme no planejamento, atraída por novidades e paciente nos consertos.','É preciso descartar alguma observação para preservar um rótulo?','Retome três anotações do caso contínuo. Acrescente um contraexemplo ou mudança de circunstância a cada uma. Compare o tratamento de combinações e aparência nas fontes; identifique uma afirmação que suas observações não estabelecem.','Lea explica que os consertos lhe dão tempo sem interrupções. Inclua as condições que apoiam sua atenção.']
 ],
 [
 ['Supporting a learner','A learner struggles to finish a planting task. One adult offers a clear demonstration; another proposes a small task connected to the learner’s interest.','What would you need to know to choose between those supports?','Use three versions of one fictional learning task: unclear instructions, excessive difficulty and limited interest. Choose a support for each, say what response you would look for and set a point to review it. Explain how the learner can contribute to that review.','The learner says they understood the task but could not reach the materials. Revise the support to address access.'],
 ['Apoiar quem aprende','Uma criança não termina o plantio. Um adulto oferece uma demonstração clara; outro propõe uma tarefa pequena ligada ao interesse dela.','O que você precisa saber para escolher entre esses apoios?','Use três versões de uma tarefa fictícia: instruções confusas, dificuldade excessiva e pouco interesse. Escolha um apoio, indique a resposta esperada e um momento para revisar. Explique como quem aprende participa da revisão.','A criança diz que entendeu a tarefa, mas não alcançava os materiais. Revise o apoio para resolver o acesso.']
 ],
 [
 ['Working together','The garden needs a planner, a welcoming host and a careful checker. Someone wants to assign these jobs from temperament labels.','Which information would make these assignments more reasonable?','Create a plan with task, demonstrated skill, preference and support needed. Review it at three checkpoints: before starting, during the task and afterward. A fictional team is sufficient. Record how members can request a change.','The quiet teammate has substantial experience welcoming newcomers and asks for that role. Update the plan and explain which earlier assumption changed.'],
 ['Trabalhar em conjunto','A horta precisa de planejamento, acolhimento e conferência. Alguém quer distribuir funções por rótulos temperamentais.','Quais informações tornariam essa distribuição mais razoável?','Crie um plano com tarefa, habilidade demonstrada, preferência e apoio necessário. Revise antes, durante e depois da tarefa. Uma equipe fictícia basta. Registre como alguém pode pedir uma mudança.','A pessoa mais quieta tem experiência acolhendo iniciantes e pede essa função. Atualize o plano e explique qual suposição mudou.']
 ],
 [
 ['Relationships and communication','Lea wants to decide immediately; a teammate wants time alone to consider the options. Each calls the other difficult.','What agreement could respect both pace and a shared deadline?','Use one fictional disagreement about pace, privacy or decisions. Draft a question that invites each person’s account. In three entries, develop an initial agreement, a difficulty that tests it and a revised agreement. Avoid compatibility scores.','The deadline can move by one day, but materials must be ordered tonight. Separate the urgent decision from the one that can wait.'],
 ['Relações e comunicação','Lea quer decidir imediatamente; um colega quer tempo para pensar sozinho. Cada um considera o outro difícil.','Que acordo respeita ritmos diferentes e um prazo comum?','Use um desacordo fictício sobre ritmo, privacidade ou decisões. Formule uma pergunta que acolha cada relato. Em três anotações, desenvolva acordo inicial, dificuldade que o testa e acordo revisado. Evite notas de compatibilidade.','O prazo pode mudar um dia, mas os materiais precisam ser pedidos hoje. Separe a decisão urgente da que pode esperar.']
 ],
 [
 ['Self-education through a small experiment','You keep planning to read about the garden but leave the book where you rarely sit.','Which circumstance could you change before making a judgment about your willpower?','Choose one modest habit. Change one circumstance, define a small completion point and try it on three occasions. Record what happened, including no change. Keep or revise the arrangement based on the result, without making your temperament a fixed identity.','Moving the book helps, but the chosen time is continually interrupted. Keep the helpful change and test a different time separately.'],
 ['Autoeducação por um pequeno experimento','Você pretende ler sobre a horta, mas deixa o livro onde quase nunca se senta.','Que circunstância poderia mudar antes de julgar sua força de vontade?','Escolha um hábito modesto. Mude uma circunstância, defina uma conclusão pequena e experimente em três ocasiões. Registre inclusive a ausência de mudança. Preserve ou revise o arranjo pelo resultado, sem transformar temperamento em identidade fixa.','Mudar o livro ajuda, mas o horário sofre interrupções. Preserve a mudança útil e teste outro horário separadamente.']
 ],
 [
 ['A more attentive encounter','You return to the early judgment that Lea was unreliable. Your notebook now contains several situations, her explanation and different supports.','What can you now explain more precisely, and what remains uncertain?','Build one final account from the opening entry and three later notes. Explain a temperament concept, compare two named sources, identify a disagreement or limitation, and propose one revisable response. After another practice session, record what still needs work.','A new project presents different constraints. Explain which parts of your account transfer and what must be learned afresh.'],
 ['Um encontro mais atento','Você volta ao julgamento inicial de que Lea era pouco confiável. O caderno reúne situações, o relato dela e apoios diferentes.','O que você explica agora com mais precisão e o que permanece incerto?','Construa uma síntese com a anotação inicial e três posteriores. Explique um conceito, compare duas fontes nomeadas, identifique divergência ou limite e proponha uma resposta revisável. Após outra sessão prática, registre o que ainda exige trabalho.','Um novo projeto apresenta outras condições. Explique o que pode ser transferido e o que precisa ser aprendido novamente.']
 ]
];
const responses=[
 ['Lea proposed ideas, left early and completed a repair. “Unreliable” is an interpretation that needs information about agreements and circumstances. Keep all three actions in view; one temperament label cannot account for them on its own.','Lea propôs ideias, saiu cedo e concluiu um conserto. “Pouco confiável” é uma interpretação que exige informações sobre acordos e circunstâncias. Preserve as três ações; um rótulo não as explica sozinho.'],
 ['All four members belong to the person in Steiner’s account. The pairings concern predominance: I/choleric, astral/sanguine, etheric/phlegmatic and physical/melancholic. Lea’s varied actions do not establish which member predominates or verify the spiritual explanation.','Os quatro membros pertencem à pessoa na descrição de Steiner. Os pares indicam predominância: Eu/colérico, astral/sanguíneo, etérico/fleumático e físico/melancólico. As ações variadas de Lea não estabelecem qual predomina nem verificam a explicação espiritual.'],
 ['A useful reply could be: “You have brought the frame together; this joint still moves. Can we check it together before deciding the finishing time?” This acknowledges initiative while making quality open to inspection. Childs’s distinction between appreciation and flattery helps keep the feedback specific.','Uma resposta possível: “Você montou a estrutura; esta união ainda se move. Podemos conferir juntos antes de decidir o horário de conclusão?” Isso reconhece a iniciativa e permite examinar a qualidade. A distinção de Childs entre apreciação e bajulação ajuda a manter a resposta específica.'],
 ['Start with one bird Lea wants to investigate, then agree to finish one small sign before expanding the project. Interest provides an entry; an explicit completion point makes follow-through discussable. This combines the Steiner readings’ attention to interest with Childs’s discussion of commitments.','Comece com um pássaro que Lea queira investigar e combine terminar uma placa pequena antes de ampliar o projeto. O interesse oferece entrada; um ponto de conclusão permite discutir continuidade. Isso reúne a atenção ao interesse nas leituras de Steiner e a discussão de compromissos em Childs.'],
 ['Show the task and offer a choice of a small contribution, with time to prepare. Quietness alone does not reveal lack of interest. The invitation should help you learn what support fits, rather than act as a test that confirms a predetermined type.','Mostre a tarefa e ofereça uma pequena contribuição à escolha, com tempo para preparação. Silêncio não revela, sozinho, falta de interesse. O convite deve ajudar a descobrir o apoio adequado, em vez de confirmar um tipo decidido previamente.'],
 ['Ask what specifically worries the volunteer, acknowledge the earlier loss, and offer to check one seedling together. A small voluntary act of care can connect sensitivity with practical participation. It should not dismiss the worry, manufacture suffering or require cheerfulness.','Pergunte o que preocupa a pessoa, reconheça a perda anterior e ofereça conferir uma muda em conjunto. Um pequeno cuidado voluntário pode ligar sensibilidade e participação prática. Não deve descartar a preocupação, fabricar sofrimento nem exigir alegria.'],
 ['Keep the apparently contrasting observations. The sources discuss mixtures, while the case also raises questions about task, setting and interruptions. A useful account states these conditions instead of selecting only evidence that fits the first label.','Preserve as observações aparentemente contrastantes. As fontes discutem combinações, enquanto o caso levanta questões sobre tarefa, ambiente e interrupções. Um relato útil explicita essas condições em vez de selecionar apenas o que combina com o primeiro rótulo.'],
 ['Ask the learner to show where the task becomes difficult. A demonstration may help unclear instructions; a smaller achievable step may help excessive scope; an interest may offer a way into the task. Choose a support for an identified difficulty, then listen to the response.','Peça que quem aprende mostre onde a tarefa fica difícil. Uma demonstração pode esclarecer instruções; uma etapa menor pode reduzir o excesso de trabalho; um interesse pode oferecer uma entrada. Escolha apoio para uma dificuldade identificada e ouça a resposta.'],
 ['Discuss relevant experience, preferences, the actual task and support needed. Agree on a review point so that a role can change. Childs supplies the workplace discussion; our adaptation uses demonstrated capacities instead of deciding a role from appearance or a temperament label.','Discuta experiência pertinente, preferências, tarefa real e apoio necessário. Combine uma revisão para permitir mudanças de função. Childs fornece a discussão do trabalho; nossa adaptação usa capacidades demonstradas em vez de decidir funções pela aparência ou por rótulos.'],
 ['Ask which decisions require discussion now and how much consideration time is possible. Agree on a deadline and a way to share reasons. Childs’s pairings can generate questions about differences, but they cannot decide whether these particular people can cooperate.','Pergunte quais decisões exigem conversa agora e quanto tempo para pensar é possível. Combine prazo e forma de compartilhar razões. Os pares de Childs podem gerar perguntas sobre diferenças, mas não decidem se estas pessoas conseguem cooperar.'],
 ['Put the book beside a place you already use, choose a short passage and define a small completion point. This changes an observable circumstance. The result can be checked without concluding that an inner type caused either the original difficulty or the improvement.','Coloque o livro junto de um lugar que você usa, escolha um trecho curto e defina uma conclusão pequena. Isso muda uma circunstância observável. O resultado pode ser verificado sem concluir que um tipo interior causou a dificuldade ou a melhora.'],
 ['A stronger account keeps the initial evidence, adds Lea’s explanation and distinguishes the sources’ concepts from your interpretation. Name the support you would offer and the observation that would make you revise it. Improvement means more precise understanding, not certainty about an inner type.','Um relato mais sólido preserva a evidência inicial, acrescenta a explicação de Lea e distingue conceitos das fontes de sua interpretação. Nomeie o apoio oferecido e a observação que levaria à revisão. Melhorar significa compreender com mais precisão, não ter certeza sobre um tipo interior.']
];
const revisionAnswers=[
 ['Leaving early fulfilled an agreement. Remove that action as evidence of unreliability while retaining questions about the other commitments.','Sair cedo cumpriu um acordo. Retire essa ação das evidências de falta de confiabilidade e preserve perguntas sobre outros compromissos.'],
 ['A predominance account allows other tendencies to be present. The observation of patience should be retained without pretending it measures an etheric body.','Uma descrição de predominância permite outras tendências. Preserve a observação de paciência sem fingir que ela mede um corpo etérico.'],
 ['The organizer should acknowledge the incorrect measurement and join the repair. Responsibility follows the evidence, not the presumed temperament of the person holding the tools.','A organização deve reconhecer a medida incorreta e participar da reparação. A responsabilidade acompanha a evidência, não o temperamento presumido de quem segura as ferramentas.'],
 ['Agree on one achievable sign and a review time. The original promise may have rested on an unclear scope; address that before treating noncompletion as a stable trait.','Combine uma placa realizável e um momento de revisão. A promessa inicial talvez dependesse de escopo pouco claro; resolva isso antes de tratar a não conclusão como traço estável.'],
 ['Make the instructions audible or provide a written demonstration, then ask whether the task is clear. A communication barrier changes the interpretation of quietness.','Torne as instruções audíveis ou ofereça uma demonstração escrita e pergunte se a tarefa ficou clara. Uma barreira de comunicação muda a interpretação do silêncio.'],
 ['Inspect the drainage together and agree on a repair. The concern contains information about a real condition; reassurance alone would leave it unresolved.','Confiram a drenagem e combinem uma reparação. A preocupação contém informação sobre uma condição real; tranquilizar não a resolveria.'],
 ['Include uninterrupted time as a condition supporting patient work. Keep the temperament comparison as a question, not the sole explanation.','Inclua tempo sem interrupções como condição que apoia o trabalho paciente. Preserve a comparação temperamental como pergunta, não como explicação única.'],
 ['Move the materials within reach or arrange suitable assistance, then retry the task. Interest and temperament were not enough to explain the access problem.','Aproxime os materiais ou organize assistência adequada e retome a tarefa. Interesse e temperamento não bastavam para explicar o problema de acesso.'],
 ['Give the teammate a chance to host with agreed support and review. Quiet behaviour in one meeting was weak evidence about their skill in welcoming people.','Dê à pessoa a oportunidade de acolher, com apoio e revisão combinados. Silêncio numa reunião era evidência fraca sobre sua habilidade de recepção.'],
 ['Order only what must be decided tonight and schedule the remaining choice tomorrow. The agreement now distinguishes a real constraint from an assumed urgency.','Peçam apenas o que precisa ser decidido hoje e programem a escolha restante para amanhã. O acordo distingue uma restrição real de uma urgência presumida.'],
 ['Keep the book accessible and try a shorter, less interrupted time. Record whether that specific adjustment helps before changing several other conditions.','Mantenha o livro acessível e teste um horário curto com menos interrupções. Registre se esse ajuste ajuda antes de mudar várias outras condições.'],
 ['Transfer the habit of observing, asking and reviewing. Learn the new agreements, resources and constraints again rather than assuming the old arrangement will fit.','Transfira o hábito de observar, perguntar e revisar. Conheça os novos acordos, recursos e limites em vez de supor que o arranjo anterior servirá.']
];
export const temperamentCourse=map.map(([book,index,extra],id)=>({id,...Object.fromEntries(['en','pt'].map((lang,i)=>{
 const primary=books[book].lessons[index][lang],e=events[id][i];
 return [lang,{...primary,title:e[0],example:e[1],question:e[2],activity:e[3],transfer:e[4],
  explanation:responses[id][i],
  goal:id===9?(i?'Explore diferenças de ritmo, privacidade e decisões por acordos revisáveis.':'Explore differences in pace, privacy and decisions through revisable agreements.'):primary.goal,
  key:primary.key+' '+primary.context,
  sources:[[book,index],...extra].map(([b,j])=>({label:books[b].label,url:'../../'+books[b].route+'/lessons/'+n(j)+'.html',focus:books[b].lessons[j][lang].title})),
  comparison:extra.map(([b,j])=>({label:books[b].label,text:books[b].lessons[j][lang].takeaway})),
  checks:[[e[2],responses[id][i]],[(i?'Nova informação: ':'New information: ')+e[4],revisionAnswers[id][i]]]
 }];
}))}));
