export function temperamentsVisual(id,lang){
 const pt=lang==='pt';
 if(id===1)return `<section class="temperaments-map" id="temperament-two-streams"><h2>${pt?'As duas correntes e sua mediação':'The two streams and their mediation'}</h2><table><caption>${pt?'Tabela explicativa original do argumento de Steiner, capturas 7–8. A individualidade reencarnante é uma premissa de sua descrição espiritual.':'Original explanatory table of Steiner’s argument, captures 7–8. Reincarnating individuality is a premise of his spiritual account.'}</caption><thead><tr>${(pt?['Elemento','O que traz','Relação com o temperamento']:['Element','What it brings','Relation to temperament']).map(h=>`<th scope="col">${h}</th>`).join('')}</tr></thead><tbody>${(pt?[
 ['Corrente hereditária','Características recebidas da linhagem familiar.','Uma das correntes que se encontram na pessoa.'],
 ['Individualidade','Aquilo que a individualidade traz de encarnações anteriores, segundo Steiner.','A outra corrente, que se une à constituição herdada.'],
 ['Temperamento','A maneira pela qual as duas correntes se combinam.','Mediador que dá expressão externa à vida interior.']
 ]:[
 ['Hereditary stream','Characteristics received from the ancestral line.','One of the streams meeting in the person.'],
 ['Individuality','What individuality brings from earlier incarnations, according to Steiner.','The other stream, joining the inherited constitution.'],
 ['Temperament','The manner in which the two streams combine.','The mediator giving outward expression to inner life.']
 ]).map(r=>`<tr><th scope="row">${r[0]}</th><td>${r[1]}</td><td>${r[2]}</td></tr>`).join('')}</tbody></table></section>`;
 if(id===0||id===10)return `<section class="inquiry-diagrams"><h2>${pt?'Da observação à resposta':'From observation to response'}</h2><ol><li>${pt?'Descreva a situação e o comportamento.':'Describe the situation and behaviour.'}</li><li>${pt?'Distinga a interpretação e procure um contraexemplo.':'Distinguish the interpretation and look for a counterexample.'}</li><li>${pt?'Ofereça uma resposta concreta e confira sua adequação.':'Offer a concrete response and check its fit.'}</li></ol></section>`;
 if(id!==2&&id!==8)return '';
 const headers=pt?['Tipo','Membro predominante, segundo Steiner','Via educativa proposta']:['Type','Predominant member, according to Steiner','Proposed educational route'];
 const rows=pt?[['Colérico','Portador do Eu','Respeito pela competência; desafio'],['Sanguíneo','Corpo astral','Afeto e interesse pessoal'],['Fleumático','Corpo etérico ou vital','Interesses dos companheiros'],['Melancólico','Corpo físico','Compaixão pelo destino alheio']]:[['Choleric','I-bearer','Respect for competence; challenge'],['Sanguine','Astral body','Affection and personal interest'],['Phlegmatic','Etheric or life body','Companions’ interests'],['Melancholic','Physical body','Compassion for another’s destiny']];
 return `<section class="temperaments-map"><h2>${pt?'Mapa de leitura':'Reading map'}</h2><table><caption>${pt?'Correspondências e vias educativas descritas por Steiner, capturas 8–12. A tabela resume a leitura; as atividades do curso são adaptações originais.':'Correspondences and educational routes described by Steiner, captures 8–12. The table summarizes the reading; course activities are original adaptations.'}</caption><thead><tr>${headers.map(h=>`<th scope="col">${h}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr><th scope="row">${r[0]}</th><td>${r[1]}</td><td>${r[2]}</td></tr>`).join('')}</tbody></table></section>`;
}
