// Original bilingual close teaching. Paragraph references use the linked Adams edition.
export const thinkingDepth = [
 {id:0,refs:'§§ 2, 7–8',en:[
 ['A clever plan still needs contact with the situation','A plan can sound reasonable because its parts fit your assumptions. Practical thinking also asks whether those assumptions fit the actual circumstances. In Steiner’s railway-truck comparison, effort within the imagined arrangement is mistaken for a means of propelling the whole arrangement. The teaching point is to inspect what your explanation leaves out.','Course example: “If I print the instructions in larger letters, everyone will understand.” Larger letters may help someone who cannot read the sign at its present size. They will not explain an unfamiliar word. Ask what difficulty the visitor actually has before deciding which change addresses it.','Does a new idea become practical merely because it differs from the old habit?','Ask how the proposed change meets the observed difficulty.','No. Both a habit and a new idea need reasons that fit the case. Novelty alone is not evidence of usefulness.']
 ],pt:[
 ['Um plano engenhoso ainda precisa encontrar a situação real','Um plano pode parecer razoável porque suas partes combinam com suas suposições. O pensar prático também pergunta se essas suposições correspondem às circunstâncias. Na comparação de Steiner com o vagão, o esforço dentro do arranjo imaginado é confundido com um meio de impulsionar o conjunto. A questão didática é examinar o que sua explicação deixa de fora.','Exemplo do curso: “Se eu imprimir as instruções com letras maiores, todos entenderão”. Letras maiores podem ajudar quem não consegue ler a placa no tamanho atual. Não explicarão uma palavra desconhecida. Descubra a dificuldade do visitante antes de decidir qual mudança a resolve.','Uma ideia nova se torna prática apenas por ser diferente do hábito antigo?','Pergunte como a mudança proposta responde à dificuldade observada.','Não. Tanto um hábito quanto uma ideia nova precisam de razões adequadas ao caso. A novidade, sozinha, não demonstra utilidade.']
 ]},
 {id:1,refs:'§§ 9–13; compare §§ 46–48',en:[
 ['Confidence in understanding is different from confidence in your first answer','Steiner’s spiritual premise is that the world contains relationships that thought can discover. It does not follow that whatever first occurs to you must express those relationships. You still have to observe, compare and revise. His call for confidence can therefore support patient inquiry without settling the answer in advance.','Course example: “There must be a reason this door keeps sticking” leaves the cause open. “The cause must be the one I already imagined” closes the inquiry prematurely. The first attitude motivates investigation; the second substitutes certainty for it.','Can you accept the lecture’s premise and still be mistaken about a particular event?','Distinguish a general claim about intelligibility from a particular explanation.','Yes. Belief that events can be understood does not make every explanation correct. The exercises ask you to bring your own ideas into better relation with what happens.']
 ],pt:[
 ['Confiar na possibilidade de compreender difere de confiar na primeira resposta','A premissa espiritual de Steiner é que o mundo contém relações que o pensar pode descobrir. Disso não resulta que toda ideia inicial expresse essas relações. Ainda é necessário observar, comparar e revisar. Seu convite à confiança pode apoiar uma investigação paciente sem decidir previamente a resposta.','Exemplo do curso: “Deve haver uma razão para esta porta emperrar” deixa a causa em aberto. “A causa tem de ser aquela que já imaginei” encerra a investigação cedo demais. A primeira atitude motiva a investigação; a segunda substitui investigar por certeza.','É possível aceitar a premissa da palestra e ainda se enganar sobre um acontecimento?','Distinga uma afirmação geral sobre a possibilidade de compreender de uma explicação particular.','Sim. A crença de que acontecimentos podem ser compreendidos não torna correta toda explicação. Os exercícios pedem que você aproxime suas ideias do que acontece.']
 ]},
 {id:2,refs:'§§ 14–18',en:[
 ['What does “refraining from thought” mean in this exercise?','The surrounding instructions still ask you to attend, form images and compare them. Here, refraining concerns arbitrary speculation: adding a story before you have grasped the observations. It is not a demand to stop all mental activity or to make your mind blank.','If you write “the edge became less distinct”, you are already using concepts and language. That is compatible with the exercise. “The weather must change because that shape is a sign” adds a further interpretation which the observation has not established.','Does using words to describe a cloud violate the instruction?','Read the instruction together with the request to form and compare clear pictures.','No. Our written descriptions support the comparison. What is postponed is an unsupported explanation, not the activity needed to attend and describe.']
 ],pt:[
 ['O que significa abster-se de pensar neste exercício?','As instruções ao redor ainda pedem atenção, formação de imagens e comparação. Aqui, a abstenção se refere à especulação arbitrária: acrescentar uma narrativa antes de apreender as observações. Não é uma exigência de interromper toda atividade mental ou esvaziar a mente.','Ao escrever “a borda ficou menos nítida”, você já usa conceitos e linguagem. Isso é compatível com o exercício. “O tempo deve mudar porque aquela forma é um sinal” acrescenta uma interpretação que a observação não estabeleceu.','Usar palavras para descrever uma nuvem viola a instrução?','Leia a instrução junto ao pedido de formar e comparar imagens claras.','Não. As descrições escritas do curso apoiam a comparação. Adia-se uma explicação sem fundamento, não a atividade necessária para prestar atenção e descrever.']
 ]},
 {id:3,refs:'§§ 14–18; contrast §§ 19–23',en:[
 ['Separate the observed sequence from the unobserved interval','A sequence is an ordered set of observations: first this, later that. The interval between them may contain events you did not see. When Steiner asks you to let the pictures pass into one another, keep the observed endpoints clear; an imagined transition does not become a record of what occurred.','Course example: at one observation a leaf is tightly folded; at the next it is more open. Compare the outline, position and visible surfaces. You can describe a direction of change without claiming to have seen every intermediate stage.','If you imagine the leaf opening smoothly, have you observed that exact movement?','Ask whether you watched the interval or reconstructed it afterward.','No. You observed the endpoints. The imagined transition helps compare them but does not supply missing observations.'],
 ['Choose the exercise that fits what you know','In this exercise the connection is still unclear, so observation and comparison come first. In the following exercise Steiner turns to cases where you have enough understanding to propose an expectation. These instructions address different starting conditions.','For now, write “I do not yet know why.” Keep a possible explanation in a separate question for later, rather than treating it as the task you must solve today. This is active attention to what you have, not indifference to explanation.','Must you produce two causes before this exercise counts as complete?','The reading asks for faithful successive pictures before speculation.','No. A precise comparison with an honestly unanswered question can complete this stage. Causal inquiry is developed in the following lessons.']
 ],pt:[
 ['Separe a sequência observada do intervalo não observado','Uma sequência é um conjunto ordenado de observações: primeiro isto, depois aquilo. O intervalo pode conter acontecimentos que você não viu. Quando Steiner pede a passagem de uma imagem à outra, conserve claros os estados observados; uma transição imaginada não vira registro do que ocorreu.','Exemplo do curso: numa observação, uma folha está bem dobrada; na seguinte, mais aberta. Compare contorno, posição e superfícies visíveis. É possível descrever uma direção de mudança sem afirmar que viu todas as etapas intermediárias.','Imaginar a folha se abrindo suavemente significa que você observou esse movimento exato?','Pergunte se acompanhou o intervalo ou o reconstruiu depois.','Não. Você observou os estados inicial e posterior. A transição imaginada ajuda a compará-los, mas não fornece as observações ausentes.'],
 ['Escolha o exercício adequado ao que sabe','Neste exercício, a relação ainda é pouco clara; por isso, observação e comparação vêm primeiro. No seguinte, Steiner passa a situações em que há compreensão suficiente para propor uma expectativa. As instruções respondem a pontos de partida diferentes.','Por enquanto, escreva “Ainda não sei por quê”. Preserve uma explicação possível como pergunta separada para depois, sem tratá-la como a tarefa obrigatória de hoje. É atenção ativa ao que você tem, não desinteresse pela explicação.','É obrigatório produzir duas causas para completar o exercício?','A leitura pede imagens sucessivas fiéis antes da especulação.','Não. Uma comparação precisa com uma pergunta honestamente em aberto pode completar esta etapa. A investigação causal será desenvolvida nas próximas lições.']
 ]},
 {id:4,refs:'§§ 19–21',en:[
 ['Prediction, explanation and conditions are three different things','A prediction says what you expect to observe. An explanation says why you expect it. Conditions specify what must stay relevantly similar for that expectation to apply. Write these separately before the result is known, so that you can see what changed.','Course example: “Fewer newcomers will ask where tools belong” is the prediction. “They will see the new sign before putting tools away” is the proposed explanation. Similar numbers of newcomers and similar help from volunteers are relevant conditions. If the session changes substantially, record that rather than silently changing your original claim.','Why is “things will be better” hard to check?','Ask which visible result would count as better, and when.','It does not specify an observable outcome. A clearer expectation names the event, the group involved and the occasion on which you will compare it.'],
 ['A matching result is support, not exclusive proof','The lecture asks you to compare expectations with events. Our course adds an explicit caution: more than one account may fit the same outcome. A success can support an expectation without identifying a unique cause; a mismatch is a reason to examine the expectation and its conditions.','Suppose eight of twenty newcomers asked for help before a change, and four of ten afterward. The raw count fell, but both groups had the same proportion asking: four in ten. This constructed example shows why you must compare like with like before concluding that the sign helped.','Does getting one prediction right show that you can read another person’s intentions?','Consider what you actually predicted and what the result can establish.','No. One outcome does not reveal private intentions or establish a general ability. Record the specific result and the limits of what it supports.']
 ],pt:[
 ['Previsão, explicação e condições são coisas diferentes','Uma previsão diz o que você espera observar. Uma explicação diz por quê. As condições indicam o que precisa permanecer suficientemente semelhante para a expectativa se aplicar. Escreva separadamente antes de conhecer o resultado, para perceber o que mudou.','Exemplo do curso: “Menos visitantes novos perguntarão onde guardar ferramentas” é a previsão. “Verão a nova placa antes de guardar os objetos” é a explicação proposta. Quantidades semelhantes de visitantes novos e ajuda semelhante dos voluntários são condições relevantes. Se a sessão mudar muito, registre isso sem modificar silenciosamente a afirmação inicial.','Por que “as coisas vão melhorar” é difícil de verificar?','Pergunte qual resultado visível contaria como melhora e quando.','A frase não especifica um resultado observável. Uma expectativa mais clara nomeia o acontecimento, o grupo envolvido e a ocasião da comparação.'],
 ['Um resultado correspondente apoia, mas não prova uma causa exclusiva','A palestra pede comparar expectativas e acontecimentos. Nosso curso explicita um cuidado adicional: mais de uma explicação pode corresponder ao mesmo resultado. Um acerto pode apoiar a expectativa sem identificar uma causa única; uma divergência pede examinar a expectativa e suas condições.','Suponha que oito de vinte visitantes novos pedissem ajuda antes da mudança, e quatro de dez depois. O número caiu, mas a proporção foi igual: quatro em dez. Esse exemplo construído mostra por que é preciso comparar situações semelhantes antes de concluir que a placa ajudou.','Acertar uma previsão demonstra que você consegue ler as intenções de alguém?','Considere o que previu e o que o resultado realmente estabelece.','Não. Um resultado não revela intenções privadas nem estabelece uma capacidade geral. Registre o resultado específico e os limites do que ele apoia.']
 ]},
 {id:5,refs:'§§ 22–26; compare § 38',en:[
 ['Working backward means proposing a cause and checking it','Steiner now starts with a present event and asks what may have led to it. This differs from forecasting a later event. A hypothesis is a possible explanation awaiting examination. It is not a recovered memory, even when you can picture it vividly.','Course example: yesterday the tray held six pencils; today it holds four. “Two were borrowed” and “two were put in a different drawer” are hypotheses. A dated borrowing note or finding the pencils in that drawer would bear on them. Your ability to tell either story smoothly does not establish it.','What makes this more than imagining a convincing past?','Look for the step after you propose the possible cause.','You look for what actually happened, compare it with your proposal and correct the proposal. Without that check it remains an unverified account.'],
 ['Earlier does not automatically mean causal','A cause contributes to producing an event; merely occurring earlier is not enough. In § 38 Steiner illustrates how a reader may even reverse cause and effect. Our course uses an ordinary example to practise keeping the direction open until there is evidence.','You notice a wet patch under a vase and conclude the vase leaked. Perhaps water was spilled before the vase was placed there. Check the vase, the surrounding surface and any available account of the sequence. If the evidence is missing, retain the uncertainty.','Can a neat timetable prove why a real event happened?','Distinguish planning how tasks could fit together from investigating what occurred.','No. A timetable can clarify dependencies, but a past event needs evidence about its actual circumstances. This lesson’s main task is causal inquiry, not scheduling.']
 ],pt:[
 ['Investigar para trás significa propor uma causa e verificá-la','Steiner parte agora de um acontecimento presente e pergunta o que pode tê-lo preparado. Isso difere de prever um acontecimento posterior. Hipótese é uma explicação possível a ser examinada. Não é uma lembrança recuperada, mesmo quando você a imagina vividamente.','Exemplo do curso: ontem havia seis lápis na bandeja; hoje há quatro. “Dois foram emprestados” e “dois foram guardados em outra gaveta” são hipóteses. Um registro datado de empréstimo ou encontrar os lápis na gaveta ajudaria a examiná-las. Contar bem qualquer uma dessas histórias não a estabelece.','O que torna isso diferente de imaginar um passado convincente?','Procure a etapa posterior à proposta de causa.','Você busca o que realmente aconteceu, compara com sua proposta e a corrige. Sem essa verificação, ela permanece uma explicação não confirmada.'],
 ['Vir antes não significa automaticamente causar','Uma causa contribui para produzir um acontecimento; apenas ocorrer antes não basta. No § 38, Steiner ilustra como alguém pode até inverter causa e efeito. Nosso curso usa um exemplo comum para praticar a suspensão da conclusão até haver evidência.','Você percebe uma mancha molhada sob um vaso e conclui que ele vazou. Talvez a água tenha sido derramada antes de colocarem o vaso ali. Examine o vaso, a superfície ao redor e algum relato disponível da sequência. Se faltar evidência, preserve a incerteza.','Um cronograma bem organizado prova por que um acontecimento ocorreu?','Distinga planejar como tarefas poderiam se encaixar de investigar o que aconteceu.','Não. Um cronograma pode esclarecer dependências, mas um acontecimento passado exige evidência sobre as circunstâncias reais. A tarefa principal desta lição é investigação causal, não planejamento de horários.']
 ]},
 {id:6,refs:'§ 28',en:[
 ['Voluntary direction is not a battle to have no other thoughts','The practical distinction is between being carried along by whatever appears and deliberately returning to a selected subject. For this course, noticing a diversion and returning is part of practice, not a reason to judge yourself as incapable. A thought can arise without determining the whole session.','Choose a quiet, ordinary subject outside the worry currently occupying you. “I will think about that footbridge’s shape and use” gives you something to return to. “I must not think about work” keeps work at the centre and does not specify a new subject.','What should you record if you noticed several distractions?','Record the action you could take, rather than a verdict on yourself.','Name the subject, a diversion and the connection you used to return. This gives you something concrete to compare on another occasion.']
 ],pt:[
 ['Direção voluntária não é uma batalha para não ter outros pensamentos','A distinção prática está entre ser levado pelo que aparece e retornar deliberadamente a um assunto escolhido. Neste curso, perceber um desvio e retornar fazem parte da prática, sem serem motivo para julgar-se incapaz. Um pensamento pode surgir sem determinar toda a sessão.','Escolha um assunto comum e tranquilo fora da preocupação atual. “Vou pensar na forma e no uso daquela ponte de pedestres” oferece algo para retomar. “Não posso pensar no trabalho” mantém o trabalho no centro e não especifica outro assunto.','O que registrar se você percebeu várias distrações?','Registre a ação possível, em vez de emitir um julgamento sobre si.','Nomeie o assunto, um desvio e a ligação usada para retornar. Isso oferece algo concreto para comparar em outra ocasião.']
 ]},
 {id:7,refs:'end of § 28; §§ 29–32',en:[
 ['Separate the source exercise from our checking adaptation','Steiner describes recalling a past encounter and deliberately completing missing parts through imagination. Our object-arrangement exercise adds an immediate check so you can compare your account with something available. It is a learning adaptation, not a word-for-word set of his instructions.','Use three labels: remembered; uncertain; deliberately imagined. For example: “Blue jacket: remembered. Bag: uncertain. Red scarf: imagined for the completed picture.” If you later check a detail, record how you checked it. Do not change the earlier label just because the whole scene now feels familiar.','Does a more vivid completed picture necessarily contain more accurate memories?','Compare vividness with the origin of each detail.','No. It can be vivid because you added imagined details. Accuracy concerns correspondence with the encounter, not only how complete the image feels.'],
 ['Understand a claimed benefit without turning it into a personal deadline','Steiner makes emphatic claims about the improvements repetition will bring. The course does not treat his number of repetitions as a guaranteed schedule for perfect recall. We assess specific observations and revisions, and distinguish his stated expectation from what your record actually shows.','A useful result might be “I now notice the positions of three objects more carefully” or “I still confuse left and right.” Both are more informative than “I have succeeded spiritually” or “I have failed because my pictures are not vivid.” Words and a sketch can support this course’s comparison.','What counts as an honest review if no improvement is clear yet?','Look for a record of what happened, including persistent difficulty.','Say that no clear change is established, describe the difficulty and choose a manageable next attempt. Do not invent progress to match a promised result.']
 ],pt:[
 ['Separe o exercício da fonte da nossa adaptação verificável','Steiner descreve recordar um encontro passado e completar deliberadamente pela imaginação o que falta. Nosso exercício com objetos acrescenta uma verificação imediata, permitindo comparar o relato com algo disponível. É uma adaptação didática, não a reprodução literal das instruções dele.','Use três rótulos: lembrado; incerto; imaginado deliberadamente. Por exemplo: “Jaqueta azul: lembrado. Bolsa: incerto. Cachecol vermelho: imaginado para completar a cena”. Se verificar um detalhe depois, registre como. Não mude o rótulo anterior apenas porque a cena inteira agora parece familiar.','Uma imagem completada mais vívida contém necessariamente mais lembranças corretas?','Compare a vividez com a origem de cada detalhe.','Não. Pode ser vívida porque você acrescentou detalhes imaginados. A precisão envolve a correspondência com o encontro, não apenas a sensação de completude.'],
 ['Compreenda o benefício afirmado sem torná-lo um prazo pessoal','Steiner faz afirmações enfáticas sobre os benefícios da repetição. O curso não trata o número de repetições como prazo garantido para uma memória perfeita. Avaliamos observações e revisões específicas, distinguindo a expectativa afirmada por ele do que seu registro mostra.','Um resultado útil pode ser “Agora noto melhor a posição de três objetos” ou “Ainda confundo esquerda e direita”. Ambos informam mais que “Tive êxito espiritual” ou “Fracassei porque minhas imagens não são vívidas”. Palavras e desenhos podem apoiar a comparação proposta pelo curso.','Como fazer uma revisão honesta se ainda não há melhora clara?','Procure registrar o que aconteceu, inclusive a dificuldade persistente.','Diga que nenhuma mudança clara foi estabelecida, descreva a dificuldade e escolha uma próxima tentativa possível. Não invente progresso para corresponder a uma promessa.']
 ]},
 {id:8,refs:'§§ 33–36',en:[
 ['Compare actions, pause and return','Here the possibilities are courses of action, not just rival explanations of an event. First picture what taking each course would involve. Then set the question aside for a defined interval and return to it. The pause follows preparation; it does not replace it.','Course example: the workshop could keep one large sign or add small labels on each shelf. For each option, consider visibility, clarity and the work required. Write the alternatives before your break, then revisit them the next day if the decision can wait. Note which reasons remain and which you would revise.','Is “I will sleep and hope the answer arrives” the full instruction?','What must be done before the question is set aside?','No. First work through at least two possibilities. On returning, examine them again and give reasons for your choice.'],
 ['Inner necessity and provisional judgment','In the lecture, inner necessity refers to connections belonging to the things and circumstances, rather than merely to personal preference. It does not mean that an intense feeling must be an instruction from the universe. A provisional conclusion is the best-supported conclusion you can presently give while naming what might change it.','After the pause, you might choose shelf labels because newcomers miss the single sign. State what supports that choice and when you will review it. A pressing decision may not allow an overnight wait; our course applies the exercise to an ordinary decision that can wait and uses a definite return time to distinguish pausing from avoidance.','If you feel more certain tomorrow, is that sufficient reason to choose?','Compare the strength of the feeling with the reasons and circumstances.','No. Explain what you now understand better. If only the feeling changed, acknowledge that and revisit the actual alternatives.']
 ],pt:[
 ['Compare ações, faça uma pausa e retorne','Aqui, as possibilidades são formas de agir, não apenas explicações rivais de um acontecimento. Primeiro imagine o que cada ação envolveria. Depois deixe a questão de lado por um intervalo definido e retome-a. A pausa vem após a preparação; não a substitui.','Exemplo do curso: a oficina pode manter uma placa grande ou acrescentar etiquetas pequenas a cada prateleira. Considere visibilidade, clareza e trabalho necessário para cada opção. Escreva as alternativas antes da pausa e retome-as no dia seguinte, se a decisão puder esperar. Registre quais razões permanecem e quais revisaria.','“Vou dormir e esperar a resposta aparecer” é a instrução completa?','O que precisa acontecer antes de deixar a questão de lado?','Não. Primeiro examine pelo menos duas possibilidades. Ao retornar, examine-as novamente e apresente razões para sua escolha.'],
 ['Necessidade interna e juízo provisório','Na palestra, necessidade interna se refere a relações que pertencem às coisas e circunstâncias, em vez de apenas à preferência pessoal. Não significa que uma sensação intensa seja uma instrução do universo. Conclusão provisória é a conclusão mais fundamentada que você pode dar agora, indicando o que poderia mudá-la.','Depois da pausa, você pode escolher etiquetas porque visitantes novos não percebem a placa única. Diga o que sustenta a escolha e quando a revisará. Uma decisão urgente talvez não permita esperar uma noite; nosso curso aplica o exercício a uma decisão comum que pode esperar e define um horário de retorno para distinguir pausa de esquiva.','Sentir mais certeza amanhã basta como razão para escolher?','Compare a intensidade do sentimento com as razões e circunstâncias.','Não. Explique o que compreende melhor agora. Se apenas o sentimento mudou, reconheça isso e retome as alternativas reais.']
 ]},
 {id:9,refs:'§§ 38–48; review §§ 1–36',en:[
 ['Objective thinking does not mean having no feelings','The lecture closes by returning to thought that follows the things. In §§ 42–46 Steiner discusses how feelings and habits can influence the reasons we give. The practical question is whether you can recognize that influence and still examine the matter. Objective here concerns faithfulness to the object or situation, not a claim that you have become infallible.','Course example: you are disappointed that your sign did not help. “I feel disappointed” can be true alongside “the observations do not support my explanation.” Acknowledging the feeling may make it easier to separate it from the conclusion.','Must you stop caring about a result in order to investigate it fairly?','Distinguish having a preference from using it as evidence.','No. You can care while asking whether your reasons fit the observations. Neither disappointment nor enthusiasm decides the factual question.'],
 ['Read the conclusion as well as the exercises','The concluding paragraphs connect the exercises with everyday action. The lecture also contains historical anecdotes, comparisons and arguments about science. Identify which kind of statement you are reading. Understanding the point of an anecdote is different from verifying its historical details; understanding an argument is different from establishing its conclusion.','Use the final audit to explain one observation, one hypothesis, one checked result and one change in your judgment. Then name one claim Steiner makes about spiritual effects and keep it distinct from what your notebook establishes. In § 47 he emphasizes natural processes, while § 28 also offers a book or an ordinary encounter: the examples vary with the exercise.','Does completing the course establish every claim in the lecture?','Ask what your exercises actually provide evidence about.','No. Your records can show aspects of your own practice. Broader historical, philosophical and spiritual claims require their own examination. Read §§ 38–48 so that you can explain the conclusion without confusing these kinds of support.']
 ],pt:[
 ['Pensar objetivamente não significa não ter sentimentos','A palestra termina retomando o pensar que acompanha as coisas. Nos §§ 42–46, Steiner aborda como sentimentos e hábitos influenciam as razões que damos. A questão prática é reconhecer essa influência e ainda examinar o assunto. Objetivo aqui envolve fidelidade ao objeto ou à situação, não a afirmação de que você se tornou infalível.','Exemplo do curso: você está decepcionado porque sua placa não ajudou. “Sinto decepção” pode ser verdadeiro junto com “as observações não apoiam minha explicação”. Reconhecer o sentimento pode ajudar a separá-lo da conclusão.','É necessário deixar de se importar com um resultado para investigá-lo com justiça?','Distinga ter uma preferência de usá-la como evidência.','Não. Você pode se importar e ainda perguntar se suas razões correspondem às observações. Nem decepção nem entusiasmo decidem a questão factual.'],
 ['Leia também a conclusão, além dos exercícios','Os parágrafos finais relacionam os exercícios à ação cotidiana. A palestra também contém relatos históricos, comparações e argumentos sobre ciência. Identifique o tipo de afirmação. Compreender a ideia de um relato difere de verificar seus detalhes históricos; compreender um argumento difere de estabelecer sua conclusão.','Na revisão final, explique uma observação, uma hipótese, um resultado verificado e uma mudança de juízo. Depois nomeie uma afirmação de Steiner sobre efeitos espirituais e distinga-a do que seu caderno estabelece. No § 47 ele enfatiza processos naturais, enquanto o § 28 também oferece um livro ou encontro cotidiano: os exemplos variam conforme o exercício.','Concluir o curso estabelece todas as afirmações da palestra?','Pergunte sobre o que seus exercícios realmente oferecem evidência.','Não. Os registros podem mostrar aspectos de sua prática. Afirmações históricas, filosóficas e espirituais mais amplas exigem exame próprio. Leia os §§ 38–48 para explicar a conclusão sem confundir os tipos de apoio.']
 ]}
];

export const thinkingRoute={
 en:[['I do not yet understand the connection.','Observe and compare successive conditions.',3],['I understand enough to form an expectation.','Predict a later event and check it.',4],['I want to know how a present event arose.','Propose an earlier cause and investigate.',5],['My thoughts are following my current worries.','Choose a subject and practise returning.',6],['My recollection is vague.','Reconstruct details and distinguish their origins.',7],['I must choose between possible actions.','Compare, pause, return and decide with reasons.',8]],
 pt:[['Ainda não compreendo a relação.','Observe e compare estados sucessivos.',3],['Compreendo o suficiente para formar uma expectativa.','Preveja um acontecimento posterior e confira.',4],['Quero saber como surgiu um acontecimento atual.','Proponha uma causa anterior e investigue.',5],['Meus pensamentos seguem as preocupações atuais.','Escolha um assunto e pratique retornar.',6],['Minha recordação é vaga.','Reconstrua detalhes e distinga suas origens.',7],['Preciso escolher entre ações possíveis.','Compare, faça uma pausa, retorne e decida com razões.',8]]
};

export function deepenThinkingLessons(lessons){
 for(const lang of ['en','pt']){
  const pt=lang==='pt';
  for(const entry of thinkingDepth)lessons[entry.id][lang].depth=entry;
  const change=lessons[3][lang];
  change.example=pt?'Na primeira observação, uma folha está dobrada e mostra uma superfície estreita. Na seguinte, está mais aberta. Você não acompanhou o intervalo entre as duas observações.':'At the first observation, a leaf is folded and presents a narrow surface. At the next, it is more open. You did not watch the interval between the observations.';
  change.explanation=pt?'Preserve os dois estados antes de propor uma causa. Compare contorno, posição e superfícies visíveis. Ao relacionar as imagens mentalmente, distinga a mudança observada de uma transição apenas imaginada. Nesta etapa não é necessário explicar por que ocorreu.':'Preserve both states before proposing a cause. Compare outline, position and visible surfaces. As you relate the pictures mentally, distinguish the observed change from an imagined transition. At this stage you do not need to explain why it occurred.';
  change.activity=pt?'Em três ocasiões, observe a mesma planta ou processo natural acessível. Registre horário e três detalhes concretos. Coloque os registros lado a lado e descreva uma mudança, uma continuidade e algo que permanece desconhecido. Não invente etapas intermediárias nem exija de si uma causa. Compare com os §§ 14–18 antes de passar à previsão.':'On three occasions, observe the same plant or accessible natural process. Record the time and three concrete details. Place the records side by side and describe a change, a continuity and something still unknown. Do not invent intermediate stages or require yourself to give a cause. Compare with §§ 14–18 before moving on to prediction.';
  change.question=pt?'Imaginar a transição entre duas observações equivale a tê-la observado?':'Is imagining the transition between two observations the same as having observed it?';
  change.checks=[[change.question,pt?'Não. Preserve os estados observados e identifique a transição como imaginada. A comparação pode ser precisa mesmo sem explicação causal.':'No. Preserve the observed states and identify the transition as imagined. The comparison can be precise even without a causal explanation.']];
  const cause=lessons[5][lang];
  cause.title=pt?'Investigar como algo aconteceu':'Investigate how something happened';
  cause.goal=pt?'Proponha uma causa anterior, procure evidência e revise sua explicação.':'Propose an earlier cause, seek evidence and revise your explanation.';
  cause.example=pt?'Ontem havia seis lápis na bandeja; hoje há quatro. Você imagina que dois foram emprestados, mas ainda não verificou.':'Yesterday the tray held six pencils; today it holds four. You imagine that two were borrowed, but have not checked.';
  cause.explanation=pt?'A contagem é uma observação; o empréstimo é uma hipótese. Procure um registro, confira os locais pertinentes ou pergunte de forma neutra a quem possa saber. Se encontrar os lápis em outra gaveta, revise a história de empréstimo. Se faltar evidência, explique por que a causa continua em aberto.':'The count is an observation; borrowing is a hypothesis. Look for a record, check relevant locations or ask someone who may know a neutral question. If you find the pencils in another drawer, revise the borrowing story. If evidence is missing, explain why the cause remains open.';
  cause.activity=pt?'Em três ocasiões, escolha um pequeno acontecimento verificável de sua rotina. Registre o que sabe, uma causa possível, outra possibilidade e uma verificação capaz de distingui-las. Faça a verificação disponível e registre o resultado antes de revisar. Não transforme uma hipótese sobre alguém em acusação; mantenha a pergunta em aberto quando não houver evidência.':'On three occasions, choose a small, checkable event from your routine. Record what you know, one possible cause, another possibility and a check that could distinguish them. Make the available check and record the result before revising. Do not turn a hypothesis about someone into an accusation; keep the question open when evidence is unavailable.';
  cause.takeaway=cause.goal;
  cause.question=pt?'O que ainda falta depois de imaginar uma causa coerente?':'What is still missing after imagining a coherent cause?';
  cause.checks=[[cause.question,pt?'Evidência sobre o que realmente aconteceu. Uma narrativa coerente pode ser falsa; a verificação permite corrigi-la ou manter a incerteza.':'Evidence about what actually happened. A coherent story can be false; checking lets you correct it or retain uncertainty.']];
  const decision=lessons[8][lang];
  decision.title=pt?'Comparar, pausar e decidir':'Compare, pause and decide';
  decision.goal=pt?'Examine ações alternativas, deixe a questão repousar e retome-a com razões para uma escolha provisória.':'Examine alternative actions, set the question aside and return with reasons for a provisional choice.';
  decision.example=pt?'A oficina pode manter uma placa grande ou colocar etiquetas nas prateleiras. Você prefere a placa, mas ainda não examinou o que cada opção exige. A escolha pode esperar até amanhã.':'The workshop can keep one large sign or put labels on the shelves. You prefer the sign but have not examined what each option involves. The choice can wait until tomorrow.';
  decision.explanation=pt?'Escreva o que cada ação envolveria, o que a apoia e o que permanece incerto. Defina quando retomará a questão e faça a pausa. Ao retornar, compare novamente e registre a razão da escolha e uma condição para revê-la. Assim, pausar não significa deixar de preparar a decisão.':'Write what each action would involve, what supports it and what remains uncertain. Set a time to return and take the pause. On returning, compare again and record your reason for choosing and a condition for review. Pausing thus follows preparation of the decision.';
  decision.activity=pt?'Use três entradas: 1) apresente duas ações possíveis para uma decisão comum que pode esperar, com razões e consequências; 2) após uma pausa definida, retome e registre o que mudou na avaliação; 3) depois da ação, examine o resultado e diga se revisaria a escolha. Os três momentos são uma organização didática do curso. Não adie uma decisão urgente apenas para cumprir o exercício.':'Use three entries: 1) set out two possible actions for an ordinary decision that can wait, with reasons and consequences; 2) after a defined pause, return and record what changed in your assessment; 3) after acting, examine the outcome and say whether you would revise the choice. These three moments are the course’s teaching structure. Do not delay an urgent decision just to fulfil the exercise.';
  decision.takeaway=pt?'Prepare a comparação antes da pausa; ao retornar, decida com razões e reconheça os limites.':'Prepare the comparison before the pause; on returning, decide with reasons and acknowledge the limits.';
  decision.reading=pt?'Parágrafos 33–36; compare o exemplo de causa e efeito no § 38.':'Paragraphs 33–36; compare the cause-and-effect example in § 38.';
  decision.question=pt?'O que distingue pausar uma decisão de simplesmente evitá-la?':'What distinguishes pausing a decision from simply avoiding it?';
  decision.checks=[[decision.question,pt?'Você prepara alternativas e razões, define um momento de retorno e retoma a avaliação. Evitar não inclui necessariamente essas etapas.':'You prepare alternatives and reasons, set a return time and resume the assessment. Avoidance need not include those steps.']];
  const review=lessons[9][lang];
  review.reading=pt?'Parágrafos 38–48 para a conclusão; retome os §§ 1–36 para os exercícios.':'Paragraphs 38–48 for the conclusion; revisit §§ 1–36 for the exercises.';
  review.activity=pt?'Reúna registros anteriores. Identifique uma observação, uma hipótese, uma verificação e uma revisão. Compare uma entrada inicial e outra posterior de dificuldade semelhante; diga o que melhorou e o que continua difícil. Escolha no mapa do curso o exercício adequado à dificuldade e registre por quê. Faça mais três tentativas breves e relate o resultado sem presumir melhora. Explique também uma afirmação espiritual da palestra que esses registros, sozinhos, não estabelecem.':'Gather earlier entries. Identify an observation, a hypothesis, a check and a revision. Compare an early and a later entry of similar difficulty; state what improved and what remains difficult. Choose the exercise matching that difficulty from the course map and explain why. Make three more short attempts and report the result without presuming improvement. Also explain one spiritual claim from the lecture that these records alone do not establish.';
 }
}
