// Original bilingual teaching grounded in targeted readings. Not source quotations.
export const clarifications = {};
export const bookChecks = {
 2:{en:{question:'Why can “etheric body” be misunderstood?',options:['It means a second material object.','It names life organization, using “body” in a special sense.','It means the old light-transmitting ether of physics.'],answer:1,reasons:['Steiner warns against giving this body a physical bodily nature.','This distinguishes the organization described from material anatomy.','The book explicitly distinguishes its use of “etheric” from that physical theory.']},pt:{question:'Por que “corpo etérico” pode ser mal compreendido?',options:['Significa outro objeto material.','Designa a organização vital, usando “corpo” num sentido especial.','Significa o antigo éter transmissor da luz da física.'],answer:1,reasons:['Steiner adverte contra atribuir a esse corpo uma natureza corporal física.','A resposta distingue a organização descrita da anatomia material.','O livro distingue expressamente seu uso de “etérico” daquela teoria física.']}},
 9:{en:{question:'What does checking The Book of the Bee establish?',options:['The medieval compilation contains the prophecy Brian discusses.','An eyewitness recorded the ancient conversation.','The fourteen incarnations have been independently proved.'],answer:0,reasons:['The passage can be located and attributed to this transmitted Christian text.','The medieval compilation is not an ancient eyewitness record.','The passage does not supply or prove Welburn’s separate proposal.']},pt:{question:'O que a conferência do Livro da Abelha estabelece?',options:['A compilação medieval contém a profecia discutida por Brian.','Uma testemunha registrou a conversa antiga.','As catorze encarnações foram provadas independentemente.'],answer:0,reasons:['A passagem pode ser localizada e atribuída ao texto cristão transmitido.','A compilação medieval não é registro antigo de uma testemunha.','A passagem não fornece nem prova a proposta separada de Welburn.']}},
 12:{en:{question:'Why does the account still need the Nathan preparation?',options:['Matthew has no bodily preparation.','The children are each half a physical person.','It contributes a specially prepared soul organization to the convergence.'],answer:2,reasons:['The genealogy is explicitly interpreted as bodily preparation.','The emphases do not divide a human body into two incomplete children.','Steiner distinguishes this contribution from the Solomon physical/etheric preparation.']},pt:{question:'Por que o relato ainda precisa da preparação natânica?',options:['Mateus não apresenta preparação corporal.','Cada menino é metade de uma pessoa física.','Ela contribui com uma organização anímica especialmente preparada.'],answer:2,reasons:['A genealogia é interpretada expressamente como preparação corporal.','As ênfases não dividem um corpo humano em dois meninos incompletos.','Steiner distingue essa contribuição da preparação física e etérica salomônica.']}},
 15:{en:{question:'How does the newly checked GA 131 passage describe Buddha’s role?',options:['Buddha replaces Zarathustra at the Temple.','Spiritual forces work in the Nathan child’s astral organization.','Buddha is another infant in the same manger.'],answer:1,reasons:['The Temple transfer concerns Zarathustra’s individuality.','Lecture VIII describes this influence from the spiritual world.','The passage describes a spiritual influence, not another physical birth.']},pt:{question:'Como a passagem conferida da GA 131 descreve Buda?',options:['Buda substitui Zaratustra no Templo.','Forças espirituais atuam na organização astral do menino natânico.','Buda é outro bebê na mesma manjedoura.'],answer:1,reasons:['A transferência no Templo concerne à individualidade de Zaratustra.','A palestra VIII descreve essa influência a partir do mundo espiritual.','A passagem descreve influência espiritual, não outro nascimento físico.']}},
 19:{en:{question:'What makes the Essene-gate question decisive in this account?',options:['It asks where the excluded powers go and who bears the cost.','It proves every community practice is worthless.','It supplies an exact map of Jesus’s journeys.'],answer:0,reasons:['The issue widens from protected purity to the condition of people outside it.','The account also recognizes the gifts and seriousness of the discipline.','Steiner explicitly leaves the altar’s precise location uncertain.']},pt:{question:'O que torna decisiva a pergunta dos portões essênios?',options:['Pergunta para onde vão as forças afastadas e quem suporta o custo.','Prova que toda prática comunitária é inútil.','Fornece um mapa exato das viagens de Jesus.'],answer:0,reasons:['A questão passa da pureza protegida à condição de quem fica fora.','O relato também reconhece os dons e a seriedade da disciplina.','Steiner deixa expressamente incerto o local exato do altar.']}},
 20:{en:{question:'Does Steiner’s passage about the two mothers establish Heavenly Eve?',options:['Yes, the names make both claims identical.','Yes, it is stated explicitly in Luke.','No; that relationship and Brian’s conjecture are distinct claims.'],answer:2,reasons:['Similar participants do not make two spiritual identifications the same claim.','Luke does not explicitly state either this transformation or that identification.','The supplied Fifth Gospel describes the mother relationship; Brian separately marks Heavenly Eve as conjecture.']},pt:{question:'A passagem de Steiner sobre as duas mães estabelece Eva celeste?',options:['Sim, os nomes tornam as afirmações idênticas.','Sim, Lucas afirma isso expressamente.','Não; essa relação e a conjectura de Brian são propostas distintas.'],answer:2,reasons:['Participantes semelhantes não tornam idênticas duas identificações espirituais.','Lucas não afirma explicitamente essa transformação nem aquela identificação.','O Quinto Evangelho descreve a relação das mães; Brian apresenta Eva celeste separadamente como conjectura.']}},
 22:{en:{question:'What does “phantom” mean in this reading of GA 131?',options:['The etheric body under another name.','The spiritual formative organization of the physical body.','A frightening ghost detached from the body.'],answer:1,reasons:['The physical form-organization and etheric life-organization remain distinct concepts.','Lecture VI distinguishes it from the substances filling the bodily form.','This specialized term concerns bodily form, not an ordinary apparition.']},pt:{question:'O que significa “fantoma” nesta leitura da GA 131?',options:['O corpo etérico com outro nome.','A organização espiritual formativa do corpo físico.','Um fantasma assustador separado do corpo.'],answer:1,reasons:['Organização da forma física e organização vital etérica continuam distintas.','A palestra VI o distingue das substâncias que preenchem a forma corporal.','O termo especializado concerne à forma corporal, não a uma aparição comum.']}}
};
function add(number,resources,enTitle,ptTitle,en,pt) {
 clarifications[number]={resources,en:{title:enTitle,paragraphs:en.split('\n\n')},pt:{title:ptTitle,paragraphs:pt.split('\n\n')}};
}
add(1,['ga8','ga123'],'Why preparation is more than learning a doctrine','Por que preparar é mais que aprender uma doutrina',
`In Christianity as Mystical Fact, Steiner uses “Mysteries” for communities in which a person was prepared for a transformation of perception and life. The term does not simply mean an unsolved puzzle. His argument concerns becoming capable of receiving and living a spiritual reality, rather than accumulating statements about it. This helps explain why Brian spends so much time on capacities, biography and relationship before reaching the Jordan.

The Matthew lectures make the preparation especially concrete within Steiner’s spiritual account. A bodily organization must be suitable for the individuality working through it; that individuality must develop capacities it can later offer. “Suitable” concerns a particular task in this narrative. It is not a measure of one person’s human worth against another’s.

Keep three questions beside the story: what organization is prepared, which individuality develops through it, and which being ultimately enters? Their answers are not interchangeable. Zarathustra’s work in Jesus prepares the human bearer; the Christ entry at the Jordan is the next event. Understanding a doctrine and undergoing the spiritual transformation it describes also remain different. This course aims at understanding, without claiming that reading its lessons constitutes initiation.`,
`Em O Cristianismo como fato místico, Steiner usa “Mistérios” para comunidades nas quais alguém era preparado para transformar a percepção e a vida. O termo não significa apenas um enigma sem solução. Seu argumento trata de tornar-se capaz de receber e viver uma realidade espiritual, além de acumular afirmações sobre ela. Isso ajuda a compreender por que Brian dedica tanto tempo às capacidades, à biografia e às relações antes do Jordão.

As palestras sobre Mateus tornam a preparação mais concreta no relato espiritual de Steiner. Uma organização corporal precisa ser adequada à individualidade que atua através dela; essa individualidade desenvolve capacidades que depois poderá oferecer. “Adequada” concerne a uma tarefa específica na narrativa. Não mede o valor humano de uma pessoa em comparação com outra.

Conserve três perguntas: que organização é preparada, qual individualidade se desenvolve através dela e qual ser finalmente entra? As respostas não são intercambiáveis. O trabalho de Zaratustra em Jesus prepara o portador humano; a entrada do Cristo no Jordão é outro acontecimento. Compreender uma doutrina também difere de passar pela transformação espiritual descrita. Este curso busca compreensão, sem afirmar que ler suas lições constitui iniciação.`);
add(2,['ga13','ga131'],'“Body” names an organization; “I” names individuality','“Corpo” designa uma organização; “Eu”, a individualidade',
`Occult Science explicitly warns that “etheric” is not the light-transmitting ether once proposed in physics. It also explains that “body” need not mean a second object with material edges. Etheric and astral name different kinds of organization: sustaining life and enabling conscious experience. That is why drawing four stacked boxes can help you learn the vocabulary while misleading you if taken literally.

The distinction between conscious feeling and I-consciousness is equally useful. Pain, pleasure and desire belong to experienced soul life. The I names the individuality that can relate present experience to its own enduring life and work upon its responses. Steiner’s translations also use “Ego”; here it means this individuality, not simply arrogance. A person who remembers yesterday’s anger and decides to respond differently gives an everyday illustration of the distinction, not a demonstration of a supersensible body.

From Jesus to Christ adds a further distinction: the visible living human being is already a cooperation of members. “Physical body” can concern organizing form as well as the substances taken into it. Keep this in mind when later lessons speak of preparing bodily sheaths. They are distinguishing functions within the spiritual account, not describing detachable anatomical containers.`,
`Ciência Oculta adverte expressamente que “etérico” não significa o éter transmissor da luz outrora proposto na física. Explica também que “corpo” não precisa designar um segundo objeto com contornos materiais. Etérico e astral nomeiam organizações diferentes: sustentar a vida e possibilitar a experiência consciente. Quatro caixas ajudam a aprender o vocabulário, mas podem enganar quando tomadas literalmente.

A distinção entre sentimento consciente e consciência do Eu também ajuda. Dor, prazer e desejo pertencem à vida anímica vivida. O Eu designa a individualidade capaz de relacionar a experiência presente à continuidade de sua vida e trabalhar sobre as respostas. Traduções de Steiner também usam “Ego”; aqui significa essa individualidade, não apenas arrogância. Recordar a raiva de ontem e escolher outra resposta ilustra a distinção cotidiana, sem demonstrar um corpo suprassensível.

De Jesus a Cristo acrescenta outra diferença: o ser humano vivo e visível já resulta da cooperação dos membros. “Corpo físico” pode concernir à forma organizadora, além das substâncias que a preenchem. Lembre disso quando as próximas lições falarem de envoltórios corporais preparados. Elas distinguem funções no relato espiritual, sem descrever recipientes anatômicos destacáveis.`);
add(3,['ga103','ga8'],'What “Logos” adds to John’s opening','O que “Logos” acrescenta à abertura de João',
`In the first lecture on John, Steiner reads Logos as a creative spiritual principle through which the world comes into being. “Word” here is more than a sound, a sentence or advice spoken by a teacher. John’s movement from the Word “in the beginning” to the Word becoming flesh connects cosmic origin with human life. This is why Brian’s summary of John begins with wisdom and a cosmic relationship rather than a genealogy.

This does not make John purely intellectual. “Life”, “light” and “dwelling among us” connect the origin to an encounter. Nor does it mean the other Gospels lack a relationship to Logos: Steiner points to Luke’s opening reference to witnesses and servants of the word. The emphasis map selects a foreground; it does not assign exclusive ownership of a spiritual capacity.

Christianity as Mystical Fact offers another interpretive frame: Gospel writers express the Christ event through different Mystery traditions. Keep that proposal identifiable as Steiner’s reading. A comparison of viewpoints can help a reader understand why accounts differ, but it does not by itself settle historical authorship or prove the two-child account.`,
`Na primeira palestra sobre João, Steiner lê Logos como princípio espiritual criador pelo qual o mundo vem a existir. “Verbo” significa mais que um som, uma frase ou um conselho pronunciado por um mestre. A passagem do Verbo “no princípio” ao Verbo feito carne relaciona origem cósmica e vida humana. Por isso, a síntese de Brian começa pela sabedoria e pela relação cósmica, em vez de uma genealogia.

Isso não torna João puramente intelectual. “Vida”, “luz” e “habitar entre nós” relacionam a origem a um encontro. Também não significa que os demais Evangelhos não tenham relação com Logos: Steiner aponta a referência inicial de Lucas às testemunhas e aos servidores da palavra. O mapa das ênfases destaca um primeiro plano; não atribui posse exclusiva de uma capacidade espiritual.

O Cristianismo como fato místico oferece outro quadro interpretativo: os evangelistas expressam o acontecimento do Cristo através de tradições distintas dos Mistérios. Identifique essa proposta como leitura de Steiner. Comparar perspectivas ajuda a compreender diferenças, mas não resolve por si só a autoria histórica nem prova o relato dos dois meninos.`);
add(6,['ga13'],'How to read a spiritual-development map','Como ler um mapa do desenvolvimento espiritual',
`Chapter IV of Occult Science explains the kind of account being offered before describing the stages. Steiner says material events express spiritual processes and describes an Akashic record accessible to spiritual perception. Reading a stage name therefore means entering that proposed framework. It does not turn the name into a physical planet visited by a spacecraft or a period dated from rocks.

Try two separate questions: at what scale is the term being used, and what capacity is being developed? “Earth” is the broad cosmic condition in this map; “Atlantean” is an epoch within it; a post-Atlantean cultural period belongs at a further level. Physical, etheric, astral and I describe aspects of the human organization developing through the account. A scale label and a capacity label do different work.

The book distinguishes investigating supersensible events from understanding a communicated account through thought. A beginner can follow the relationships without claiming to perceive the Akashic record. Returning to those relationships is more useful here than attaching exact dates to every stage: the course needs the history of the prepared instrument, not a compressed catalogue of all cosmology.`,
`O capítulo IV de Ciência Oculta explica o tipo de relato proposto antes de descrever os estágios. Steiner diz que acontecimentos materiais expressam processos espirituais e apresenta um registro akáshico acessível à percepção espiritual. Ler o nome de um estágio significa entrar nesse quadro proposto. Não transforma o nome num planeta visitável por uma nave ou num período datado pelas rochas.

Faça duas perguntas separadas: em que escala o termo é usado e que capacidade está se desenvolvendo? “Terra” designa a condição cósmica ampla; “atlântica”, uma época dentro dela; um período cultural pós-atlântico ocupa outro nível. Físico, etérico, astral e Eu descrevem aspectos da organização humana que se desenvolvem no relato. Nomear uma escala e nomear uma capacidade cumprem funções diferentes.

O livro distingue investigar acontecimentos suprassensíveis de compreender pelo pensamento um relato comunicado. Quem começa pode acompanhar as relações sem alegar percepção do registro akáshico. Retornar a essas relações ajuda mais que atribuir datas exatas a cada estágio: o curso precisa da história do instrumento preparado, não de um catálogo resumido de toda a cosmologia.`);
add(8,['ga11'],'Remembering an image and comparing experiences','Recordar uma imagem e comparar experiências',
`Cosmic Memory gives a more developed account of the distinction Brian compresses. In “Our Atlantean Ancestors”, Steiner describes an early mode of acting through powerful recollection of similar situations, followed by an ability to compare experiences, calculate and judge. Language is connected with retaining what has been experienced so that it can be named and communicated.

The conceptual distinction is useful even without accepting the spiritual chronology. Remembering that a particular route was safe yesterday is different from comparing yesterday’s conditions with today’s flooding. A vivid memory may help, but a changed situation asks for judgment. Thought does not eliminate memory: it uses remembered material in a new relationship.

This edition uses early twentieth-century “race” categories and also makes hierarchical claims about peoples. Those are genuine features of the source, rather than neutral names the course silently endorses. We use the passage to clarify its memory-to-judgment argument, not to teach those claims as established anthropology or to classify living people. The everyday example establishes a distinction between mental acts; it cannot establish the account of Atlantis.`,
`Memória Cósmica desenvolve a distinção que Brian resume. Em “Nossos antepassados atlantes”, Steiner descreve uma forma inicial de agir pela recordação intensa de situações semelhantes, seguida pela capacidade de comparar experiências, calcular e julgar. A linguagem é relacionada à retenção do vivido, permitindo nomeá-lo e comunicá-lo.

A distinção conceitual ajuda mesmo sem aceitar a cronologia espiritual. Recordar que um caminho estava seguro ontem difere de comparar aquelas condições com uma inundação de hoje. Uma memória viva ajuda, mas uma situação modificada exige julgamento. O pensamento não elimina a memória: utiliza seu conteúdo numa relação nova.

A edição emprega categorias de “raça” do início do século XX e também formula hierarquias entre povos. São características reais da fonte, não nomes neutros que o curso endossa silenciosamente. Usamos a passagem para esclarecer seu argumento sobre memória e julgamento, sem ensinar aquelas afirmações como antropologia estabelecida ou classificar pessoas vivas. O exemplo cotidiano esclarece atos mentais diferentes; não estabelece o relato de Atlântida.`);
add(9,['bee'],'A prophecy, its transmission and its interpretation','Uma profecia, sua transmissão e sua interpretação',
`The supplied Book of the Bee lets us check the actual passage Brian reads. Chapter 37 attributes a prophecy to Zârâdôsht: a coming child, suffering, a heavenly sign and emissaries bearing offerings. These motifs explain why Brian connects the passage with the Magi and preparation. However, a text preserving a prediction and an independent record proving that prediction was spoken are different kinds of evidence.

The preface identifies the compiler as Solomon of Akhlat, a Christian bishop associated with the thirteenth century. Budge is the later editor and English translator. The chapter itself also identifies its Zârâdôsht with Baruch the scribe. That feature belongs to the compilation’s own Christian tradition; it should not be silently treated as a straightforward identification of the historical Persian teacher.

There are therefore three layers: the medieval text, its inherited prophecy tradition, and Brian’s anthroposophical interpretation through Zarathustra. The passage can illuminate what Brian means by expectation and a school watching for signs. It cannot, by itself, establish an unbroken historical school or prove the spiritual incarnation sequence. Keep Welburn’s separate fourteen-incarnation proposal separate as well.`,
`O Livro da Abelha fornecido permite conferir a passagem lida por Brian. O capítulo 37 atribui a Zârâdôsht uma profecia: uma criança futura, sofrimento, um sinal celeste e enviados levando oferendas. Esses temas esclarecem sua relação com os magos e a preparação. Entretanto, preservar uma previsão num texto e provar independentemente que ela foi pronunciada são tipos diferentes de evidência.

O prefácio identifica o compilador como Salomão de Akhlat, bispo cristão ligado ao século XIII. Budge é o editor e tradutor inglês posterior. O próprio capítulo identifica seu Zârâdôsht com Baruc, o escriba. Isso pertence à tradição cristã da compilação; não deve ser tratado silenciosamente como identificação simples do mestre persa histórico.

Temos três camadas: texto medieval, tradição profética transmitida e interpretação antroposófica de Brian através de Zaratustra. A passagem esclarece o sentido da expectativa e de uma escola atenta aos sinais. Sozinha, não estabelece uma escola histórica ininterrupta nem prova a sequência de encarnações espirituais. Mantenha também separada a proposta de Welburn sobre catorze encarnações.`);
add(10,['ga123'],'Why a spiritual gift is not ordinary inheritance','Por que um dom espiritual difere da herança comum',
`Lecture VII of Matthew recalls two gifts before describing a third: Zarathustra’s astral body to Hermes and etheric body to Moses, followed much later by his offering of the prepared human organism to Christ. This provides a clear thread through Brian’s many geographical and personal names. In the account, cultivated capacities become available for another spiritual task.

That thread is different from the genealogy beginning with Abraham. Genealogy concerns a succession of human generations and the bodily preparation attributed to it. The gifts to Hermes and Moses concern a claimed spiritual transmission across individualities. Calling both “inheritance” without qualification can make them sound like the same process, although Steiner distinguishes their participants and means.

When the story returns to Egypt, ask which kind of relationship is being discussed: a journey narrated in Matthew, earlier teaching associated with Hermes, or an interpretation of renewed connection with Zarathustra’s work. A region is a setting for these relationships, not proof of them. The preparation narrative becomes clearer when the source’s spiritual continuity is explained alongside the separate journeys, rather than replacing their immediate human reasons.`,
`A palestra VII sobre Mateus recorda dois dons antes de descrever um terceiro: o corpo astral de Zaratustra a Hermes e o etérico a Moisés, seguidos, muito depois, da oferta do organismo humano preparado ao Cristo. Isso oferece um fio claro através dos muitos nomes e lugares citados por Brian. No relato, capacidades cultivadas tornam-se disponíveis para outra tarefa espiritual.

Esse fio difere da genealogia iniciada em Abraão. A genealogia concerne à sucessão de gerações humanas e à preparação corporal atribuída a ela. Os dons a Hermes e Moisés concernem a uma transmissão espiritual proposta entre individualidades. Chamar ambos de “herança” sem qualificação pode fazê-los parecer o mesmo processo, embora Steiner distinga participantes e meios.

Ao retornar ao Egito, pergunte qual relação está em questão: viagem narrada por Mateus, ensinamento anterior relacionado a Hermes ou interpretação da reconexão com o trabalho de Zaratustra. Uma região oferece o cenário dessas relações, não sua prova. A narrativa fica mais clara ao explicar a continuidade espiritual ao lado das viagens distintas, preservando seus motivos humanos imediatos.`);
add(11,['ga123'],'Thinking about the divine through an earthly instrument','Pensar o divino através de um instrumento terreno',
`In Matthew lecture III, Steiner’s portrait of Abraham concerns a bodily instrument for thinking. The contrast is between receiving divine knowledge through an older clairvoyant mode and forming thoughts of the divine while embodied. Outward observation is therefore not presented simply as a loss of spirituality. It can become a different way of approaching meaning.

Steiner also qualifies the description of Abraham as an inventor of arithmetic: it should not be taken too literally. That qualification helps us read Brian’s compressed expression “first modern thinker”. The passage explains a proposed spiritual transition; it is not a documented account of who first counted, measured land or invented mathematics.

Follow the causal sequence within the interpretation: a capacity needs an instrument, the instrument is associated with a bodily lineage, and preparation across generations makes it usable for Zarathustra’s task. The spiritual individuality is still distinct from the lineage. In ordinary practice, the useful connection is between observation and a thought you can explain: what did you notice, what relationship did you infer, and what would make you revise that inference?`,
`Na palestra III sobre Mateus, o retrato de Abraão concerne a um instrumento corporal para pensar. Steiner contrasta o conhecimento divino recebido por uma antiga percepção clarividente com a formação de pensamentos sobre o divino durante a vida encarnada. Observar o exterior não aparece simplesmente como perda da espiritualidade. Pode tornar-se outra via de aproximação ao sentido.

Steiner também qualifica a descrição de Abraão como inventor da aritmética: não deve ser tomada literalmente demais. Essa ressalva esclarece a expressão resumida de Brian, “primeiro pensador moderno”. A passagem explica uma transição espiritual proposta; não documenta quem primeiro contou, mediu terras ou inventou a matemática.

Acompanhe a sequência interpretativa: uma capacidade precisa de um instrumento, este é relacionado a uma linhagem corporal e a preparação entre gerações o torna utilizável na tarefa de Zaratustra. A individualidade espiritual continua distinta da linhagem. Na prática cotidiana, a ligação útil é entre observação e pensamento explicável: o que percebeu, que relação inferiu e o que faria rever a conclusão?`);
add(12,['ga123'],'Forty-two generations and two complementary preparations','Quarenta e duas gerações e duas preparações complementares',
`Matthew lecture III develops the three groups of fourteen as a preparation of physical, etheric and astral sheaths. It compares this with developmental periods in an individual life and proposes a pattern in which alternate generations carry particular inherited qualities. These are parts of Steiner’s spiritual explanation. Matthew 1:17 supplies the threefold grouping; it does not itself teach the fourfold human being or a law of hereditary transmission.

Lecture VI then makes a distinction that a simple table can conceal. Although all three sheaths are involved in the genealogy, the Solomon preparation is emphasized as providing the physical and etheric instrument through which Zarathustra develops. The Nathan preparation provides the specially prepared astral organization and I-bearer for the next phase. This is why two streams are needed in the account, even after the long genealogy has prepared the first.

Avoid turning these emphases into two incomplete people: both children have human bodily lives in the narrative. What differs is the preparation and the capacities brought into the eventual convergence. A useful explanation can name the genealogical pattern, then state what it prepares, and finally explain why the Temple event adds something it has not supplied by itself.`,
`A palestra III sobre Mateus desenvolve os três grupos de catorze como preparação dos envoltórios físico, etérico e astral. Compara isso aos períodos de uma biografia e propõe um padrão de transmissão de certas qualidades por gerações alternadas. São elementos da explicação espiritual de Steiner. Mateus 1:17 fornece a divisão tríplice; não ensina, por si, os quatro membros humanos nem uma lei hereditária.

A palestra VI faz uma distinção que uma tabela simples pode esconder. Embora os três envoltórios participem da genealogia, a preparação salomônica é destacada por fornecer o instrumento físico e etérico através do qual Zaratustra se desenvolve. A natânica oferece a organização astral e o portador do Eu especialmente preparados para a etapa seguinte. Por isso, o relato precisa de duas correntes, mesmo depois da longa genealogia.

Não transforme essas ênfases em duas pessoas incompletas: os dois meninos têm vida corporal humana na narrativa. Diferem a preparação e as capacidades trazidas à convergência. Uma boa explicação nomeia o padrão genealógico, diz o que prepara e mostra por que o acontecimento do Templo acrescenta algo que ele não oferece sozinho.`);
add(13,['ga131','ga148'],'Preserved openness is not a lack of human worth','Abertura preservada não significa falta de valor humano',
`From Jesus to Christ describes the Nathan child’s unusual contrast: little aptitude for the products of earthly learning alongside an immense capacity for love and self-giving. Steiner expressly says the first description is not a depreciation. The point is a kind of preparation, not a verdict that the child is less human or that love is a substitute for all learning.

The Fifth Gospel later looks back at the child’s life before twelve through Jesus’s own remembered warmth and openness to nature. After the Temple change, learned wisdom becomes available, but the account also describes the sorrow that comes with understanding human distress. Openness and acquired knowledge are not simply two quantities added together. Their meeting changes what can be understood and experienced.

John the Baptist remains another participant. Relating him spiritually to the Nathan being does not mean John becomes the child or enters the body at the Temple. Likewise, a passage about the two mothers at the Jordan does not establish Brian’s Heavenly Eve conjecture. A preserved soul, an earthly individuality, a family relationship and a suggested symbolic identity must each be explained on their own terms.`,
`De Jesus a Cristo descreve o contraste incomum do menino natânico: pouca aptidão para os produtos do aprendizado terreno e imensa capacidade de amor e entrega. Steiner diz expressamente que a primeira descrição não o deprecia. Trata-se de um tipo de preparação, não de julgá-lo menos humano ou de substituir todo aprendizado pelo amor.

O Quinto Evangelho retorna à vida anterior aos doze anos pela lembrança de Jesus de seu calor e abertura à natureza. Após a mudança no Templo, a sabedoria adquirida torna-se disponível, mas o relato também descreve a tristeza de compreender o sofrimento humano. Abertura e conhecimento não são apenas duas quantidades somadas. Seu encontro modifica o que pode ser compreendido e vivido.

João Batista continua sendo outro participante. Relacioná-lo espiritualmente ao ser natânico não significa que João se torne o menino ou entre no corpo no Templo. Uma passagem sobre as duas mães no Jordão tampouco estabelece a conjectura de Brian sobre Eva celeste. Alma preservada, individualidade terrena, relação familiar e identidade simbólica sugerida precisam ser explicadas separadamente.`);
add(15,['ga131'],'Buddha’s influence is not another child or another transfer','A influência de Buda não é outro menino nem outra transferência',
`The opening of lecture VIII in From Jesus to Christ gives a direct source for the distinction. Steiner says forces acquired by the Bodhisattva who became Gautama Buddha work in the Nathan child’s astral body. He presents Buddha as active from the spiritual world after the earthly life associated with his attainment of Buddhahood. That is a claimed spiritual influence, rather than a second physical birth as Jesus.

Compare the roles: Buddha’s forces are related to the soul organization and compassion; Zarathustra’s individuality enters at the Temple; Christ enters the prepared human bearer at the Jordan. If all three are described loosely as “entering Jesus”, the sequence becomes confused. Specifying the kind of influence and its place in the narrative restores the difference.

This newly checked passage supports the Buddha/Nathan relationship. It does not independently verify the specific Asita/Simeon identification, which remains credited to the supplied GA 114 research dossier. Luke’s presentation scene and the anthroposophical explanation should still be distinguished. The aim is to understand what each participant contributes, not to recast Buddhist teaching as though its practitioners all endorsed this Christian interpretation.`,
`O início da palestra VIII de De Jesus a Cristo oferece uma fonte direta para a distinção. Steiner diz que forças adquiridas pelo bodisatva que se tornou Gautama Buda atuam no corpo astral do menino natânico. Apresenta Buda como atuante a partir do mundo espiritual após a vida terrena relacionada à condição de Buda. Trata-se de uma influência espiritual proposta, não de um segundo nascimento físico como Jesus.

Compare as funções: as forças de Buda relacionam-se à organização anímica e à compaixão; a individualidade de Zaratustra entra no Templo; o Cristo entra no portador humano preparado no Jordão. Descrever os três vagamente como “entrando em Jesus” confunde a sequência. Especificar o tipo de influência e seu lugar no relato restaura a diferença.

A passagem agora conferida apoia a relação Buda/natânico. Não verifica independentemente a identificação específica de Asita/Simeão, ainda atribuída ao dossiê fornecido sobre a GA 114. A apresentação narrada por Lucas continua distinta da explicação antroposófica. Buscamos compreender a contribuição de cada participante, sem apresentar o ensino budista como se seus praticantes endossassem essa interpretação cristã.`);
add(17,['ga123','ga148'],'An Essene connection does not establish formal membership','Uma relação com os essênios não estabelece filiação formal',
`Matthew lecture VI connects Nazareth with Netzer and an Essene colony. The Fifth Gospel describes an Essene settlement within Jesus’s surroundings and a later exchange with learned members. Both passages belong to Steiner’s spiritual account; finding them in the supplied books establishes the attribution, not archaeological confirmation of the town’s origin.

The Fifth Gospel makes a particularly helpful qualification: Jesus is received into the community as an outside associate, without the ordinary lower tests, and Steiner declines to call this entry into the Order itself. Knowing teachings, meeting members and living under a formal rule are different relationships. The later criticism of the protected community should therefore not be summarized as a documented resignation from an order he is known to have joined.

Family labels remain important too. The conversation before the Jordan is with the surviving mother in the joined household. Luke’s earlier visitation and the Temple search concern different moments in the narrative. Before connecting community and spiritual preparation, identify whose relationship is being described and at which stage of life. That small habit prevents several apparently mysterious contradictions.`,
`A palestra VI sobre Mateus relaciona Nazaré a Netzer e a uma colônia essênia. O Quinto Evangelho descreve um núcleo essênio no ambiente de Jesus e o intercâmbio posterior com membros instruídos. As duas passagens pertencem ao relato espiritual de Steiner; encontrá-las nos livros confirma a atribuição, não a origem arqueológica da cidade.

O Quinto Evangelho faz uma qualificação útil: Jesus é recebido na comunidade como associado externo, sem os testes inferiores habituais, e Steiner evita chamar isso de entrada na Ordem propriamente dita. Conhecer ensinamentos, encontrar membros e viver sob uma regra formal são relações distintas. A crítica posterior não deve ser resumida como saída documentada de uma ordem à qual ele comprovadamente teria pertencido.

Os nomes familiares também importam. A conversa anterior ao Jordão acontece com a mãe sobrevivente na família reunida. A visitação e a busca no Templo concernem a outros momentos. Antes de relacionar comunidade e preparação espiritual, identifique de quem se fala e em qual etapa da vida. Esse pequeno hábito evita várias contradições aparentemente misteriosas.`);
add(18,['ga123','ga131'],'What changes at the Temple, and what continues afterward','O que muda no Templo e o que continua depois',
`Matthew lecture VI supplies a detailed explanation of the change at twelve. Zarathustra brings capacities acquired through the Solomon preparation into the Nathan organization. Steiner connects the subsequent growth with wisdom becoming outwardly effective, with acquired habits, and with bodily expression of what had been inward warmth. The convergence is therefore followed by development; it is not the completion of the whole Christ event.

No physical infant is moved between families at this moment. In the account, an individuality changes its bodily bearer. “The two become one” refers to the meeting of preparations in the continuing Nathan Jesus. It does not mean two physical bodies fuse, nor that Buddha, Zarathustra and Christ become one interchangeable name. The Solomon child’s decline belongs to the same spiritual narrative; the passage is not a medical explanation of a historical death.

Lecture VII then distinguishes another offering at the Jordan: Zarathustra relinquishes the human organism with its etheric and astral content, and Christ enters. Keep the sequence explicit: Temple—Zarathustra enters the Nathan organization; years afterward—further preparation; Jordan—Christ enters the prepared bearer. Reading the two passages side by side removes the common confusion that the Temple event is already the Christ entry.`,
`A palestra VI sobre Mateus explica detalhadamente a mudança aos doze anos. Zaratustra traz à organização natânica capacidades adquiridas na preparação salomônica. Steiner relaciona o crescimento posterior à sabedoria atuante exteriormente, aos hábitos adquiridos e à expressão corporal do calor antes interior. A convergência é seguida por desenvolvimento; ainda não conclui todo o acontecimento do Cristo.

Nenhum bebê físico muda de família nesse momento. No relato, uma individualidade muda de portador corporal. “Os dois tornam-se um” concerne ao encontro das preparações no Jesus natânico que continua vivendo. Não significa fusão de dois corpos nem torna Buda, Zaratustra e Cristo nomes intercambiáveis. O declínio do menino salomônico pertence à mesma narrativa espiritual; a passagem não explica medicamente uma morte histórica.

A palestra VII distingue outra oferta no Jordão: Zaratustra entrega o organismo humano com seu conteúdo etérico e astral, e entra o Cristo. Preserve a sequência: Templo—Zaratustra entra na organização natânica; anos seguintes—preparação posterior; Jordão—o Cristo entra no portador preparado. Ler as duas passagens lado a lado desfaz a confusão frequente de que o Templo já seria a entrada do Cristo.`);
add(19,['ga148','ga8'],'Three encounters form one deepening question','Três encontros aprofundam uma mesma pergunta',
`The Fifth Gospel gives the encounters a connected movement. First, Jesus experiences a gap between inherited sacred words and the capacity to hear their meaning. Next, the account places him before suffering people at a neglected cult altar; the issue becomes whether old ritual can still bring the help they need. Finally, Essene discipline offers a powerful form of protected spiritual life, but raises the question of the people outside its protection. These are different experiences of the same difficulty: how can spiritual life reach humanity in its actual condition?

The details improve the explanation. “Bath-Kol” names a voice of inspiration in the first encounter and an altered voice in the altar episode. At the Essene gates, Jesus perceives Lucifer and Ahriman fleeing and asks where they go. In the following conversation with Mary, the account states his conclusion: protecting the community sends those powers toward others. The criticism concerns the cost of a protected purity, not a denial of every gift of communal discipline.

The six-year phases are a teaching outline, not airtight boundaries. Lecture IV mentions early journeys already around sixteen to eighteen, and explicitly leaves the altar’s exact location uncertain. Preserve that uncertainty instead of inventing travel destinations. The source claims spiritual perception; the course explains its argument without treating the episodes as newly established historical evidence.`,
`O Quinto Evangelho dá aos encontros um movimento relacionado. Primeiro, Jesus vive a distância entre palavras sagradas recebidas e a capacidade de ouvir seu sentido. Depois, o relato o coloca diante de pessoas sofrendo num altar abandonado; a questão é se o antigo ritual ainda oferece a ajuda necessária. Por fim, a disciplina essênia oferece vida espiritual protegida, mas suscita a pergunta pelos que ficam fora. São experiências diferentes da mesma dificuldade: como a vida espiritual pode alcançar a condição humana real?

Os detalhes esclarecem. “Bath-Kol” designa uma voz inspiradora no primeiro encontro e uma voz transformada no episódio do altar. Nos portões essênios, Jesus percebe Lúcifer e Ahriman fugindo e pergunta para onde vão. Na conversa seguinte com Maria, o relato apresenta a conclusão: proteger a comunidade encaminha essas forças a outras pessoas. A crítica concerne ao custo da pureza protegida, sem negar todos os dons da disciplina comunitária.

As fases de seis anos são um esquema didático, não fronteiras rígidas. A palestra IV menciona viagens já entre dezesseis e dezoito anos e deixa incerto o lugar exato do altar. Preserve essa incerteza, sem inventar destinos. A fonte reivindica percepção espiritual; o curso explica seu argumento sem tratar os episódios como evidência histórica recém-estabelecida.`);
add(20,['ga148','ga123'],'Mary’s listening, two mothers and the Jordan threshold','A escuta de Maria, as duas mães e o limiar do Jordão',
`In the Fifth Gospel’s fifth lecture, Jesus tells the surviving mother what the three encounters have meant. She initially recalls his great gifts; he explains why reviving ancient wisdom or protected discipline alone would not answer the condition of humanity. As she listens with love, the account describes his accumulated experience passing, as it were, into her heart. Ordinary listening is an analogy for this relationship; Steiner is describing an additional spiritual transformation.

The sequence is precise enough to keep three moments distinct. The conversation accompanies Zarathustra’s withdrawal. Jesus goes toward John. At the Baptism, Christ enters the prepared bodily organization. The passage also describes the surviving mother as becoming permeated by the soul of the Nathan mother who had died. This is a relationship between two mothers within Steiner’s account, not a statement that the women had always been one physical person.

That directly checked passage strengthens the course’s source basis, but does not prove the separate identification “Mary is Heavenly Eve”. Brian marks that proposal as his conjecture. Nor should a relative’s alarm in the narrative become a psychiatric diagnosis. What the lesson needs is the transition of spiritual participants and Mary’s role in it, explained with the limits of each claim visible.`,
`Na quinta palestra do Quinto Evangelho, Jesus conta à mãe sobrevivente o sentido dos três encontros. Ela recorda seus grandes dons; ele explica por que reavivar a sabedoria antiga ou a disciplina protegida não atenderia, por si só, à condição humana. Ao escutá-lo com amor, ela recebe no coração, por assim dizer, sua experiência acumulada. A escuta cotidiana oferece uma analogia; Steiner descreve uma transformação espiritual adicional.

A sequência permite distinguir três momentos. A conversa acompanha a retirada de Zaratustra. Jesus segue em direção a João. No Batismo, o Cristo entra na organização corporal preparada. A passagem também descreve a mãe sobrevivente como permeada pela alma da mãe natânica que morreu. É uma relação entre duas mães no relato de Steiner, não a afirmação de que sempre foram uma única pessoa física.

A passagem agora conferida fortalece as fontes do curso, mas não prova a identificação separada “Maria é Eva celeste”. Brian apresenta essa proposta como sua conjectura. O espanto dos parentes na narrativa tampouco deve tornar-se diagnóstico psiquiátrico. A lição precisa explicar a transição dos participantes espirituais e o papel de Maria, mantendo visíveis os limites de cada afirmação.`);
add(21,['ga148'],'Why a lament differs from a petition','Por que um lamento difere de um pedido',
`The altar episode in The Fifth Gospel presents the altered Bath-Kol as a voice naming humanity’s estrangement: evil, selfhood, daily bread and separation from a heavenly kingdom. Its movement is diagnostic and sorrowful. A petition instead addresses someone and asks for a changed relationship or help. Hearing this difference makes the lecture’s comparison with the Lord’s Prayer more intelligible than treating the two as merely opposite word orders.

Steiner’s 1950 edition prints both the German formulation and an English rendering. It describes this as his rendering of a spiritual experience, not a recovered ancient manuscript. The plural heavenly “Fathers” in that formulation and the singular “Father” of the familiar prayer should therefore be noticed without inventing a documented linguistic evolution between them.

The text’s role in the preparation narrative is to deepen the question of how human beings can regain relationship rather than remain isolated in selfhood. The course’s move from naming a problem to asking for help and considering a deed is an original practical extension. It illustrates the change of direction, without claiming that a short daily exercise recreates the source’s spiritual experience.`,
`O episódio do altar no Quinto Evangelho apresenta a Bath-Kol transformada como voz que nomeia o afastamento humano: mal, individualidade, pão cotidiano e separação do reino celeste. Seu movimento é diagnóstico e doloroso. Um pedido dirige-se a alguém e solicita ajuda ou mudança na relação. Perceber a diferença esclarece a comparação com o Pai-Nosso, além de tratar os textos como simples inversões de palavras.

A edição de 1950 imprime a formulação alemã e uma versão inglesa. Apresenta-as como expressão de Steiner para uma experiência espiritual, não como manuscrito antigo recuperado. Observe, portanto, os “Pais” celestes no plural e o “Pai” singular da oração conhecida, sem inventar uma evolução linguística documentada entre ambos.

Na narrativa da preparação, o texto aprofunda a pergunta de como recuperar a relação, em vez de permanecer isolado em si. A passagem didática de nomear um problema a pedir ajuda e considerar um ato é uma ampliação prática original. Ilustra uma mudança de direção, sem afirmar que um exercício breve recria a experiência espiritual descrita pela fonte.`);
add(22,['ga131'],'“Phantom” concerns form, not a ghost or the etheric body','“Fantoma” concerne à forma, não a um fantasma ou ao corpo etérico',
`Lecture VI of From Jesus to Christ distinguishes the substances of a body from the spiritual form-organization that makes them a human body. Steiner calls that form-organization the “Phantom”. He uses the sculptor’s relationship to a form as an analogy, while saying the human form is a real spiritual organization in his account. A phantom here is not a frightening apparition or simply another name for the etheric body.

The distinctions can now be stated together: physical substances are the material content; the phantom concerns the spiritual formative organization of the physical body; the etheric concerns life organization. They cooperate in the living human being but are not interchangeable concepts. An ordinary pattern-and-material example can clarify what distinction is intended, without establishing the existence of the phantom.

Lecture VII then interprets resurrection as restoration and communication of an incorruptible formative reality, rather than restarting the ordinary material corpse. This indicates why Brian recommends the book after the Jordan narrative. It opens the question of what Christ gives through Golgotha, which requires further study. This brief explanation defines the next question accurately; it does not turn the present preparation course into a complete teaching of resurrection.`,
`A palestra VI de De Jesus a Cristo distingue as substâncias corporais da organização espiritual da forma que faz delas um corpo humano. Steiner chama essa organização de “Fantoma”. Usa como analogia a relação do escultor com a forma, mas afirma que a forma humana é uma organização espiritual real em seu relato. Aqui, fantoma não significa aparição assustadora nem é apenas outro nome para corpo etérico.

Podemos reunir as distinções: substâncias físicas constituem o conteúdo material; o fantoma concerne à organização espiritual formativa do corpo físico; o etérico, à organização vital. Cooperam no ser humano vivo, mas não são conceitos intercambiáveis. Um exemplo cotidiano entre padrão e material esclarece a distinção pretendida, sem estabelecer a existência do fantoma.

A palestra VII interpreta a ressurreição como restauração e comunicação de uma realidade formativa incorruptível, além de reativar o cadáver material comum. Isso esclarece a recomendação de Brian após a narrativa do Jordão. Abre a pergunta pelo que o Cristo oferece através do Gólgota, exigindo estudo posterior. A explicação breve define corretamente a próxima questão; não transforma o curso da preparação num ensino completo da ressurreição.`);
