import fs from 'node:fs';
const anchors=JSON.parse(fs.readFileSync(new URL('./anchor-questions.json',import.meta.url),'utf8'));
// Every option receives its own explanation. No score or pass requirement.
const wrong = [
 ['Birth begins the preparation; it is not the Jordan.','','The two households belong to the earlier preparation.'],
 ['','Selfishness is one possible use of individuality, not its definition.','The organ of sight is the eye, not the spiritual I.'],
 ['An emphasis does not exclude other faculties.','Patient comparison keeps the differences visible.',''],
 ['Luke narrates shepherds and the manger.','','These events appear explicitly in Matthew, not both accounts.'],
 ['','A rule may be followed from an understood purpose.','Habit and compulsion can also feel like personal desire.'],
 ['Old Moon is a cosmic stage, not today’s Moon.','The framework is spiritual cosmology, not archaeology.',''],
 ['Enthusiasm can contribute imagination and initiative.','','Practical organization can serve a humane purpose.'],
 ['','Anticipation can still be mistaken or used irresponsibly.','An everyday example does not establish cosmic chronology.'],
 ['Luke does not list fourteen Zarathustra incarnations.','An astronomical table would not establish spiritual identities.',''],
 ['The claimed gifts concern spiritual organizations.','','A spiritual gift is not an excavated object.'],
 ['','A feeling of spirituality does not separate perception from conclusion.','Thought can form a reasonable inference without being direct perception.'],
 ['The correspondence is not a genetic law.','Understanding the landmarks comes before memorizing every name.',''],
 ['Luke does not explicitly identify Mary as heavenly Eve.','','Similar names do not establish the proposed spiritual identity.'],
 ['','The twelve-year-old scene occurs after the infancy narratives.','The Baptism belongs to the adult threshold.'],
 ['Herod belongs to Matthew’s danger narrative.','Netzer belongs to the lecturer’s Nazareth tradition.',''],
 ['The images invite the capacities to cooperate.','','The images are not ranks of people.'],
 ['','Unverified dates would add false precision.','The key concerns these households, not all later incarnations.'],
 ['The Temple is the childhood convergence, not a baptism.','Luke does not explicitly describe the spiritual transfer.',''],
 ['The account is not a dismissal of living communities.','','The detailed tin itinerary is not source-established here.'],
 ['','The preparation includes acquired earthly experience.','The adult Baptism is not another infant birth.'],
 ['Prayer does not guarantee a desired outcome.','This lesson compares themes, not a proven exact derivation.',''],
 ['The talks only introduce these questions.','','GA 131 and GA 114 are different cycles.'],
 ['','Different traditions retain distinct doctrines and voices.','Respect includes listening to traditions’ own accounts.'],
 ['Course completion does not establish spiritual rank.','The central task is understanding relationships, not cosmic dates.','']
];
// Portuguese anchor questions and explanations, aligned with the supplied bank.
const portuguese = [
 ['O que marca o Jordão neste relato?',['O nascimento em Belém.','A entrada do Cristo no portador humano preparado.','O primeiro encontro das famílias.'],['O nascimento inicia a preparação.','A entrada do Cristo difere do nascimento e da convergência.','As famílias pertencem à preparação anterior.']],
 ['O que designa principalmente o Eu?',['Empenho individual e responsabilidade.','Apenas desejo egoísta.','O órgão físico da visão.'],['O Eu é o centro da iniciativa responsável.','Egoísmo é um uso possível, não a definição.','O olho físico não é o Eu espiritual.']],
 ['Por que estudar quatro perspectivas?',['Cada Evangelho contém só uma capacidade.','As diferenças podem ser ignoradas.','Cada um pode enfatizar um aspecto.'],['Ênfase não exclui outras capacidades.','A comparação preserva diferenças.','Perspectivas diferentes ampliam a compreensão.']],
 ['Qual relato inclui magos e fuga ao Egito?',['Lucas.','Mateus.','Ambos explicitamente.'],['Lucas narra pastores e manjedoura.','Esses episódios aparecem na infância em Mateus.','Não aparecem explicitamente em ambos.']],
 ['Por que obedecer a “seja livre” é insuficiente?',['Obedecer não estabelece compreensão própria.','Toda regra é ruim.','Todo impulso é liberdade.'],['Liberdade envolve compreender e escolher.','Uma regra pode ter finalidade compreendida.','Hábitos e compulsões também parecem desejos próprios.']],
 ['Qual distinção é correta?',['Antiga Lua é a Lua atual.','Todos os estágios são arqueológicos.','Estágios cósmicos, épocas terrestres e períodos culturais diferem.'],['Antiga Lua é um estágio cósmico.','O quadro é cosmologia espiritual.','São níveis distintos do mapa.']],
 ['O que exige a ação equilibrada?',['Evitar todo entusiasmo.','Usar capacidades para uma finalidade humana responsável.','Abandonar a organização.'],['Entusiasmo pode oferecer iniciativa.','A finalidade orienta o uso dos dons.','Organização pode servir às pessoas.']],
 ['O que o pensamento acrescenta à memória?',['Antecipar consequências.','Perfeição moral automática.','Provar a cronologia cósmica.'],['Recordar e antecipar são atos distintos.','A previsão pode falhar ou ser mal utilizada.','Uma analogia não prova a cronologia.']],
 ['De onde vem a proposta de catorze encarnações?',['De uma lista explícita em Lucas.','De uma tabela astronômica.','Do estudo de Welburn citado pelo palestrante.'],['Lucas não apresenta essa lista.','Astronomia não estabelece identidades espirituais.','O palestrante distingue essa proposta do que Steiner diz ali.']],
 ['Como são apresentados os dons a Hermes e Moisés?',['Como genética comum.','Como continuidade espiritual no relato.','Como inventário arqueológico.'],['São organizações espirituais propostas.','O modo de transmissão descrito é espiritual.','Não são objetos escavados.']],
 ['Como separar observação e inferência?',['O que descrevo e o que concluo.','O que parece espiritual e o que não parece.','Fatos e tudo que envolve pensamento.'],['A conclusão pode ser razoável, mas difere da percepção.','O sentimento não estabelece a distinção.','Pensar pode formar inferências fundamentadas.']],
 ['O que ilustra a estrutura genealógica?',['Uma regra genética moderna.','A obrigação de decorar todos os nomes.','Preparação persistente entre gerações.'],['A correspondência não é lei genética.','Os marcos podem ser compreendidos primeiro.','Essa é a função interpretada no curso.']],
 ['Como apresentar Maria como Eva celeste?',['Como afirmação direta de Lucas.','Como conjectura explícita do palestrante.','Como prova por nomes semelhantes.'],['Lucas não faz essa identificação.','P1 marca expressamente sua autoria e limite.','Semelhança de nomes não prova identidade.']],
 ['O que antecede a visitação em Lucas?',['A anunciação a Maria.','O episódio aos doze anos.','O Batismo no Jordão.'],['A mensagem antecede o encontro com Isabel.','O episódio é posterior à infância.','O Batismo pertence à vida adulta.']],
 ['Quem a passagem de Steiner relaciona a Simeão?',['Herodes.','Netzer.','Asita.'],['Herodes pertence ao perigo em Mateus.','Netzer pertence à tradição de Nazaré.','O dossiê identifica Asita na GA 114.']],
 ['O que convidam as imagens de coração e cabeça?',['Escolher uma capacidade para sempre.','Unir calor e compreensão na boa ação.','Classificar pessoas em posições fixas.'],['As capacidades devem cooperar.','O verso orienta ambas ao bem com propósito.','As imagens não são classificações humanas.']],
 ['O que deve esclarecer a chave familiar?',['A qual família e menino cada afirmação se refere.','Datas exatas não verificadas.','Todas as encarnações posteriores.'],['Nomes estáveis evitam confusão.','Datas incertas dariam falsa precisão.','A chave trata destas famílias.']],
 ['O Templo é idêntico ao Jordão?',['Sim, ambos são batismos.','Sim, Lucas afirma a transferência.','Não: a relação de Zaratustra e a entrada do Cristo diferem.'],['O Templo é a convergência na infância.','Lucas narra a cena, não a transferência técnica.','Os participantes e acontecimentos são distintos.']],
 ['Qual pergunta central surge dos encontros?',['Qual religião atual rejeitar.','Como a sabedoria recebida pode atender às necessidades humanas.','Como provar o itinerário do estanho.'],['O relato não dispensa comunidades vivas.','O tema é significado e acesso.','O itinerário não foi estabelecido.']],
 ['O que antecede a entrada do Cristo?',['Preparação combinada e retirada de Zaratustra.','Ausência completa de experiência.','Nascimento de um terceiro bebê.'],['O relato distingue preparar, retirar e receber.','A preparação inclui experiência adquirida.','O Batismo adulto não é outro nascimento infantil.']],
 ['Como compreender a relação lamento–oração?',['Método garantido de obter resultados.','Derivação exata provada palavra por palavra.','Transformação espiritual dos temas.'],['Oração não garante resultados.','A lição compara temas.','O lamento da separação torna-se busca de relação.']],
 ['Por que recomendar a GA 131?',['Porque já foi ensinada integralmente.','Porque desenvolve questões apenas abertas aqui.','Porque é outro nome da GA 114.'],['As palestras apenas introduzem essas questões.','Ressurreição e fantoma exigem estudo próprio.','São ciclos diferentes.']],
 ['O que exige uma universalidade respeitosa?',['Explicar a síntese sem falar por todas as tradições.','Dizer que todas são idênticas.','Ignorar sua compreensão própria.'],['Convicção e escuta podem coexistir.','As tradições possuem diferenças.','Respeitar inclui ouvir as próprias vozes.']],
 ['Qual é um sinal adequado de compreensão?',['Alegar superioridade espiritual.','Decorar toda data cósmica.','Explicar relações e aplicar compreensão com cuidado.'],['Concluir não estabelece posição espiritual.','Datas não são a finalidade central.','O curso une entendimento e ação responsável.']]
];
const applications = [
 ['A friend needs help. Which response joins the two qualities?','Listen freshly and use experience to judge what helps.','Assume every situation is identical.','Avoid judgment because openness is enough.','Fresh attention protects individuality; experience supports a fitting response.','Assuming sameness lets experience become a fixed defense.','Openness does not remove the need for discernment.',
 'Um amigo precisa de ajuda. Qual resposta une as qualidades?','Escutar com abertura e usar experiência para discernir.','Presumir que toda situação é igual.','Evitar julgamento porque abertura basta.','Atenção renovada e experiência ajudam a responder adequadamente.','Presumir igualdade transforma experiência em defesa fixa.','Abertura não elimina discernimento.'],
 ['You feel anger and choose a careful reply. What relationship is illustrated?','The I can work upon a conscious reaction.','The astral body is the physical eye.','Life processes stop during anger.','Individual initiative can shape a response to feeling.','Astral concerns conscious experience, not sight as an organ.','The example distinguishes continuing life from conscious reaction.',
 'Você sente raiva e escolhe responder com cuidado. O que isso ilustra?','O Eu pode trabalhar sobre uma reação consciente.','O corpo astral é o olho físico.','Processos vitais param durante a raiva.','A iniciativa individual pode dar forma à resposta.','Astral concerne à experiência, não ao órgão da visão.','A vida continua enquanto a reação é percebida.'],
 ['Luke includes an active deed. Does that defeat the compassion emphasis?','No; emphasis does not mean exclusive content.','Yes; Luke can contain no action.','Yes; every Gospel must have identical beginnings.','A perspective highlights rather than exhausts its subject.','The lesson expressly includes multiple faculties in each Gospel.','The beginnings are different and meaningful.',
 'Um ato aparece em Lucas. Isso invalida a ênfase na compaixão?','Não; ênfase não significa exclusividade.','Sim; Lucas não pode conter ação.','Sim; todos devem começar igualmente.','Uma perspectiva destaca sem esgotar o assunto.','Cada Evangelho inclui várias capacidades.','As aberturas diferem e têm significado.'],
 ['How should a detail absent from Luke be described?','It does not appear in this account.','It could never have happened.','Luke explicitly proves two children.','A textual omission is a limited observation.','Omission alone does not establish nonoccurrence.','The two-child account is an additional interpretation.',
 'Como descrever um detalhe ausente em Lucas?','Não aparece neste relato.','Nunca poderia ter ocorrido.','Lucas prova explicitamente dois meninos.','A ausência textual é observação limitada.','Omissão não estabelece inexistência.','Dois meninos é interpretação adicional.'],
 ['Someone freely follows a useful rule. Is that impossible here?','No; understood purpose can guide a chosen action.','Yes; every rule destroys freedom.','Yes; freedom requires acting without reasons.','The motive and understanding matter.','The lesson distinguishes obedience alone from deliberate participation.','Reasons can make purpose conscious.',
 'Alguém segue livremente uma regra útil. Isso é impossível?','Não; a finalidade compreendida orienta uma escolha.','Sim; toda regra destrói liberdade.','Sim; liberdade exige agir sem razões.','Motivo e compreensão importam.','A lição distingue obediência e participação deliberada.','Razões tornam consciente a finalidade.'],
 ['Where does ancient Persia belong in the map?','A cultural period within post-Atlantis.','A cosmic stage before Old Saturn.','Another name for today’s Moon.','The levels are nested.','Persia is not a cosmic stage.','It is not the Moon at either level.',
 'Onde fica a Pérsia antiga no mapa?','Num período cultural pós-atlântico.','Num estágio anterior ao Antigo Saturno.','Como outro nome da Lua atual.','Os níveis estão encaixados.','Pérsia não é um estágio cósmico.','Não designa a Lua.'],
 ['A spreadsheet ignores guests’ access needs. What should change?','Bring organization back to the human purpose.','Discard all planning forever.','Demand compliance because calculation is enough.','Order is useful when it serves actual people.','The capacity is useful; its use needs correction.','Rigid control forgets the purpose.',
 'Uma planilha ignora acessibilidade. O que mudar?','Reorientar a organização à finalidade humana.','Abandonar todo planejamento.','Exigir cumprimento porque cálculo basta.','A ordem é útil ao servir pessoas.','A capacidade é útil; o uso precisa mudar.','Rigidez esquece a finalidade.'],
 ['You remember a result and predict a similar one. What remains necessary?','Attention to changed conditions.','Certainty that predictions cannot fail.','A judgment of someone’s spiritual worth from posture.','Reasoning remains answerable to the situation.','Predictions can be mistaken.','Bodily ability does not determine worth.',
 'Você prevê um resultado semelhante ao anterior. O que ainda precisa?','Atenção às condições modificadas.','Certeza de que previsões nunca falham.','Julgar valor espiritual pela postura.','O raciocínio responde à situação.','Previsões podem falhar.','Capacidade corporal não determina valor.'],
 ['What kind of source is The Book of the Bee?','A medieval compilation preserving an attributed tradition.','An ancient eyewitness recording.','A modern astronomical dataset.','Its historical status differs from the story it preserves.','The compilation is later than the attributed conversation.','The work is not astronomical data.',
 'Que fonte é O Livro da Abelha?','Uma compilação medieval de tradição atribuída.','Um registro antigo de testemunha ocular.','Dados astronômicos modernos.','A data da compilação difere da história preservada.','É posterior à conversa atribuída.','Não é um conjunto de dados astronômicos.'],
 ['Who has the cow dream in the corrected narrative?','Pharaoh.','Joseph in his personal childhood dream.','Melchizedek when renaming Abram.','Genesis 41 distinguishes Pharaoh’s dream from Joseph’s.','Joseph’s personal dreams concern sheaves and heavenly bodies.','God’s renaming in Genesis 17 is a different episode.',
 'Quem sonha com vacas no relato corrigido?','O faraó.','José em seu sonho pessoal da infância.','Melquisedeque ao renomear Abrão.','Gênesis 41 distingue o sonho do faraó.','Os sonhos pessoais de José envolvem feixes e astros.','Deus muda o nome em outro episódio.'],
 ['Drooping leaves lead you to suspect thirst. What is the suspicion?','An inference to check.','A direct observation of every cause.','Proof of the plant’s spiritual history.','A conclusion can be reasonable while requiring more observation.','Visible leaves do not display every cause.','This observation does not establish spiritual history.',
 'Folhas caídas fazem suspeitar de sede. O que é a suspeita?','Uma inferência a verificar.','Observação direta de todas as causas.','Prova da história espiritual da planta.','A conclusão pode exigir mais observação.','A aparência não mostra todas as causas.','Não estabelece história espiritual.'],
 ['What differs between Matthew and Luke’s genealogical directions?','Matthew moves from Abraham forward; Luke traces backward to Adam.','Both begin from Adam and move forward.','Neither concerns ancestry.','Their scope and direction help frame the comparison.','Matthew begins from Abraham; Luke works backward.','Both contain genealogical material.',
 'Como diferem as direções genealógicas?','Mateus avança de Abraão; Lucas remonta a Adão.','Ambos avançam a partir de Adão.','Nenhum trata de ancestralidade.','Direção e alcance ajudam a comparar.','Mateus começa em Abraão; Lucas remonta.','Ambos contêm genealogias.'],
 ['Does never incarnating ordinarily mean the preserved soul was inactive?','No; the lecturer describes spiritual participation.','Yes; it had no spiritual life.','Yes; it must be identical to John’s earthly line.','Spiritual manifestation and ordinary incarnation are distinct here.','The account describes pre-earthly activity.','The preserved counterpart and earthly line are distinguished.',
 'Não encarnar normalmente significa inatividade?','Não; o relato descreve participação espiritual.','Sim; não havia vida espiritual.','Sim; é idêntica à linha terrena de João.','Manifestação espiritual e encarnação diferem aqui.','O relato descreve atuação pré-terrena.','Contraparte e linha terrena são distintas.'],
 ['What ethical attention appears in Mary’s song?','Concern for the lowly and hungry.','Only decoration without human concern.','Instructions to ignore questioning.','The song widens the scene toward people’s conditions.','Removing that concern loses its ethical content.','The narrative itself includes questions.',
 'Que atenção ética aparece no cântico de Maria?','Cuidado com humildes e famintos.','Decoração sem preocupação humana.','Ordem para ignorar perguntas.','O cântico amplia a atenção às condições das pessoas.','Isso perderia o conteúdo ético.','A própria narrativa inclui perguntas.'],
 ['In this account, Buddha’s relation to the Nathan child is what kind?','Spiritual influence and radiance.','Another infant physically in the manger.','A claim that all Buddhists interpret Luke this way.','The proposed relationship concerns the soul organization.','The teaching does not add Buddha as an infant.','Other traditions retain their own accounts.',
 'Como Buda se relaciona ao menino natânico?','Por influência e irradiação espirituais.','Como outro bebê na manjedoura.','Como interpretação de Lucas por todos os budistas.','A relação proposta concerne à organização da alma.','O ensino não acrescenta Buda como bebê.','Outras tradições preservam relatos próprios.'],
 ['A kind suggestion adds a burden. What is missing?','Accurate understanding of the actual need.','All feeling should be eliminated.','The person must accept help to prove gratitude.','Warmth needs insight to shape a useful deed.','Feeling can contribute care.','Respect includes allowing refusal.',
 'Uma sugestão bondosa aumenta a carga. O que falta?','Compreender a necessidade real.','Eliminar todo sentimento.','Exigir que a ajuda seja aceita.','Calor precisa de compreensão para orientar o ato.','Sentimento pode contribuir cuidado.','Respeito permite recusar.'],
 ['Why omit exact sibling counts from the household key?','The transcript is uncertain and the roles do not require them.','The key should hide which family is meant.','Luke explicitly provides every proposed esoteric count.','Stable relationships are enough for this teaching.','The purpose is to clarify the families.','Those proposed counts are not supplied explicitly by Luke.',
 'Por que omitir contagens exatas de irmãos?','A transcrição é incerta e as funções não exigem números.','Para esconder a família referida.','Lucas fornece todas as contagens esotéricas.','Relações estáveis bastam à lição.','A finalidade é esclarecer famílias.','Lucas não fornece essas contagens propostas.'],
 ['What does Luke narrate directly at twelve?','Jesus listening and questioning among the teachers.','A technical account of Zarathustra’s transfer.','The exact age of a second child.','The interpretation is a further source layer.','The technical explanation comes through anthroposophy.','Luke does not state another child’s age.',
 'O que Lucas narra diretamente aos doze anos?','Jesus ouvindo e perguntando entre os mestres.','Relato técnico da transferência de Zaratustra.','Idade exata de outro menino.','A interpretação acrescenta outra camada.','A explicação técnica vem da antroposofia.','Lucas não informa essa idade.'],
 ['What question does the Essene expansion raise?','Who remains outside a protected community’s benefit?','Whether every discipline is selfish.','Whether Britain’s tin itinerary is proved.','The issue is access and responsibility beyond the gates.','The account does not reject every discipline.','That itinerary remains unresolved.',
 'Que pergunta surge da ampliação essênia?','Quem permanece fora do benefício protegido?','Se toda disciplina é egoísta.','Se o itinerário britânico foi provado.','O tema é acesso e responsabilidade além dos portões.','O relato não rejeita toda disciplina.','O itinerário permanece incerto.'],
 ['How should Mary’s renewal be understood in this lesson?','As spiritual relationship, keeping the Eve conjecture separate.','As established physical de-aging.','As a prescription to erase students’ agency.','The source layers concern spiritual transformation.','The lesson does not establish bodily age reversal.','The specialized event does not instruct self-erasure.',
 'Como compreender a renovação de Maria?','Como relação espiritual, separando a conjectura de Eva.','Como rejuvenescimento físico estabelecido.','Como ordem para apagar autonomia.','As camadas concernem à transformação espiritual.','Não se estabelece reversão corporal de idade.','O evento não exige autoanulação.'],
 ['What nondevotional exercise fits this lesson?','Name a need and choose a consistent practical response.','Require everyone to recite the prayer.','Assume every petition guarantees success.','The exercise follows the movement toward responsibility.','Devotion is optional.','Prayer is not a guarantee of outcomes.',
 'Qual exercício não devocional se ajusta?','Nomear uma necessidade e escolher uma resposta prática.','Exigir que todos recitem a oração.','Presumir sucesso garantido.','O exercício acompanha a responsabilidade.','Devoção é opcional.','Oração não garante resultados.'],
 ['What should a future resurrection course begin with?','Close reading of identified primary sources such as GA 131.','Invented details filling the brief closing remarks.','A claim that this course has already taught everything.','The next inquiry requires its own source work.','The current remarks do not supply the missing explanation.','The course explicitly marks its endpoint and limits.',
 'Como começar um curso futuro de ressurreição?','Ler fontes primárias identificadas, como a GA 131.','Inventar o que falta nos comentários finais.','Afirmar que tudo já foi ensinado.','A nova pesquisa exige fontes próprias.','Os comentários não fornecem toda explicação.','O curso marca seu limite.'],
 ['Someone describes their religion differently from this synthesis. What is respectful?','Hear their account before offering an interpretation.','Insist they secretly agree.','Treat differences as proof of lesser worth.','Listening allows conviction and accurate comparison.','Universal intent does not establish another person’s assent.','Difference is not a ranking of worth.',
 'Alguém descreve sua religião de outra maneira. O que é respeitoso?','Ouvir antes de oferecer uma interpretação.','Insistir que concorda secretamente.','Tratar diferenças como valor inferior.','Escuta permite convicção e comparação correta.','Intenção universal não prova concordância alheia.','Diferença não classifica valor.'],
 ['Your help has an unexpected result. What next?','Attend to the result and adjust responsibly.','Ignore it because good intention proves success.','Claim spiritual superiority from completing lessons.','Consequences can teach and refine a considered action.','Intention alone does not establish effectiveness.','Completion is not spiritual rank.',
 'Sua ajuda tem resultado inesperado. E agora?','Observar e ajustar responsavelmente.','Ignorar porque boa intenção prova sucesso.','Alegar superioridade por concluir lições.','Consequências podem aperfeiçoar a ação.','Intenção não prova eficácia.','Conclusão não estabelece posição espiritual.']
];
export function checksFor(number,lang) {
 const anchor=anchors[number-1],pt=lang==='pt',p=portuguese[number-1];
 const first=pt?{question:p[0],options:p[1],answer:anchor.answer,reasons:p[2]}:{...anchor,reasons:anchor.options.map((_,i)=>i===anchor.answer?anchor.explanation:wrong[number-1][i])};
 const a=applications[number-1].slice(pt?7:0,pt?14:7),shift=number%3;
 const opts=[a[1],a[2],a[3]],reasons=[a[4],a[5],a[6]];
 // Rotate positions so application answers do not all occupy the first slot.
 const order=[0,1,2].map(i=>(i+shift)%3);
 const second={question:a[0],options:order.map(i=>opts[i]),reasons:order.map(i=>reasons[i]),answer:order.indexOf(0)};
 return [first,second];
}
