// Targeted readings of supplied editions; these records do not claim full-book study.
export const reviewedResources = [
 {id:'ga8',en:'Christianity as Mystical Fact',pt:'O Cristianismo como fato místico',edition:'GA 8 · Andrew Welburn translation · Anthroposophic Press, 1997',locator:'Ch. 1, pp. 1–4 (PDF 25–28); ch. 6, pp. 101–104 (PDF 125–128); ch. 10, pp. 144–146 (PDF 168–170)',enUse:'Background on initiation, Gospel perspectives and the movement from the Mysteries to Christianity. Added study background; not identified as a title Brian names in these three talks.',ptUse:'Contexto sobre iniciação, perspectivas evangélicas e passagem dos Mistérios ao cristianismo. Aprofundamento acrescentado; não identificado como título citado por Brian nestas três palestras.'},
 {id:'ga11',en:'Cosmic Memory',pt:'Memória Cósmica',edition:'GA 11 · Karl E. Zimmer translation · first paperback edition, 1976; translation ©1959',locator:'“Our Atlantean Ancestors”, pp. 42–56 (PDF 36–50)',enUse:'Memory, language and comparing experiences. The edition also contains racial hierarchies and dated claims about peoples; these are acknowledged as source limitations and are not taught as current anthropology.',ptUse:'Memória, linguagem e comparação de experiências. A edição também contém hierarquias raciais e afirmações datadas sobre povos; são reconhecidas como limites da fonte e não ensinadas como antropologia atual.'},
 {id:'ga13',en:'An Outline of Occult Science',pt:'Um Esboço da Ciência Oculta',edition:'GA 13 · supplied text title page: Anthroposophic Press, New York, 1922',locator:'Ch. II, printed-text markers pp. 16–30 (PDF 27–34); ch. IV, pp. 104–109 (PDF 80–83)',enUse:'Clarifies the four members, the special meaning of “body” and spiritual cosmology. The upload label says 2011; the embedded title page says 1922. The Markdown is a reading aid checked against the PDF.',ptUse:'Esclarece os quatro membros, o sentido especial de “corpo” e a cosmologia espiritual. O nome do arquivo indica 2011; a folha de rosto interna indica 1922. O Markdown serve de apoio, conferido com o PDF.'},
 {id:'ga103',en:'The Gospel of St. John',pt:'O Evangelho de João',edition:'GA 103 · Hamburg, May 1908 · Maud B. Monges translation · revised edition 1962, second printing 1973',locator:'Lecture I, pp. 19–20 and 24–25 (PDF 21–22, 26–27)',enUse:'Explains why Logos concerns creative spiritual origin rather than merely a spoken word. Added background from an identified John cycle, not a claim that Brian specified this edition.',ptUse:'Explica por que Logos designa uma origem espiritual criadora, além de uma palavra falada. Contexto de um ciclo de João identificado, sem afirmar que Brian indicou esta edição.'},
 {id:'ga123',en:'The Gospel of St. Matthew',pt:'O Evangelho de Mateus',edition:'GA 123 · Dorothy Osmond and Mildred Kirkcaldy translation · fourth edition 1965, reprinted 1985',locator:'Lecture III, pp. 67–70 (PDF 69–72); lecture VI, pp. 110–116 (PDF 112–118); lecture VII, pp. 125–128 (PDF 127–130)',enUse:'Checks genealogy, the two children, Temple convergence and the separate Jordan entry. The supplied file label says January 2000; its imprint says reprinted 1985. GA 123 VI–VII speaks of the Solomon child at twelve at transfer, while Brian later entertains larger age gaps; no exact harmonized gap is asserted.',ptUse:'Confere genealogia, dois meninos, convergência no Templo e entrada distinta no Jordão. O nome do arquivo indica janeiro de 2000; o expediente indica reimpressão de 1985. A GA 123 VI–VII fala do menino salomônico aos doze anos na transferência, enquanto Brian considera diferenças maiores; não se afirma uma diferença exata harmonizada.'},
 {id:'ga131',en:'From Jesus to Christ',pt:'De Jesus a Cristo',edition:'GA 131 · Karlsruhe, October 1911 · Rudolf Steiner Press, revised translation 1973',locator:'Lecture VI (PDF 79–83); lecture VII (PDF 89–95); opening of lecture VIII (PDF 96–98); no printed pagination in supplied PDF',enUse:'Checks physical form versus material substances, the “phantom”, and Buddha’s influence on the Nathan child. Resurrection remains a brief continuation question rather than a new course module.',ptUse:'Confere forma física e substâncias materiais, “fantoma” e influência de Buda no menino natânico. A ressurreição permanece uma breve indicação de continuidade, sem novo módulo.'},
 {id:'ga148',en:'The Fifth Gospel',pt:'O Quinto Evangelho',edition:'GA 148 selection · five Christiania lectures, 1–6 October 1913 · D. S. Osmond with M. Cotterell · London, 1950',locator:'Lecture IV, pp. 64–84 (PDF 68–88); lecture V, pp. 85–98 (PDF 89–102)',enUse:'Directly checks the pre-Jordan encounters, the Essene-gate question and the conversation with Mary. This supplied edition is five lectures, not the entire GA 148 collection.',ptUse:'Confere diretamente encontros anteriores ao Jordão, questão dos portões essênios e conversa com Maria. A edição fornecida contém cinco palestras, não toda a GA 148.'},
 {id:'bee',en:'The Book of the Bee',pt:'O Livro da Abelha',edition:'Solomon of Akhlat · English edition by E. A. Wallis Budge · internal title page 1886',locator:'Preface, PDF 6; introduction, PDF 10; ch. 37, p. 73 (PDF 78)',enUse:'Confirms the prophecy text and its medieval Christian transmission. Budge edits/translates the work; he is not its medieval author. The filename’s 2021 label does not establish a new translation.',ptUse:'Confirma a profecia e sua transmissão cristã medieval. Budge edita e traduz a obra; não é seu autor medieval. A indicação 2021 no nome do arquivo não estabelece nova tradução.'}
];
export const mismatchedResource = {
 en:'The upload named “Esoteric Christianity and the mission of Christian…” contains Art as Seen in the Light of Mystery Wisdom (GA 275), eight Dornach lectures, 28 December 1914–4 January 1915, first complete English edition 1984. Its PDF title/imprint pages 5–6 and matching Markdown were checked. It is not used as evidence for Christian Rosenkreutz or the two-child account.',
 pt:'O arquivo chamado “Esoteric Christianity and the mission of Christian…” contém Art as Seen in the Light of Mystery Wisdom (GA 275), oito palestras em Dornach, de 28 de dezembro de 1914 a 4 de janeiro de 1915, primeira edição inglesa completa de 1984. Foram conferidos folha de rosto e expediente nas páginas 5–6 do PDF e o Markdown correspondente. Não serve aqui de evidência sobre Christian Rosenkreutz ou os dois meninos.'
};
